### ISSUE TITLE
Error initializing mariadb (with or without volume for persistence)

### ISSUE THREAD

**Issue by Rhodan-FR** [bitnami/bitnami-docker-mariadb#105]
Hi

redmine / mariadb

Os Host = CentOS Linux release 7.2.1511 (Core) 
Docker = 1.13.0
Image version = 10.1.21-r0

I tried to start mariadb as described in doc with volume for persistence :
docker run -d --name redmine-mariadb --net redmine-tier --volume /var/dockerdata/containersdata/redmine-mariadb:/bitnami/mariadb bitnami/mariadb:latest
I get errors about initialization phase :
stdout log:
2017-02-15T11:27:47.367855280Z nami    INFO  Initializing mariadb
2017-02-15T11:27:59.635811382Z mariadb INFO  ==> Creating 'root' user with unrestricted access...
stderr log:
2017-02-15T11:27:59.692711434Z Error executing 'postInstallation': ERROR 1010 (HY000) at line 1: Error dropping database (can't rmdir './test', errno: 22 "Invalid argument")

without volume for persistence I get same errors:
#docker run -d --name redmine-mariadb --net redmine-tier bitnami/mariadb:latest
stdout log:
2017-02-15T11:22:54.310796882Z nami    INFO  Initializing mariadb
2017-02-15T11:23:07.066812252Z mariadb INFO  ==> Creating 'root' user with unrestricted access...
stderr log:
2017-02-15T11:23:07.130841239Z Error executing 'postInstallation': ERROR 1010 (HY000) at line 1: Error dropping database (can't rmdir './test', errno: 22 "Invalid argument")

it seems there is a script during initialization which fires this error.

Thanks

Rhodan

**Comment by Rhodan-FR** [comment]
I rebuilt and relaunched the container (without persistent volume) several time and errors are changing until retrieving same :
**Attempt 1 :**
nami    INFO  Initializing mariadb
mariadb INFO  ==> Creating 'root' user with unrestricted access...
Error executing 'postInstallation': ERROR 1010 (HY000) at line 1: Error dropping database (can't rmdir './test', errno: 22 "Invalid argument")
**Attempt 2 :**
nami    INFO  Initializing mariadb
mariadb INFO  ==> Creating 'root' user with unrestricted access...
Error executing 'postInstallation': ERROR 1227 (42000) at line 1: Access denied; you need (at least one of) the CREATE USER privilege(s) for this operation
**Attempt 3 :**
nami    INFO  Initializing mariadb
Error executing 'postInstallation': ERROR 1142 (42000) at line 1: DELETE command denied to user 'root'@'localhost' for table 'user'
**Attempt 4 :**
nami    INFO  Initializing mariadb
Error executing 'postInstallation': ERROR 1142 (42000) at line 1: DELETE command denied to user 'root'@'localhost' for table 'user'


Rhodan

**Comment by juan131** [comment]
I tried using a Red Hat 7.3 and Docker 1.13.1 and I did not find any issue running:
 
```
$ docker network create redmine-tier
$ docker run -d --name mariadb --net redmine-tier --volume /home/user/mariadb-persistence:/bitnami/mariadb bitnami/mariadb:latest
```

The problem might be related with not having writing permissions on the directory you're using as persistence directory:

```
/var/dockerdata/containersdata/redmine-mariadb
```

Could you try using a different directory where the user running the docker command has writing permissions?

**Comment by sameersbn** [comment]
@Rhodan-FR can you try remove the `/var/dockerdata/containersdata/redmine-mariadb` directory and retry launching the container (`docker run -d --name redmine-mariadb --net redmine-tier --volume /var/dockerdata/containersdata/redmine-mariadb:/bitnami/mariadb bitnami/mariadb:latest`) after executing the following commands:

```bash
mkdir -p /var/dockerdata/containersdata/redmine-mariadb
sudo chcon -Rt svirt_sandbox_file_t /var/dockerdata/containersdata/redmine-mariadb
```

If this does not help, then please check if your host is using the overlay filesystem at the storage backend for docker. We have seen issues launching containers on Redhat / CentOS setups, see https://github.com/bitnami/bitnami-docker-testlink/issues/17#issuecomment-261783035

Do let us know if this helps.

**Comment by sameersbn** [comment]
p.s. this issue may indeed be related to overlay storage driver, see https://github.com/bitnami/bitnami-docker-mariadb/issues/92

**Comment by Rhodan-FR** [comment]
I tested 
```
mkdir -p /var/dockerdata/containersdata/redmine-mariadb
sudo chcon -Rt svirt_sandbox_file_t /var/dockerdata/containersdata/redmine-mariadb
```
I got error :
`chcon: can't apply partial context to unlabeled file â€˜/var/dockerdata/containersdata/redmine-mariadbâ€™`
As not mastering chcon, I tested :
`/usr/bin/dockerd --storage-driver=devicemapper`
... and then creation of container "redmine-mariadb" is running perfectly 👍 

What is impact of using "devicemapper" driver in place of "overlay"?

Thanks

**Comment by sameersbn** [comment]
OverlayFS is new and supposed to be a faster storage driver for docker. Evidently it has issues in real use cases.

As an aside when it comes to Docker on CentOS/Redhat you should install docker using the docker packages provided by the distro and avoid using the installation instructions provide on [docker.com](https://docs.docker.com/engine/installation/linux/centos/).

One line thing i'd like to mention is in the future you can avoid the following commands,

```
mkdir -p /var/dockerdata/containersdata/redmine-mariadb
sudo chcon -Rt svirt_sandbox_file_t /var/dockerdata/containersdata/redmine-mariadb
```

by appending `:Z` to the volume mount instruction, f.e. `--volume /var/dockerdata/containersdata/redmine-mariadb:/bitnami/mariadb:Z`

**Comment by sameersbn** [comment]
**Update:**

RHEL treats OverlayFS as a preview filesystem. The following document https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/7.2_Release_Notes/technology-preview-file_systems.html lists the problems and possible workarounds for using OverlayFS with Docker on RHEL 7.2. 

We hope you find the information contained in this referenced document useful.
