### ISSUE TITLE
Error using width dockerToolbox

### ISSUE THREAD

**Issue by fallphenix** [bitnami/bitnami-docker-mariadb#116]
nami    ERROR Unable to start com.bitnami.mariadb: Warning: World-writable config file '/opt/bitnami/mariadb/conf/my.cnf' is ignored
Warning: World-writable config file '/opt/bitnami/mariadb/conf/my.cnf' is ignored

**Comment by silviofdez** [comment]
Hi, we cannot reproduce the issue. Could you please give us more details (SO, administator or not, ...)

**Comment by fallphenix** [comment]
I use dockertoolbox in windows. When i mount volume for mariadb data, i have the error below. But when i do not use local volume, all work fine.
`docker run -it -p 3306:3306 -v /d:/bitnami/mariadb --name mariadb -e ALLOW_EMPTY_PASSWORD=yes --network app-tier bitnami/mariadb`  not work

`docker run -it -p 3306:3306 -v /d:/bitnami/mariadb --name mariadb -e ALLOW_EMPTY_PASSWORD=yes --network app-tier bitnami/mariadb`  work

**Comment by fallphenix** [comment]
i have the same with official mariadb image

**Comment by fallphenix** [comment]
`                       ##         .
                  ## ## ##        ==
               ## ## ## ## ##    ===
           /"""""""""""""""""\___/ ===
      ~~~ {~~ ~~~~ ~~~ ~~~~ ~~~ ~ /  ===- ~~~
           \______ o           __/
             \    \         __/
              \____\_______/
 _                 _   ____     _            _
| |__   ___   ___ | |_|___ \ __| | ___   ___| | _____ _ __
| '_ \ / _ \ / _ \| __| __) / _` |/ _ \ / __| |/ / _ \ '__|
| |_) | (_) | (_) | |_ / __/ (_| | (_) | (__|   <  __/ |
|_.__/ \___/ \___/ \__|_____\__,_|\___/ \___|_|\_\___|_|
Boot2Docker version 17.03.0-ce, build HEAD : f11a204 - Thu Mar  2 00:14:47 UTC 2                                                                                                                017
Docker version 17.03.0-ce, build 3a232c8
docker@docker-dev:~$ docker run -it -p 3306:3306 -v /docker/:/bitnami/mariadb --
name mariadb -e ALLOW_EMPTY_PASSWORD=yes --network app-tier bitnami/mariadb
db/                   mariadb-persistence/  vhost-nginx/
help.txt              source/
docker@docker-dev:~$ docker run -it -p 3306:3306 -v /docker/:/bitnami/mariadb --
name mariadb -e ALLOW_EMPTY_PASSWORD=yes --network app-tier bitnami/mariadb
db/                   mariadb-persistence/  vhost-nginx/
help.txt              source/
docker@docker-dev:~$ docker run -it -p 3306:3306 -v /docker/db/mariadb:/bitnami/
mariadb --name mariadb -e ALLOW_EMPTY_PASSWORD=yes --network app-tier bitnami/ma
riadb

Welcome to the Bitnami mariadb container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-dock                                                                                                                er-mariadb
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-                                                                                                                mariadb/issues
Send us your feedback at containers@bitnami.com

WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety                                                                                                                 reasons, do not use this flag in a production environment.
nami    INFO  Initializing mariadb
mariadb INFO  ==> Configuring permissions...
mariadb INFO  ==> Validating inputs...
mariadb WARN  Allowing the "rootPassword" input to be empty
mariadb INFO  ==> Initializing database...
mariadb INFO  ==> Creating 'root' user with unrestricted access...
mariadb INFO  ==> Enabling remote connections...
mariadb INFO
mariadb INFO  ##################################################################                                                                                                                ######
mariadb INFO   Installation parameters for mariadb:
mariadb INFO     Root User: root
mariadb INFO     Root Password: Not set during installation
mariadb INFO   (Passwords are not shown for security reasons)
mariadb INFO  ##################################################################                                                                                                                ######
mariadb INFO
nami    INFO  mariadb successfully initialized
INFO  ==> Starting mariadb...
nami    ERROR Unable to start com.bitnami.mariadb: Warning: World-writable confi                                                                                                                g file '/opt/bitnami/mariadb/conf/my.cnf' is ignored
Wa`

**Comment by joseajp** [comment]
Hello @fallphenix, according to the [Docker documentation](https://docs.docker.com/engine/tutorials/dockervolumes/#mount-a-host-directory-as-a-data-volume)

> If you are using Docker Machine on Mac or Windows, your Docker Engine daemon has only limited access to your macOS or Windows filesystem. Docker Machine tries to auto-share your /Users (macOS) or C:\Users (Windows) directory

Basically, you will need to use as volume some location such as `C:\Users\YourUser\mariadb` and then mount using something like suggested in documentation:

```
docker run -v //c/Users/YourUser/mariadb:/bitnami/mariadb bitnami/mariadb:latest
```

**Comment by fallphenix** [comment]
i  already read this part of documentation. Both User's and other's directory not work. bitnami/mariadb or official  mariaDB image show the same error.
I finally turn on mysql which work well.

**Comment by amorel-ljsl** [comment]
This is due the fat that shared mounted volumes on Virtual Machine are *not compatible with permissions* and that MariaDB *requires configuration files to have restricted permissions* in order to be launched.

Bitnami images launch MariaDB in "safe mode". In normal mode, I don't think that should happen.

I could not yet come to a solution, one year later, and I think it is in Bitnami's hands.

**Comment by andresbono** [comment]
Hi @amorel-ljsl, thanks for suggesting the work-around of starting MariaDB in "normal" mode. However, I think it is not enough to solve the issue. Do you have a chance to try it? Let us know if it works for you!

Regards,
-Andrés.

**Comment by andresbono** [comment]
@amorel-ljsl, in theory, a possible solution can be changing the umask applied to regular files in the mounted volume of the Toolbox VM:

```
docker-machine ssh default "sudo umount -l DEVICE"
docker-machine ssh default "sudo mount -t vboxsf -o remount,defaults,iocharset=utf8,uid=$(id -u docker),gid=$(id -g docker),fmask=002 DEVICE MOUNTPOINT"
```

If you want, give us more details about your environment (mounted volumes, share folders between your host OS and VirtualBox, docker volumes that you are using,...).
