### ISSUE TITLE
Why is creating more than one DB not allowed?

### ISSUE THREAD

**Issue by dgonzalezruiz** [bitnami/bitnami-docker-mariadb#120]
**Description**

I am currently using this image together with mysql-client to automate the setup of three databases, which I want contained in a single database server.

**Steps to reproduce the issue:**

Launch your `docker-compose.yml` specifying several database names in the `MARIADB_DATABASE` env variable, separated by either commas or spaces

**Describe the results you received:**

It crashed the heck out of it, since it is not catching up to those commas, and just executing a
```
mysql -u'root' -h'mariadb' -e 'CREATE DATABASE $WHATEVER_I_PUT'
```

**Describe the results you expected:**

It should loop over the variable passed and take into account commas and spaces.
Have in mind that, per the [supported identifiers page from MariaDB](https://mariadb.com/kb/en/mariadb/identifier-names/), spaces are not allowed, so we could just take that as a multiple DB condition.

This would also make the HELM offering more interesting. Having to launch a pod for every database your service owns is something that people is not going to want to do.

**Comment by dgonzalezruiz** [comment]
Also, I have been checking the module code for `mysql-client` and we could go with something like:
```
 _.forEach($app.createDatabaseNames.split(' '), function(databaseName) {
        $app.info(`==> Creating database ${databaseName}...`);
        mysqlFunctions.createDatabase(databaseName, adminConnection);
        $app.info(`==> Granting access to ${$app.createDatabaseUser} to the database ${databaseName}...`);
        mysqlFunctions.grantPrivileges(databaseName, $app.createDatabaseUser, _.merge({
          databaseUserPassword: $app.createDatabasePassword
        }, adminConnection));
      });
```

After replacing `createDatabaseName` var name with `createDatabaseNames`.

**Comment by dgonzalezruiz** [comment]
By the moment I sorted this out by dirty-hacky patching on runtime the `main.js` file with this patch file:

```
36,37d35
<       $app.info(`==> Creating database ${$app.createDatabaseName}...`);
<       mysqlFunctions.createDatabase($app.createDatabaseName, adminConnection);
50,57c48,57
<
<       // Grant will create the username on-the-fly if the password is specified
<       $app.info(`==> Granting access to ${$app.createDatabaseUser} to the database ${$app.createDatabaseName}...`);
<       mysqlFunctions.grantPrivileges($app.createDatabaseName, $app.createDatabaseUser, _.merge({
<         databaseUserPassword: $app.createDatabasePassword,
<         privileges: $app.createDatabasePrivileges.split(/[;,]+/g).filter(p => !_.isEmpty(p))
<       }, adminConnection));
<
---
>       _.forEach($app.createDatabaseName.replace(/"/g, '').split(' '), function(databaseName) {
>         $app.info(`==> Creating database ${databaseName}...`);
>         mysqlFunctions.createDatabase(databaseName, adminConnection);
>         // Grant will create the username on-the-fly if the password is specified
>         $app.info(`==> Granting access to ${$app.createDatabaseUser} to the database ${databaseName}...`);
>         mysqlFunctions.grantPrivileges(databaseName, $app.createDatabaseUser, _.merge({
>           databaseUserPassword: $app.createDatabasePassword,
>           privileges: $app.createDatabasePrivileges.split(/[;,]+/g).filter(p => !_.isEmpty(p))
>         }, adminConnection));
>       });
```
Then execute `patch /root/.nami/components/com.bitnami.mysql-client/main.js < multipleDBs.patch`

Similar logic could be applied to MariaDB

**Comment by sameersbn** [comment]
@dgonzalezruiz I am in favour of being able to create multiple databases via the `MARIADB_DATABASE` env parameter. Since you have already done all the legwork to get this working, I suggest you submit a patch for the nami module.

**Comment by fredsted** [comment]
@dgonzalezruiz I'm a little confused about where to apply your patch, in this repository there's no `/root/.nami/components/com.bitnami.mysql-client/main.js`, so I'm a little confused. 

Any other ideas on how to create multiple databases would be _awesome_ (I'm using Helm/Helmfile by the way)

**Comment by sameersbn** [comment]
@juan131 do you think we can add this feature to the mariadb module?

**Comment by juan131** [comment]
Hi @sameersbn 

So.. We want the ability to create more than one database with its corresponding user/password via env. variables. Is it? 

Instead of using:

```
$ docker run --name mariadb \
  -e ALLOW_EMPTY_PASSWORD=yes \
  -e MARIADB_USER=my_user \
  -e MARIADB_PASSWORD=my_password \
  -e MARIADB_DATABASE=my_database \
  bitnami/mariadb:latest
```

Run sth like:

```
$ docker run --name mariadb \
  -e ALLOW_EMPTY_PASSWORD=yes \
  -e MARIADB_USER="my_first_user, my_second_user" \
  -e MARIADB_PASSWORD="my_first_pass, my_second_pass" \
  -e MARIADB_DATABASE="my_first_db, my_second_db" \
  bitnami/mariadb:latest
```

Am I right?

**Comment by sameersbn** [comment]
@juan131 IMO we should only support creation of multiple databases. If a user is created at launch, that user should have access to all the database created. so something like this


```
$ docker run --name mariadb \
  -e ALLOW_EMPTY_PASSWORD=yes \
  -e MARIADB_USER=my_user  \
  -e MARIADB_PASSWORD=my_password \
  -e MARIADB_DATABASE=my_first_db, my_nth_db \
  bitnami/mariadb:latest

```

**Comment by juan131** [comment]
Hi @sameersbn 

All right! I just found we have already an internal task to do so. Let me try to re-prioritise it! Thanks

**Comment by fredsted** [comment]
Hi guys, any updates? :-)

**Comment by tompizmor** [comment]
Hello @fredsted,

You can mount a custom `.sh` script creating all the databases that you want into the `/docker-entrypoint-initdb.d` folder. Check this [section](https://github.com/bitnami/bitnami-docker-mariadb#initializing-a-new-instance) in the README.

If you are using Helm, you can also do it. Check [this other section](https://github.com/helm/charts/tree/master/stable/mariadb#initialize-a-fresh-instance) in the MariaDB Helm chart readme.

**Comment by bittner** [comment]
We have solved this on Kubernetes (OpenShift, really) by mounting the following script into the `/docker-entrypoint-initdb.d/` folder ([as pointed out above](https://github.com/bitnami/bitnami-docker-mariadb/issues/120#issuecomment-410243733) by @tompizmor):

```bash
#!/bin/bash -e

. /opt/bitnami/scripts/libmariadb.sh

mysql_ensure_database_exists ${AUTHOR_DATABASE}
mysql_ensure_database_exists ${PUBLIC_DATABASE}

mysql_ensure_user_exists ${AUTHOR_USER} -p ${AUTHOR_PASSWORD}
mysql_ensure_user_exists ${PUBLIC_USER} -p ${PUBLIC_PASSWORD}

mysql_ensure_user_has_database_privileges ${AUTHOR_USER} ${AUTHOR_DATABASE}
mysql_ensure_user_has_database_privileges ${PUBLIC_USER} ${PUBLIC_DATABASE}
```

We're only setting the `MARIADB_ROOT_PASSWORD` value [when initializing the MariaDB instance](https://github.com/bitnami/bitnami-docker-mariadb#setting-the-root-password-on-first-run), ignoring the other environment variables. The above scripts creates two custom databases and related users subsequently, leveraging the Bash library functions shipped with the Bitnami image.

**Comment by migruiz4** [comment]
Hi @bittner,

Thank you for sharing your solution!
