### ISSUE TITLE
Show error " Error executing 'postInstallation': ENOENT: no such file or directory, chown '/opt/bitnami/mariadb/data/test/db.opt'"

### ISSUE THREAD

**Issue by ringxu** [bitnami/bitnami-docker-mariadb#126]
**Steps to reproduce the issue:**

1. [First Step]
download docker-compose

2. [Second Step]
docker-compose up

3. [and so on...]

**Describe the results you received:**

mariadb_1  | nami    INFO  Initializing mariadb
mariadb_1  | mariadb INFO  ==> Cleaning data dir...
mariadb_1  | mariadb INFO  ==> Configuring permissions...
mariadb_1  | Error executing 'postInstallation': ENOENT: no such file or directory, chown '/opt/bitnami/mariadb/data/test/db.opt'
mariadb_mariadb_1 exited with code 1

**Comment by ringxu** [comment]
And it show same error on testlink docker

**Comment by ringxu** [comment]
It's ok after I rebuild your docker on my host. I don't know why.

**Comment by sameersbn** [comment]
thanks for confirming. probably a data corruption issue.
please re-open if the issue reappears.
