### ISSUE TITLE
Error executing 'postInstallation': EPERM: operation not permitted

### ISSUE THREAD

**Issue by Scotty42** [bitnami/bitnami-docker-mariadb#128]
**Description**

Mounted a NFS volume from a freenas server for persistance. NFS server maps all to user mysql. 
NFS volume is mounted by a cloud-config yml file on a rancher OS instance. This container is also configured by a cloud-config yml file and declares a volume mapping for /bitnami to /mnt/<nfs_share>. On first start of this container, directories and files are created fine within the volume. But later during startup a chown call is made. That one fails with error: Error executing 'postInstallation': EPERM: operation not permitted, chown '/bitnami/mariadb/data'. 

**Steps to reproduce the issue:**

1. Create NFS server share and user mysql, set mapall to mysql
2. Mount NFS share on docker host (in my case rancher OS instance) as /mnt/db/mariadb
3. Declare volume mapping for persistance e.g. - /mnt/db/mariadb:/bitnami
4. Start container. Files are created on first run with uid:gid 1102:1102 (mapped account of NFS server)
5. Have a look at error logs and find the aforementioned error. 

**Describe the results you received:**

Server is not starting up and hangs with trying to chown something. 
Error executing 'postInstallation': EPERM: operation not permitted, chown '/bitnami/mariadb/data'.

**Describe the results you expected:**

Well, startup. Files are already created. Why chowning again by startup script and to which account?

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
Docker version 17.03.1-ce, build c6d412e
```

- Output of `docker info`:

```
Containers: 6
 Running: 6
 Paused: 0
 Stopped: 0
Images: 11
Server Version: 17.03.1-ce
Storage Driver: overlay
 Backing Filesystem: extfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.34-rancher
Operating System: RancherOS v1.0.3
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.955 GiB
Name: rancher
ID: S27D:NTUU:HVHD:MFRP:JWSM:IMYF:JVLW:K4RW:JEUB:Y53Q:T7VJ:FQZY
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by Scotty42** [comment]
to be sure it is not just an OS issue, I installed a plain Debian 9, installed latest docker-engine and mounted NFS share in debian. 

`sudo docker run -e ALLOW_EMPTY_PASSWORD=yes -v /mnt/db/mariadb:/bitnami bitnami/mysql:latest`

leads to exactly the same error:

`Error executing 'postInstallation': EPERM: operation not permitted, chown '/bitnami/mysql/data'`

**Comment by prydonius** [comment]
> Well, startup. Files are already created. Why chowning again by startup script and to which account?

The chown is to the user inside the container that will run the mysql daemon, however this obviously doesn't work on NFS mounts. A possible solution is to not fail initialisation if the chown fails.

**Comment by sameersbn** [comment]
> A possible solution is to not fail initialisation if the chown fails.

In case of mysql/mariadb the daemon will error out if the datadir does not have the right permissions. i.e. not owned my the `mysql` user. Probably the solution is to use the same uid/gid on the NFS server as the container mysql user.

@Scotty42 can you retry by specifying `no_root_squash` parameter for  the NFS share? This is an insecure choice, but it would be worth noting if it works. 

As an aside, I am not an expert but using a NFS share for the mysql datadir seems like a poor design choice.

**Comment by Scotty42** [comment]
@sameersbn matching uid was a really helpful hint. I couldn't match gid but wasn't needed in the end, so don't care. 
Additionally I removed mapall setting for user mysql on server side and set maproot_user to root. 

On or both of the settings in conjungtion did the trick. mariadb startup finally succeeds.
