### ISSUE TITLE
MariaDB problem with install "no such file or directory, chown '/opt/bitnami/mariadb/data/test/db.opt'"

### ISSUE THREAD

**Issue by alexmartino** [bitnami/bitnami-docker-mariadb#129]
**Description**

**Steps to reproduce the issue:**

1. Run docker-compose (docker-compose up) with follow docker-compose.yml file:

version: '2'

services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    ports:
      - '13306:3306'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=my_user
      - MARIADB_PASSWORD=my_password
      - MARIADB_DATABASE=my_database

**Describe the results you received:**

_I get this log informtions:_

Starting crm_mariadb_1
Attaching to crm_mariadb_1
mariadb_1  |
mariadb_1  | Welcome to the Bitnami mariadb container
mariadb_1  | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb
mariadb_1  | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb/issues
mariadb_1  | Send us your feedback at containers@bitnami.com
mariadb_1  |
mariadb_1  | WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
mariadb_1  | nami    INFO  Initializing mariadb
mariadb_1  | mariadb INFO  ==> Cleaning data dir...
mariadb_1  | mariadb INFO  ==> Configuring permissions...
mariadb_1  | Error executing 'postInstallation': ENOENT: no such file or directory, chown '/opt/bitnami/mariadb/data/test/db.opt'
crm_mariadb_1 exited with code 1

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:20:36 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:21:56 2017
 OS/Arch:      linux/amd64
 Experimental: true

- Output of `docker info`:

Containers: 36
 Running: 13
 Paused: 0
 Stopped: 23
Images: 422
Server Version: 17.06.0-ce
Storage Driver: overlay
 Backing Filesystem: xfs
 Supports d_type: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-514.26.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 24
Total Memory: 125.7GiB
Name: dockerserver.trscarsharing.it
ID: PRHB:DK2I:AB4P:7CF6:BURK:Q2UH:6OT2:QHBY:NS5L:IZSL:PAIJ:VCWZ
Docker Root Dir: /opt/docker-data
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 msdockerhub:5000
 127.0.0.0/8
Live Restore Enabled: false

WARNING: overlay: the backing xfs filesystem is formatted without d_type support, which leads to incorrect behavior.
         Reformat the filesystem with ftype=1 to enable d_type support.
         Running without d_type support will not be supported in future releases.

- Output of `docker-compose version` (if applicable):

docker-compose version 1.11.2, build dfed245
docker-py version: 2.1.0
CPython version: 2.7.13
OpenSSL version: OpenSSL 1.0.1t  3 May 2016

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by jotamartos** [comment]
Hi @alexmartino,

I tried to reproduce the issue and I could not do it as the MariaDB container worked fine for me. It seems that this issue has been already reported in the Moby Github repository

https://github.com/moby/moby/issues/29873

Have you tried to launch the same docker-compose file in a different file system?

Regards,
Jota

**Comment by alexmartino** [comment]
Hi Juan,  
I tried in Windows and in CentOs 7 but with default  storage driver and all work fine.

I think the problem is in storage driver overlay.

Regards

Alessandro

Da: Juan José Martos
Inviato: venerdì 18 agosto 2017 17:24
A: bitnami/bitnami-docker-mariadb
Cc: alexmartino; Mention
Oggetto: Re: [bitnami/bitnami-docker-mariadb] MariaDB problem with install "nosuch file or directory, chown '/opt/bitnami/mariadb/data/test/db.opt'" (#129)

Hi @alexmartino,
I tried to reproduce the issue and I could not do it as the MariaDB container worked fine for me. It seems that this issue has been already reported in the Moby Github repository
moby/moby#29873
Have you tried to launch the same docker-compose file in a different file system?
Regards,
Jota

**Comment by sameersbn** [comment]
@alexmartino Did you notice the following your `docker version` output,

```
WARNING: overlay: the backing xfs filesystem is formatted without d_type support, which leads to incorrect behavior.
Reformat the filesystem with ftype=1 to enable d_type support.
Running without d_type support will not be supported in future releases.
```

Have you tried the suggestion? 

Additionally you may want to look for possibles workarounds in https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/7.2_Release_Notes/technology-preview-file_systems.html
