### ISSUE TITLE
Debian stretch

### ISSUE THREAD

**Issue by matiux** [bitnami/bitnami-docker-mariadb#131]
Hi,
is there a way to use debian 9 (stretch)?
I need to install mycli command, but there isn't in jessie

Thanks

**Comment by sameersbn** [comment]
@matiux at the moment we do not have packages for debian stretch. However, you should not have to install this package in the mariadb container. You can install `mycli` on your host or you can build a docker image with `mycli` like so:

```dockerfile
FROM bitnami/minideb:stretch
ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8
RUN echo 'Acquire::HTTP::Proxy "http://proxy.damagehead.com:3142";' >> /etc/apt/apt.conf.d/01proxy
RUN install_packages mycli
ENTRYPOINT ["mycli"]
```

Build the docker image with

```bash
docker build -t mycli .
```

Start a test mariadb instance

```bash
docker run  -it --rm --name mariadb bitnami/mariadb:latest
```

Start the `mycli` container

```bash
docker run -it --link mariadb:mariadb mycli -h mariadb
```

**Comment by sameersbn** [comment]
tip: you could also create an shell alias with `alias mycli='docker run -it --rm mycli'` and invoke the command with just `mycli` to connect to any mariadb server that is addressable from the container

**Comment by sameersbn** [comment]
@matiux was the information useful? can we close this request?
