### ISSUE TITLE
When deploying the helm chart stable/wordpress onto a cluster running as defined in Kelsey Hightowers "Kubernetes: the hard way", environment variables appear to be undefined.

### ISSUE THREAD

**Issue by cyb3r** [bitnami/bitnami-docker-mariadb#132]
**Description**

```
Welcome to the Bitnami mariadb container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb/issues
Send us your feedback at containers@bitnami.com

ERROR ==> The MARIADB_ROOT_PASSWORD environment variable is empty or not set. Set the environment variable ALLOW_EMPTY_PASSWORD=yes to allow the container to be started with blank passwords. This is recommended only for development.
```

**Steps to reproduce the issue:**

1. Provision cluster as described. Notably, it uses CRIO and not Docker as it's container runtime.
2. Manually create mariadb resources. Same result
3. init helm
4. helm install --name="boop" stable/wordpress --set="persistence.enabled=false,mariadb.persistence.enabled=false"
**Describe the results you received:**

See above, root password is undefined.

**Describe the results you expected:**

Container bootstrap, successful wordpress install.

**Additional information you deem important (e.g. issue happens only occasionally):**

Mariadb library version works fine; seems to be something about the bitnami images.

**Version**

- Output of `docker version`:

```
$ crio --version
crio version 1.0.0-alpha.0
```

- Output of `docker info`:

```
Uhh it's a different runtime.
```

- Output of `docker-compose version` (if applicable):

```
Kubernetes v 1.7.5
```

cc @andrewhowdencom

**Comment by cyb3r** [comment]
Oh same was also true of the wordpress image, though I didn't look hugely into that one.

**Comment by sebgoa** [comment]
@cyb3r any chance you could try to run a standard Pod that defines some env var and see if they get set properly.

It seems like a CRI-O issue to me

**Comment by runcom** [comment]
It sounds like a cri-o issue to me as well. One thing worth noticing is that we fixed many bugs from alpha to v1 so may be already fixed. I'll try to set this up and reproduce or if someone can upgrade cri-o to v1 that would help as well

**Comment by andrewhowdencom** [comment]
I was there for this one -- we're not in a super good position to repro it; we were following the tutorial to get the cluster up and running over the course of a free day and we don't have so many free days ;) 

If memory serves, it was common across bitnami containers, but not the core (as mariadb indicates)

**Comment by sebgoa** [comment]
@andrewhowdencom and did you try to set env variables in Pod using other images ? Did that work ?

we need to know if it was a cri-o issue, or a bitnami container issue

**Comment by andrewhowdencom** [comment]
(again if memory serves) the MariaDB library image accepted environment variables to initialise the correct user, etc. It's been some time though, and unfortunately I don't have it in my radar to check this again. Additionally, I can't find an easy way to repro the CRI-O tooling; I had a short play now but can't afford to invest lots of time into this. 

Sorry man. I might suggest following the tutorial and giving it a shot as described; it provides the necessary tooling to debug, if nothing else.
