### ISSUE TITLE
Error executing 'postInstallation'

### ISSUE THREAD

**Issue by l50** [bitnami/bitnami-docker-mariadb#134]
The newest version of the mariadb container introduces this issue for me: 

```
Error executing 'postInstallation': EPERM: operation not permitted, utime '/bitnami/mariadb/.restored'
```

When I roll back to 10.1.28-r1, the issue is no longer present.

The docker-compose file that I'm using can be found [here](https://github.com/l50/techvomit/blob/master/docker-compose.yml).

**Version**

- Output of `docker version`:

```
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:42:18 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:56 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

- Output of `docker info`:

```
Containers: 4
 Running: 4
 Paused: 0
 Stopped: 0
Images: 5
Server Version: 17.09.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-36-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 990.7MiB
Name: ip-172-31-1-1
ID: ZOSE:KEA7:YGRZ:PFAE:RK57:CO4D:TF7T:SLW7:R3QG:GFOU:OB7W:CYNP
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Live Restore Enabled: false
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.16.1, build 6d1ac219
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
This is running on an Ubuntu 16.04 instance on AWS.

This is the first issue I've run into with this project; thanks for all the great work on it so far!

**Comment by sameersbn** [comment]
@l50 With release `10.1.28-r2` we have adopted a non-root approach to launch the container. The container is now launched as user `1001`. Launching the containers as non-root improves the security of the container and also makes it compatible with the default openshift security policies.

The reason you are seeing the issue is because you are upgrading from a previous release, which used to be launched as the `root` user and thus the data volume is accessible only by the root user.

To workaround this issue, please execute the following command before upgrading to the latest 10.1.28-r2 release.

```bash
docker run -it --rm -v $PWD/data/mariadb:/bitnami busybox chmod -R g+rwX /bitnami
```

Do let us know if this resolves the issue. Thanks and best regards

/cc @tompizmor

**Comment by roozeec** [comment]
Hi
I had the same error and I applied your workaround and it is now ok.
Thanks

**Comment by l50** [comment]
The workaround wasn't working for me, but doing a ```chown -R 1001:1001 <path-to-mariadb-volume>``` did the trick.

**Comment by sameersbn** [comment]
> The workaround wasn't working for me, but doing a chown -R 1001:1001 <path-to-mariadb-volume> did the trick.

@l50 Thanks for the confirmation. Clearly a `chmod` is not sufficient to fix the issue, perhaps we should do a `chown` /cc @tompizmor

**Comment by l50** [comment]
I concur.

**Comment by tompizmor** [comment]
The `chmod` command was sufficient in our test because the group of the volume was `root` and the user `1001` belongs to the `root` group. 
@l50 is it possible that you have changed the permission of the volume before?

**Comment by l50** [comment]
I do not believe that I did, but my memory is quite poor (to say the least).

**Comment by tompizmor** [comment]
We have just released MariaDB _10.1.28-r3_ addressing https://github.com/bitnami/bitnami-docker-mariadb/issues/135 which was a similar permission issue.
