### ISSUE TITLE
Running .sql dump files found in the /docker-entrypoint-initdb.d/

### ISSUE THREAD

**Issue by laukaichung** [bitnami/bitnami-docker-mariadb#137]
I'm looking for a way to load some data into the database when the master/slave containers are initialized.
Will you support restoring data via mounting dump files to `docker-entrypoint-initdb.d/` like the official repository?

**Comment by juan131** [comment]
Hi @stonecold123 

At this moment you can create a new database during initialisation, see:

https://github.com/bitnami/bitnami-docker-mariadb#creating-a-database-user-on-first-run

However, we're not supporting to also populate that database on the first run. @tompizmor @sameersbn @prydonius what do you think about this feature?

**Comment by sameersbn** [comment]
This is a useful feature to have and can be implemented in the [run.sh](https://github.com/bitnami/bitnami-docker-mariadb/blob/master/10.1/rootfs/run.sh) script without having to change the nami module. At the first launch we would have to start the server (localhost only), run the custom scripts, stop the server and launch server again allowing outside connections.

**Comment by JayWood** [comment]
Want to second this as a good feature to have. Right now your image is the go-to for us Windows folks which require mariadb since the official mariadb image has issues mounting volumes on windows devices. I believe this is the last piece of the puzzle for me, until then I'm probably stuck with `mysql:8` as an alternative.

**Comment by pasikarkkainen** [comment]
Yes please, docker-entrypoint-initdb.d/ like functionality to easily run scripts would be very welcome.. handy to set up more complex user/access permissions and whatnot.

**Comment by marcosbc** [comment]
@muhaimincs We're already working on adding support for this, it shouldn't take more than a week or two before making it public. We'll let you know once this is done.

**Comment by muhaimincs** [comment]
> When the container is executed for the first time, it will execute the files with extensions .sh, .sql and .sql.gz located at /docker-entrypoint-initdb.d.

How exactly sql been executed?

**Comment by tompizmor** [comment]
Yoy can see the exact logic here:

https://github.com/bitnami/bitnami-docker-mariadb/blob/master/10.2/debian-9/rootfs/run.sh#L53-L66
