### ISSUE TITLE
Out of memory when setting up a clean SLAVE in replication mode.

### ISSUE THREAD

**Issue by seli** [bitnami/bitnami-docker-mariadb#139]
**Description**

We were using a master / slave docker setup of maria db which works fine. Both master and slave have 3GB of memory available.
When restoring an existing database of 130 GB into the master, the slave is also filled correctly when running the master and the slave from scratch in the beginning.
The issue occurred when we started our docker stack with only a master and no slave. Then restored the DB of 130 GB and then restarted a stack with a slave configured.
We did this to found out if we can easily create an extra slave in an existing environment. But apparently this isn't working because we run out of memory. Even if we increase it to 16GB of memory.

**Steps to reproduce the issue:**

1. Deploy a docker stack with a master
2. Restore a database of 130 GB
3. Stop the docker stack 
4. Deploy a docker stack with the master (same volume) and a slave (clean volume)

**Describe the results you received:**

After a while we see that the docker service of the slave is going out of memory.
When looking at the processes in the container (ps -efww) we noticed that it was performing a mysqldump with some strange parameter -px xxx and without the usage of an output file.

**Describe the results you expected:**

A slave to be filled from scratch from the master

**Additional information you deem important (e.g. issue happens only occasionally):**

I don't expect more memory to be needed when starting from scratch than when starting clean

**Version**

- Output of `docker version`:

```
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:42:18 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:56 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

- Output of `docker info`:

```
Containers: 32
 Running: 32
 Paused: 0
 Stopped: 0
Images: 35
Server Version: 17.09.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: swq9m7wyge20r7yu5ezxfywr9
 Is Manager: true
 ClusterID: m1f4z3fu0maf7ukb8t6mblzvt
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: 192.168.119.82
 Manager Addresses:
  192.168.119.82:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-98-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.67GiB
Name: EDD-01
ID: JV2H:JNVU:DOH5:HH7U:KIWL:ZHND:X4FG:INSG:EUTA:G7ZZ:R4X5:O5EY
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

- Output of `docker-compose version` (if applicable):

(not real used)
```
docker-py version: 2.5.1
CPython version: 2.7.13
OpenSSL version: OpenSSL 1.0.1t  3 May 2016
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

Docker om a linux vm in vsphere.

**Comment by sameersbn** [comment]
@seli We've noticed an issue with the replication logic on the slave and i've submitted a fix for it (internally). This issue should be resolved in the upcoming release

**Comment by sameersbn** [comment]
@seli release 10.1.30-r1 is expected to fix this issue. 

In earlier released the slaves your restore a dump of the data from the master node before coming online. In your use-case this meant that a db dump of ~130 GB was being created in RAM resulting in excessive memory usage.

In the new release we have disabled this db dump/restore operation and instead expect the slaves to replicate the data completely on their own when they are started (streaming replication). However, please note that it would take a while for the slave to sync with the state of the master node after it comes online, especially when the amount of data to be copied is very large.

Do let us know what you think.
