### ISSUE TITLE
Import all sql files from a folder

### ISSUE THREAD

**Issue by rapsli** [bitnami/bitnami-docker-mariadb#144]
I have figured out a way to import single sql files into the db:

volumes:
      - ./mysql:/bitnami
      - ./backup/mytable.sql:/docker-entrypoint-initdb.d/mytable.sql

What I though like to accomplish is to import all sql files in the folder backup. Yes I could list them all manually, but it would be way more convinient the other way around. Is there a way to do this?

**Comment by ofanged1** [comment]
I added a Kubernetes Job that waits for mysql readiness and then imports them. This also ensures the initdb files are not still mounted in the container after import

**Comment by rapsli** [comment]
I'm running it with docker-composer. I guess I could merge the sql files on export into one file and solve it like this.

**Comment by andresbono** [comment]
Hi @rapsli, we already have another issue opened related to importing sql files. It sounds like an interesting feature that we are already evaluating if we can include it.

Closing this issue in favor of #137. Please, feel free to share your thoughts in that one if you want!
