### ISSUE TITLE
Cluster cannot start

### ISSUE THREAD

**Issue by m1911** [bitnami/bitnami-docker-mariadb#150]
**Description**

**Steps to reproduce the issue:**

Unable to start cluster using docker-compose-f test.yml scale mariadb-master=1 mariadb-slave=2 command

**Describe the results you received:**

Creating root_mariadb-master_1 ... error

ERROR: for root_mariadb-master_1  Cannot start service mariadb-master: b'network root_default not found'
ERROR: Cannot start service mariadb-master: b'network root_default not found'

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
[root@localhost ~]# docker version
Client:
 Version:      18.05.0-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   f150324
 Built:        Wed May  9 22:14:54 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.05.0-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   f150324
  Built:        Wed May  9 22:18:36 2018
  OS/Arch:      linux/amd64
  Experimental: false

```

- Output of `docker info`:

```
[root@localhost ~]# docker info
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 1
Server Version: 18.05.0-ce
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-862.3.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.779GiB
Name: localhost.localdomain
ID: OBHT:RBR5:VMCV:JT2H:A4QE:Q4SD:THU3:XCSP:L63T:BVO2:DXWL:N4MT
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Registry Mirrors:
 http://4124b417.m.daocloud.io/
Live Restore Enabled: false

```

- Output of `docker-compose version` (if applicable):

```
[root@localhost ~]# docker-compose version
docker-compose version 1.21.2, build a133471
docker-py version: 3.3.0
CPython version: 3.6.5
OpenSSL version: OpenSSL 1.0.1t  3 May 2016

```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
VMware

**Comment by m1911** [comment]
My Profile information：
version: '2'
services:
  mariadb-master:
    image: 'bitnami/mariadb:10.2.16'
    ports:
      - '3306'
    volumes:
      - /data:/bitnami
      - /data/my.cnf:/opt/bitnami/mariadb/conf/my.cnf:ro
    environment:
      - MARIADB_REPLICATION_MODE=master
      - MARIADB_REPLICATION_USER=repl_user
      - MARIADB_REPLICATION_PASSWORD=123456
      - MARIADB_ROOT_PASSWORD=123456
  mariadb-slave:
    image: 'bitnami/mariadb:10.2.16'
    ports:
      - '3306'
    depends_on:
      - mariadb-master
    environment:
      - MARIADB_REPLICATION_MODE=slave
      - MARIADB_REPLICATION_USER=repl_user
      - MARIADB_REPLICATION_PASSWORD=123456
      - MARIADB_MASTER_HOST=mariadb-master
      - MARIADB_MASTER_PORT_NUMBER=3306
      - MARIADB_MASTER_ROOT_PASSWORD=123456

**Comment by tompizmor** [comment]
Hello @m1911,

I think your command is not correct. Can you try with this one?

```
docker-compose -f test.yml up --scale mariadb-master=1 --scale mariadb-slave=2
```

**Comment by m1911** [comment]
@tompizmor 
Yes, it's ready to start.
My orders are to refer to your readme.
I hope you can update them.
