### ISSUE TITLE
Scripts in /docker-entrypoint-initdb.d/ are not executed at container start

### ISSUE THREAD

**Issue by phermann1988** [bitnami/bitnami-docker-mariadb#156]
my problem is that the copied .sql files are not executed after the copy to /docker-entrypoint-initdb.d/ and first start of the container (but the files are in the FS of the container). With "FROM mariadb:10.3.." the scripts are working so there are not the reason. i tried to copy a simple .sh but it won't executed either.... :-/

https://github.com/bitnami/bitnami-docker-mariadb#creating-a-database-user-on-first-run

Dockerfile

```
FROM bitnami/mariadb:latest
ENV ALLOW_EMPTY_PASSWORD=yes
ENV MARIADB_USER=admin
ENV MARIADB_PASSWORD=test
ENV MARIADB_DATABASE=test_db
COPY *.sql /docker-entrypoint-initdb.d/
```

docker build
```
...
Step 7/7 : COPY *.sql /docker-entrypoint-initdb.d/
---> Using cache
---> f902b1ce02d9
Successfully built f902b1ce02d9
...

```

docker run
```
....

mariadb INFO
mariadb INFO ########################################################################
mariadb INFO Installation parameters for mariadb:
mariadb INFO Root User: root
mariadb INFO Root Password: Not set during installation
mariadb INFO Database: test_db
mariadb INFO Username: admin
mariadb INFO Password: **********
....
```

inside the container
```
I have no name!@0cdd5f2118b9:/docker-entrypoint-initdb.d$ ls
V1.0__Initial_Script.sql V1.1__insert_eventdefs.sql
```

**Comment by tompizmor** [comment]
I tried and it worked fine for me.
Did you pull the latest bitnami/mariadb image? Maybe you have an old version cached.
Run `docker pull bitnami/mariadb:latest` to get the latest image.

I used this Dockerfile

```
FROM bitnami/mariadb:latest

ENV ALLOW_EMPTY_PASSWORD=yes
ENV MARIADB_USER=admin
ENV MARIADB_PASSWORD=test
ENV MARIADB_DATABASE=test_db

COPY *.sh /docker-entrypoint-initdb.d/
COPY *.sql /docker-entrypoint-initdb.d/
```

This test.sh:

```
#!/bin/bash

echo "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
echo "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
echo "                          TEST                                  "
echo "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
echo "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
```

And this test.sql file:

```
--
-- Database: `samplevideo_db`
--

-- --------------------------------------------------------

--
-- Table structure for table `user_details`
--

CREATE TABLE IF NOT EXISTS `user_details` (
  `user_id` int(11) NOT NULL AUTO_INCREMENT,
  `username` varchar(255) DEFAULT NULL,
  `first_name` varchar(50) DEFAULT NULL,
  `last_name` varchar(50) DEFAULT NULL,
  `gender` varchar(10) DEFAULT NULL,
  `password` varchar(50) DEFAULT NULL,
  `status` tinyint(10) DEFAULT NULL,
  PRIMARY KEY (`user_id`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=10001 ;

--
-- Dumping data for table `user_details`
--

INSERT INTO `user_details` (`user_id`, `username`, `first_name`, `last_name`, `gender`, `password`, `status`) VALUES
(1, 'rogers63', 'david', 'john', 'Female', 'e6a33eee180b07e563d74fee8c2c66b8', 1),
(2, 'mike28', 'rogers', 'paul', 'Male', '2e7dc6b8a1598f4f75c3eaa47958ee2f', 1),
(3, 'rivera92', 'david', 'john', 'Male', '1c3a8e03f448d211904161a6f5849b68', 1),
(4, 'ross95', 'maria', 'sanders', 'Male', '62f0a68a4179c5cdd997189760cbcf18', 1),
(5, 'paul85', 'morris', 'miller', 'Female', '61bd060b07bddfecccea56a82b850ecf', 1),
(6, 'smith34', 'daniel', 'michael', 'Female', '7055b3d9f5cb2829c26cd7e0e601cde5', 1),
(7, 'james84', 'sanders', 'paul', 'Female', 'b7f72d6eb92b45458020748c8d1a3573', 1),
(8, 'daniel53', 'mark', 'mike', 'Male', '299cbf7171ad1b2967408ed200b4e26c', 1),
(9, 'brooks80', 'morgan', 'maria', 'Female', 'aa736a35dc15934d67c0a999dccff8f6', 1),
(10, 'morgan65', 'paul', 'miller', 'Female', 'a28dca31f5aa5792e1cefd1dfd098569', 1);
```


And this is the output of the docker run command:

```
Welcome to the Bitnami mariadb container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb/issues

WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
nami    INFO  Initializing mariadb
mariadb INFO  ==> Cleaning data dir...
mariadb INFO  ==> Configuring permissions...
mariadb INFO  ==> Validating inputs...
mariadb WARN  Allowing the "rootPassword" input to be empty
mariadb INFO  ==> Initializing database...
mariadb INFO  ==> Creating 'root' user with unrestricted access...
mariadb INFO  ==> Creating database test_db...
mariadb INFO  ==> Creating user admin...
mariadb INFO  ==> Granting access to admin to the database test_db...
mariadb INFO
mariadb INFO  ########################################################################
mariadb INFO   Installation parameters for mariadb:
mariadb INFO     Root User: root
mariadb INFO     Root Password: Not set during installation
mariadb INFO     Database: test_db
mariadb INFO     Username: admin
mariadb INFO     Password: **********
mariadb INFO   (Passwords are not shown for security reasons)
mariadb INFO  ########################################################################
mariadb INFO
nami    INFO  mariadb successfully initialized
INFO  ==> Starting mariadb...
==> Loading user files from /docker-entrypoint-initdb.d
INFO  ==> MariaDB init process in progress...
180914 08:10:07 mysqld_safe Logging to '/opt/bitnami/mariadb/logs/mysqld.log'.
180914 08:10:07 mysqld_safe Starting mysqld daemon with databases from /opt/bitnami/mariadb/data
Executing /docker-entrypoint-initdb.d/test.sh
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                          TEST
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Executing /docker-entrypoint-initdb.d/test.sql

INFO  ==> Starting mysqld_safe.....
```

**Comment by phermann1988** [comment]
Thank you!! I tried your example (on the same machine as my given example above  and i didnt work, well it did work but it just skipped the whole "==> Loading user files from /docker-entrypoint-initdb.d" part).  Then I tried it on another machine and it worked - with your .sh and .sql samples as well as my DB schemas. so it's sth on the machine/configuration not on the Dockerfile or the db init scripts..

**Comment by tompizmor** [comment]
I would bet that you are using and outdated version of the `bitnami/mariadb` container that didn't have the custom scripts functionality yet.

Did you run `docker pull bitnami/mariadb:latest`? If your image is updated you will see something like this:

```
latest: Pulling from bitnami/mariadb
Digest: sha256:23aa1a4c44cd963b9a3a41850616dfc44a4ae4766a3dcaab19f1375cc715b257
Status: Image is up to date for bitnami/mariadb:latest
```

**Comment by phermann1988** [comment]
yes that was the problem, thank you!! :-)

Digest: sha256:23aa1a4c44cd963b9a3a41850616dfc44a4ae4766a3dcaab19f1375cc715b257
Status: Downloaded newer image for bitnami/mariadb:latest

...
180917 09:51:52 mysqld_safe Starting mysqld daemon with databases from /opt/bitnami/mariadb/data
Executing /docker-entrypoint-initdb.d/helloworld.sh
HELLLOOO
...

**Comment by tompizmor** [comment]
Glad to help! 😄

**Comment by gauravmittal80** [comment]
Hi,

I am getting a similar problem where I am doing a helm upgrade to upgrade the mariadb pod and the setup.sql file under docker-entrypoint-initdb.d is not getting called.

But when i do a install it works.

Kindly help.

Gaurav

**Comment by tompizmor** [comment]
Hi @gauravmittal80, can you please reply to the following questions?

- Is MariaDB you main chart or a sub chart?
- Can you please let me know the command that you are using?
- How are you specifying the init scripts? Directly in your values.yaml file or using an external config map?

**Comment by AndresPineros** [comment]
@gauravmittal80 I think the problem happens because the script only runs ONCE. If you already created the Mysql and it already has a volume, the logic of the docker-entrypoint of the container will avoid executing the scripts again.

I'm not sure why the container was created this way... Maybe because Mysql commands aren't idempotent. Idk. You can test this behavior on your local machine without Kubernetes.

**Comment by crwgregory** [comment]
Was running into this issue w/ a mysql container and Google brought me here. Issue for me was what @AndresPineros pointed out.

```
docker-compose build --no-cache db
docker-compose run db
```
Fixed the issue for me.

**Comment by andresbono** [comment]
Thanks for providing a way to fix your issue.

**Comment by natanlao** [comment]
Also found this from Google, but my solution was slightly different:

    $ docker-compose up --renew-anon-volumes

**Comment by andresbono** [comment]
Thanks for sharing it with us, @natanlao.

**Comment by himat** [comment]
Running `docker-compose up --renew-anon-volumes` deleted all the local database data I had in my volume.
Is there a way to get the same effect of causing the initialization scripts to run but keeping the existing data there?

**Comment by andresbono** [comment]
Hi @himat, if you look at the function that handles the custom init scripts you can see a flag file:

https://github.com/bitnami/bitnami-docker-mariadb/blob/c65b690813f20496e13a33549669c19e0dfb8dc1/10.3/debian-10/rootfs/opt/bitnami/scripts/libmariadb.sh#L333-L334

If you remove `/bitnami/mariadb/.user_scripts_initialized`, you may achieve what you are describing. However, we haven't tested it.
