### ISSUE TITLE
passwordCharacterEncoding error

### ISSUE THREAD

**Issue by phermann1988** [bitnami/bitnami-docker-mariadb#158]
the pw from my java app contains a $. when i try to connect to a bitnami maria db container i get a stacktrace of connectiion errors with the following error:

Caused by: java.sql.SQLException: Access denied for user 'admin'@'172.17.0.1' (using password: YES)
Current charset is UTF-8. If password has been set using other charset, consider using option 'passwordCharacterEncoding' 

if I change the pw to "with no $" or other special chars the JDBC connection works fine. 
the strange thing is my app is UTF-8 and the MariaDB in the container is, too.

MariaDB [(none)]> \s
--------------
mysql  Ver 15.1 Distrib 10.1.36-MariaDB, for Linux (x86_64) using readline 5.1

Connection id:          14
Current database:
Current user:           admin@localhost
SSL:                    Not in use
Current pager:          stdout
Using outfile:          ''
Using delimiter:        ;
Server:                 MariaDB
Server version:         10.1.36-MariaDB Source distribution
Protocol version:       10
Connection:             Localhost via UNIX socket
Server characterset:    utf8
Db     characterset:    utf8
Client characterset:    utf8
Conn.  characterset:    utf8
UNIX socket:            /opt/bitnami/mariadb/tmp/mysql.sock
Uptime:                 49 min 30 sec

**Comment by andresbono** [comment]
Hi @phermann1988, is your issue related to the MariaDB container? We have done the following test:

1. Define a simple MariaDB docker-compose with a password containing `$` symbols:

```
version: '2'

services:
  mariadb:
    image: 'bitnami/mariadb:10.1'
    environment:
      - 'MARIADB_ROOT_PASSWORD=pa$$$$word123'
```

Note that two dollar symbols `$$` to specify a literal dollar sign ([reference](https://docs.docker.com/compose/compose-file/#variable-substitution)).

2. Start the container:
```
docker-compose up
```

3. Check if there is access to MariaDB using the password defined: 
```
docker-compose exec mariadb mysql -uroot -p'pa$$word123' -e 'SHOW DATABASES;'

+--------------------+
| Database           |
+--------------------+
| information_schema |
| mysql              |
| performance_schema |
+--------------------+
```

Can be your issue related to the SQL connector that you are using in your java application?

-Andrés B.

**Comment by phermann1988** [comment]
thank you!! i tried the steps you mentioned and i think it's the java SQL connector. I changed my pw to use ':' instead of '$' and now everything works perfect. ty!!

**Comment by andresbono** [comment]
Great to hear that it works now! :tada:

Thanks for letting us know, @phermann1988.
