### ISSUE TITLE
can't rmdir './test', errno: 39 "Directory not empty"

### ISSUE THREAD

**Issue by arvindjha** [bitnami/bitnami-docker-mariadb#160]
When I create container,the error happened.

#docker network create wordpress-tier
#docker volume create --name mariadb_data
#docker run -d --name mariadb \
 -e ALLOW_EMPTY_PASSWORD=yes \
 -e MARIADB_USER=bn_wordpress \
 -e MARIADB_DATABASE=bitnami_wordpress \
 --net wordpress-tier \
 --volume mariadb_data:/bitnami \
 bitnami/mariadb:latest

===========================
ERROR COMES:

WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
nami    INFO  Initializing mariadb
mariadb INFO  ==> Cleaning data dir...
mariadb INFO  ==> Configuring permissions...
mariadb INFO  ==> Validating inputs...
mariadb WARN  Allowing the "rootPassword" input to be empty
mariadb WARN  Allowing the "password" input to be empty
mariadb INFO  ==> Initializing database...
Error executing 'postInstallation': MySQL command failed to run. Error: 
 ERROR 1010 (HY000) at line 1: Error dropping database (can't rmdir './test', errno: 39 "Directory not empty")

THANKS IN ADVANCE 
Arvind jha

**Comment by tompizmor** [comment]
Hello @arvindjha,

Can you please check this issue https://github.com/bitnami/bitnami-docker-mariadb/issues/92 ?
It is about the same error.

**Comment by arvindjha** [comment]
so without storage driver change that is overlay to devicemapper we can not solve this issue ? please confirm.

**Comment by tompizmor** [comment]
If you are using a RedHat based operative system with the overlay storage driver it seems you need to change the storage driver to devicemapper, yes.

This is another related [issue](https://github.com/bitnami/bitnami-docker-mariadb/issues/149).

In any case, as you are in a production environment, I would try to reproduce the issue on a testing environment and check that the fix works as expected.
