### ISSUE TITLE
[BUG ] mariadb docker image failed to init custom sql files "files/docker-entrypoint-initdb.d"

### ISSUE THREAD

**Issue by inix** [bitnami/bitnami-docker-mariadb#170]
### 1.environment and package version

Host OS and version: `CentOS CentOS Linux release 7.3.1611 (Core)`
Docker version (docker version): `17.06.2-ce`
kubernetes version:` v1.10.0`
Output of docker info:
[docker info.txt](https://github.com/bitnami/charts/files/2504976/docker.info.txt)

Version of this container (echo $BITNAMI_IMAGE_VERSION inside the container)
```
mariadb docker v10.1.36
helm chart v5.2.1
```
The command you used to run the container, and any relevant output you saw (masking any sensitive information)
ERROR:
`ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/opt/bitnami/mariadb/tmp/mysql.sock' (2)`

### 2. Bug

Bitnami mariadb docker image failed to init custom sql script and caused container failed to start.
2.1 ERROR info:
`ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/opt/bitnami/mariadb/tmp/mysql.sock' (2)`

2.2 kubernetes dashboard error info:
```
pod has unbound PersistentVolumeClaims
Back-off restarting failed container
```

2.3 pod info:
[k8s desc.log](https://github.com/bitnami/charts/files/2504901/k8s.desc.log)

2.3 pod logs:
kubectl logs:
```
INFO  ==> ** Starting MariaDB setup **
INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars..
INFO  ==> Initializing mariadb database...
INFO  ==> Persisted data detected. Restoring...
INFO  ==> Loading user files from /docker-entrypoint-initdb.d ...
INFO  ==> Executing /docker-entrypoint-initdb.d/apolloconfigdb.sql
total 8
drwxrwxr-x 2 root root 4096 Oct 23 06:56 .
drwxr-xr-x 1 root root 4096 Oct 23 06:56 ..
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/opt/bitnami/mariadb/tmp/mysql.sock' (2 "No such file or directory")
INFO  ==> Stopping mariadb...
```
**Tips:** 
Mariadb do not print errors "ERROR 2002 (HY000): Can't..." messages by default,you need to hack the "libmysql.sh" initializing script,and build your custom mariadb docker image from https://github.com/bitnami/bitnami-docker-mariadb.

For example,you can disable error redirect by deleting `>/dev/null 2>&1`.
Before:
```
...
mysql_execute() {
    local db="${1:-}"
    local user="${2:-root}"
    local pass="${3:-}"

    info "db=$db;user=$user;pass=$pass"

    if [ -z  "$pass" ]; then
        cat - | "$DB_BINDIR/mysql" --defaults-file="$DB_CONFDIR/my.cnf" -N -u "$user" "$db" >/dev/null 2>&1
    else
        cat - | "$DB_BINDIR/mysql" --defaults-file="$DB_CONFDIR/my.cnf" -N -u "$user" -p"$pass" "$db" >/dev/null 2>&1
    fi
}
...
```

after:
```
...
mysql_execute() {
    local db="${1:-}"
    local user="${2:-root}"
    local pass="${3:-}"

    info "db=$db;user=$user;pass=$pass"

    if [ -z  "$pass" ]; then
        cat - | "$DB_BINDIR/mysql" --defaults-file="$DB_CONFDIR/my.cnf" -N -u "$user" "$db"
    else
        cat - | "$DB_BINDIR/mysql" --defaults-file="$DB_CONFDIR/my.cnf" -N -u "$user" -p"$pass" "$db"
    fi
}
...
```

### 3. Root cause
There is no file "/opt/bitnami/mariadb/tmp/mysql.sock" when execute custom init sql files.

### 4.repeat steps

- helm fetch stable/mariadb
- tar zxvf mariadb-5.2.1.tgz
- place custom init sql files into files/docker-entrypoint-initdb.d
- create kubernetes PV
- helm install ./mariadb --set replication.enabled=false

example custom sql files:
[apolloportaldb sql.zip](https://github.com/bitnami/charts/files/2504973/apolloportaldb.sql.zip)

**Comment by inix** [comment]
Hi,this is not a bug. I have found root cause of my case,old persistent volume data on the host path,and new db can not start due to permissions.

**Comment by tompizmor** [comment]
Thanks for updating the issue!
