### ISSUE TITLE
Pod restart failed with custom init scripts

### ISSUE THREAD

**Issue by ChristianSchlatter** [bitnami/bitnami-docker-mariadb#173]
**Description**
Custom init SQL script prevents Pod restart. This issue is related to the Bitnami MariaDB helm chart.

**Steps to reproduce the issue:**

1. Install MariaDB helm
2. Mount SQL script into /docker-entrypoint-initdb.d (named it init.sql)
3. Schedule / Start MariaDB Pod. During the first start everything worked fine. 
4. Restart the Pod, the MariaDB container doesn't come up again.

```
Welcome to the Bitnami mariadb container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb/issues
Send us your feedback at containers@bitnami.com
INFO ==> ** Starting MariaDB setup **
INFO ==> Validating settings in MYSQL_*/MARIADB_* env vars..
INFO ==> Initializing mariadb database...
DEBUG ==> Ensuring expected directories/files exist...
INFO ==> Persisted data detected. Restoring...
INFO ==> Loading user's custom files from /docker-entrypoint-initdb.d ...
DEBUG ==> Ignoring /docker-entrypoint-initdb.d/README.md
DEBUG ==> Executing /docker-entrypoint-initdb.d/init.sql
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/opt/bitnami/mariadb/tmp/mysql.sock' (2 "No such file or directory")
INFO ==> Stopping mariadb...
```

I guess the cause is following issue
https://github.com/bitnami/bitnami-docker-mariadb/blob/master/10.1/debian-9/rootfs/libmysql.sh#L675-L684
If we have an existing database, the database doesn't start in the background. Instead the script exits the mysql_initialize function. Later the script list all SQL files in the custom script directory and tries to execute them. But due the missing mysql_start_bg function call, the database isn't running at this moment.

**Describe the results you expected:**
Either Custom scripts should not be executed after the first startup, or the script should ensure the database is running during the script execution.

**Version**
Docker v17.3.2
**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
Kubernetes Version 1.12.3

**Comment by juan131** [comment]
Hi @ChristianSchlatter 

Even if we modify the logic so MariaDB is started at the point it tries to execute the SQL scripts, shouldn't we try to avoid running the scripts a second time? I mean, shouldn't the scripts be run only the first time the database is initialised?

**Comment by ChristianSchlatter** [comment]
>  I mean, shouldn't the scripts be run only the first time the database is initialised?
Yes, that is at least what the documentation says. But for now, if you add a SQL file and start the container with peristed data, it doesn't start. (See the log entry above)

**Comment by ChristianSchlatter** [comment]
I solved my problem. It was a Kubernetes related issue. The script runs only one time, didn't saw the .user_scripts_initialized file which prevents the for running a second time.

**Comment by juan131** [comment]
Hi @ChristianSchlatter 

Could you please provide more info about how you solved the issue?

**Comment by ChristianSchlatter** [comment]
As described in the Bitnami MariaDB helm repo

> The Bitnami MariaDB image allows you to use your custom scripts to initialize a fresh instance. In order to execute the scripts, they must be located inside the chart folder files/docker-entrypoint-initdb.d so they can be consumed as a ConfigMap.

So I simply had to add the init script in the file folder before I installed the chart.

**Comment by juan131** [comment]
Oh! I thought you were installing the chart using that method since the beginning!! 
Cool! Thanks for sharing it
