### ISSUE TITLE
How can I disable read_only on slave ? 

### ISSUE THREAD

**Issue by dbjpanda** [bitnami/bitnami-docker-mariadb#174]
I am preparing a stage server with replicating my production database.  Due to some workflow I just wanted read-write permission for slave. So passed the command in env variable like `MARIADB_EXTRA_FLAGS='--read-only=0'`. But I am not able to start the mariadb with that flag.  "Initializing mariadb database" is taking infinite time.  Why I am not able to override the variable  ( https://github.com/bitnami/bitnami-docker-mariadb/blob/f2077e570ecd310e7c5a75e294366903aa2a7b52/10.2/debian-9/rootfs/libmysql.sh#L184 )?

**Comment by andresbono** [comment]
Hi @dbjpanda, settings `read-only` to off in the slave node may lead into unexpected corruption of the database. Please read [Server System Variables: read_only](https://mariadb.com/kb/en/library/server-system-variables/#read_only).

If you still want to make your slave node read/write, you should modify the `libmysql.sh` file and build the container again.

Note that the logic in https://github.com/bitnami/bitnami-docker-mariadb/blob/f2077e570ecd310e7c5a75e294366903aa2a7b52/10.2/debian-9/rootfs/libmysql.sh#L184

Is appending the flags after the ones that you are setting by using `MARIADB_EXTRA_FLAGS` so they are overwritten.

**Comment by dbjpanda** [comment]
Yes. I already did that. Had to build it again as the read only was hard coded at run time. So I think it should not be hard-coded or if hard coded let users to override it via extra args or .inf file.

**Comment by andresbono** [comment]
Great @dbjpanda!

Maybe we can add a note in the README explaining all of this, but I don't think it's safe to have slave nodes allowing R/W operations for most use cases.

Thoughts, @juan131?

**Comment by juan131** [comment]
We allow overwriting the configuration file as it's explained in the link below:
https://github.com/bitnami/bitnami-docker-mariadb#overwrite-the-main-configuration-file

However, we don't allow overwriting the extra flags but extending them instead. I don't see any advantage on allowing write operations on production environments in the slaves since it can cause conflicts as @andresbono mentioned. 

Could you please provide more information about the reason why you're interested on this feature?

**Comment by dbjpanda** [comment]
We are using Drupal and our slave server attached to a website in stage. To make our stage website up there are some tables like session and cache which needs to be writable. We are only interested to replicate few tables only from master slave. So either we have planned to use --replicate-do-table or --replicate-ignore-table in this case.  

 In short we are replicating **only few tables** but setting read_only=1 for **entire database** !!!

**Comment by andresbono** [comment]
Ok, thanks for describing the environment that you have in place.

We'll analyze the implementation and the risks again.

In any case, overwriting the `libmysql.sh` script is working for you, right?

**Comment by dbjpanda** [comment]
@andresbono Yes modifying in libmysql.sh works.

**Comment by andresbono** [comment]
Oh, nice!
