### ISSUE TITLE
How to build mariadb rhel7 ? 

### ISSUE THREAD

**Issue by lduparc** [bitnami/bitnami-docker-mariadb#180]
Cloning the project I'm unable to build the docker image for 10.2.-rhel-7 version.

Asking for subscription-manager account ... what is the process to be able to build it ?

Thanks

**Comment by carrodher** [comment]
Hi, are you using a subscribed Red Hat host to build the image? The build action should be successful from any RHEL Host system running the Docker service with subscription managed registered, you can find more information about how to register your system at the following link https://access.redhat.com/solutions/253273

**Comment by lduparc** [comment]
Thanks
