### ISSUE TITLE
How to link existing data dir ?

### ISSUE THREAD

**Issue by lduparc** [bitnami/bitnami-docker-mariadb#181]
In order to have performance, I'm not using a dump to populate my database. I'm copying an existing /var/lib/mysql dir into the /bitnami/data but data is not available when container is running. How to perform this kind of data loading ?

**Comment by alemorcuq** [comment]
Hi @lduparc,

To do that, you can mount your copy of `/var/lib/mysql` to `/bitnami/mariadb/data`. For example:

```
docker run -e ALLOW_EMPTY_PASSWORD=yes \
           -v /path/to/var/lib/mysql:/bitnami/mariadb/data bitnami/mariadb:10.2
```

However, you will have to ensure first that the directory has the correct permissions (keep in mind the container runs as user 1001). A `chown` would work:

```
chown -R 1001 /path/to/var/lib/mysql
```

If you are using Kubernetes, you could use the help of an init container to set the permissions properly.

Also, when the container [is run for the first time](https://github.com/bitnami/bitnami-docker-mariadb#initializing-a-new-instance) it will execute files located at `/docker-entrypoint-initdb.d`. It may be useful for you.

**Comment by lduparc** [comment]
Hi @alemorcuq,

Thanks for your feedback. I'm already use `/docker-entrypoint-initdb.d` to load some sql migration. My issue is to mount an existing dir to bitnami. Using docker run & docker-compose it's ok but using Kubernetes I don't know how to perform this except using persistant volume with init-containers.

What I want is only a dockerfile getting existing data with source /var/lib/mysql and target /bitnami/mariadb/data but I don't know how to do this using kubernetes. Regarding permissions it's ok.

**Comment by alemorcuq** [comment]
Hi @lduparc,

> Persistant volume is not an option. I need to be able to start multiple mariadb instance for tests with isolated data. Using dymanic volume instead of have to clean a storage everytime.

I don't fully understand why using persistent volumes is not an option for you. Could you please provide more information?

With an init container you can use two volumes:

- One for your source data.
- The MariaDB data volume.

This way you can prepare your data to be available for MariaDB.

> What I want is only a dockerfile getting existing data with source /var/lib/mysql and target /bitnami/mariadb/data but I don't know how to do this using kubernetes. Regarding permissions it's ok.

You can always modify the Dockerfile to take your data and build your own image. However, it's usually best to separate your data from your image.

**Comment by lduparc** [comment]
below an example what I would like to do using dockerfile : 

```
FROM busybox:latest as builder

RUN mkdir -p /bitnami/mariadb/data
RUN wget my_existing_mysql_data_dir -o /bitnami/mariadb/data

FROM bitnami/mariadb:10.2

VOLUME /bitnami/mariadb/data

COPY --from=builder /bitnami/mariadb/data /bitnami/mariadb/data
```

> With an init container you can use two volumes:
> 
> One for your source data.
> The MariaDB data volume.

In this case I will have a dockerfile with data on path `/var/lib/mysql` for example and run a command like `cp /var/liib/mysql /bitnami/mariadb/data` on initContainer and after start my container with volumeMount on /bitnami/mariadb/data ?
