### ISSUE TITLE
profiling queries on database instance

### ISSUE THREAD

**Issue by fede-green** [bitnami/bitnami-docker-mariadb#187]
Hello, 

i am working on a lando machine that uses a mariadb instance. I would like to profile all of the executed queries on the DB. As far as i researched, i tried using two different methods: 

#setup my mariadb instance to log all of the executed queries to the disc:
so i'm launching the DB instance using this my.cnf 
```
[mariadb]
# enable the slow query log
enable_slow_query_log
# enable general log
general_log
# set general log file
general-log-file=/tmp/dblog.log
```
when i query `SHOW VARIABLES LIKE "general_log%";` all of my entries are there, but then the log file stays empty when my application runs.

so i also read that i could use this method: `mysqladmin -i 1 processlist`. The problem with this is i get: 
```
mysqladmin: connect to server at 'localhost' failed
error: 'Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2 "No such file or directory")'
Check that mysqld is running and that the socket: '/var/run/mysqld/mysqld.sock' exists!
```
is there a way to get all of the queries out of the machine?

**Comment by andresbono** [comment]
Hi @fede-green,

The first method works for me. Did you restart the container after changing the configuration?

You can restart it or configure it dynamically as specified here: https://mariadb.com/kb/en/library/general-query-log/#configuring-the-general-query-log-filename

What I tried:

```
$ docker exec -it mariadb mysql -uroot
> SET GLOBAL general_log=1;
> SET GLOBAL general_log_file='/tmp/dblog.log';

> SHOW DATABASES;

$ docker exec -it mariadb cat /tmp/dblog.log
/opt/bitnami/mariadb/sbin/mysqld, Version: 10.3.16-MariaDB (Source distribution). started with:
Tcp port: 3306  Unix socket: /opt/bitnami/mariadb/tmp/mysql.sock
Time		    Id Command	Argument
190802  7:46:11	     8 Quit
190802  7:46:35	     9 Connect	root@localhost as anonymous on
		     9 Query	show databases
		     9 Quit
```

Hope this is helpful!
