### ISSUE TITLE
Error executing 'postInstallation': EIO: i/o error, lstat '/bitnami/mariadb/.restored'

### ISSUE THREAD

**Issue by paxinos** [bitnami/bitnami-docker-mariadb#190]
Container has been running for a couples months.   When performing an update of kubernetes on the cluster, the container no longer start.   Error in the logs is:

```
Welcome to the Bitnami mariadb container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb/issues

nami INFO Initializing mariadb
Error executing 'postInstallation': EIO: i/o error, lstat '/bitnami/mariadb/.restore
```

**Comment by juan131** [comment]
Hi @paxinos 

What kind of persistence were you using in the MariaDB pod? It looks like something is wrong in the data directory `/bitnami/mariadb` where the persistent volumes are usually mounted.
I assume you deployed the container using the MariaDB Helm chart (`stable/mariadb`), am I right?
