### ISSUE TITLE
init script doesn't work for slave mode

### ISSUE THREAD

**Issue by s-mansouri** [bitnami/bitnami-docker-mariadb#197]
**Description**
I am trying to use custom init script for MariaDB in slave mode but after loading my script MariaDB stop and don't work 

**Steps to reproduce the issue:**
here is my docker-compose.yml:
```yml
version: '3.6'
services:
  mariadb-master:
    image: 'bitnami/mariadb:10.1.41-debian-9-r35'
    ports:
      - '3306'
    volumes:
      - ./initscript:/docker-entrypoint-initdb.d
    environment:
      - MARIADB_REPLICATION_MODE=master
      - MARIADB_REPLICATION_USER=repl_user
      - MARIADB_USER=my_user
      - MARIADB_DATABASE=my_database
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_ROOT_PASSWORD=my_root_password
  mariadb-slave:
    image: 'bitnami/mariadb:10.1.41-debian-9-r35'
    ports:
      - '3306'
    volumes:
      - ./initscript:/docker-entrypoint-initdb.d
    depends_on:
      - mariadb-master
    environment:
      - MARIADB_REPLICATION_MODE=slave
      - MARIADB_REPLICATION_USER=repl_user
      - MARIADB_USER=my_user
      - MARIADB_DATABASE=my_database
      - MARIADB_MASTER_HOST=mariadb-master
      - MARIADB_MASTER_PORT_NUMBER=3306
      - MARIADB_MASTER_ROOT_PASSWORD=my_root_password
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
```
here is my init script for both master and slave:
```
SET GLOBAL gtid_strict_mode=ON;
```

**Describe the results you received:**
For the master, it works fine but for the slave, container exited, here is the slave log

```bash
 04:59:56.86 Welcome to the Bitnami mariadb container
 04:59:56.86 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb
 04:59:56.86 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb/issues
 04:59:56.86 Send us your feedback at containers@bitnami.com
 04:59:56.86 
 04:59:56.86 INFO  ==> ** Starting MariaDB setup **
 04:59:56.89 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars..
 04:59:56.89 INFO  ==> Initializing mariadb database...
 05:00:09.79 INFO  ==> Configuration replication mode...
 05:00:12.86 INFO  ==> Loading user's custom files from /docker-entrypoint-initdb.d ...
 05:00:12.87 INFO  ==> Stopping mariadb...
```

With version '10.1.36-debian-9-r0' the slave gives this error:

```bash
INFO  ==> MariaDB init process in progress...
INFO  ==> MariaDB init process in progress...
INFO  ==> MariaDB init process in progress...
ERROR ==> MariaDB init process failed.
Executing /docker-entrypoint-initdb.d/gtid-replication.sql
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)

mysqladmin: connect to server at 'localhost' failed
error: 'Access denied for user 'root'@'localhost' (using password: NO)'
MariaDB init process failed.
```
#195

**Comment by marcosbc** [comment]
Hi @s-mansouri, the problem is MySQL is stopped right after you set `gtid_strict_mode=ON`, meaning you would need to add the line `gtid_strict_mode` inside the `[mysqld]` section in `my.cnf`.

However, if you set it too son in `my.cnf` (i.e. before the replication is configured) it will not work.

I've created an internal task for implementing this feature, but unfortunately I cannot give an ETA for when it would be done.

Feel free to contribute this change if you prefer, keeping in mind that this should be configurable -disabled by default- and would only apply for MariaDB -you can differentiate with the `DB_FLAVOR` environment variable in `libmysql.sh`-.

Thanks!

**Comment by s-mansouri** [comment]
@marcosbc Thank you for your help.
I don't think it is because of `gtid_strict_mode`. I put other commands but still slave stops. furthermore this command doesn't stop master!

**Comment by marcosbc** [comment]
Hi @s-mansouri, we have reproduced this issue, and it seems like there are a few issues on MariaDB. The most important one is it doesn't run `mysql_upgrade` after each start, which may be problematic. If we run it, we get the same `Access denied` error.

We're investigating this and will get back with any progress.

**Comment by mostafahussein** [comment]
Any updates on this one?

**Comment by andresbono** [comment]
Hi @mostafahussein, we have made several improvements to the MariaDB container image in this period. Are you still facing this specific issue with the latest version of the image?

**Comment by sida-khalibre** [comment]
any update?

**Comment by andresbono** [comment]
> Hi @mostafahussein, we have made several improvements to the MariaDB container image in this period. Are you still facing this specific issue with the latest version of the image?

Hi @sida-khalibre, we have made a bunch of updates since this issue was opened. are you still facing this issue? Can you give us more details on the specifics of your issue?

**Comment by sida-khalibre** [comment]
> > Hi @mostafahussein, we have made several improvements to the MariaDB container image in this period. Are you still facing this specific issue with the latest version of the image?
> 
> Hi @sida-khalibre, we have made a bunch of updates since this issue was opened. are you still facing this issue? Can you give us more details on the specifics of your issue?

Still sae issue

**Comment by andresbono** [comment]
Hi @sida-khalibre, I noticed that we are actually preventing the executing of sql files in slave nodes:

https://github.com/bitnami/bitnami-docker-mariadb/blob/e6a19d3e5038f9102842e0e82135ce6e70e6c033/10.4/debian-10/rootfs/opt/bitnami/scripts/libmysql.sh#L463

And that makes sense, you should only be altering the database in the master node but not in the rest.

Can you share with us the docker-compose that you are using to deploy the cluster and tell us more details about your use case?

**Comment by sida-khalibre** [comment]
> Hi @sida-khalibre, I noticed that we are actually preventing the executing of sql files in slave nodes:
> 
> https://github.com/bitnami/bitnami-docker-mariadb/blob/e6a19d3e5038f9102842e0e82135ce6e70e6c033/10.4/debian-10/rootfs/opt/bitnami/scripts/libmysql.sh#L463
> 
> And that makes sense, you should only be altering the database in the master node but not in the rest.
> 
> Can you share with us the docker-compose that you are using to deploy the cluster and tell us more details about your use case?

My use case is to setup MaraiDB master/slave replication using GTID slow it can be managed by maxscale monitoring.

**Comment by carrodher** [comment]
Hi, in order to be able to reproduce your use case it would be nice to have a `docker-compose` file (without sensitive data like passwords or usernames), and not only the docker-compose if you are mounting custom configuration files or something like that it would also be very useful for us. On this way, we can reproduce the same (or as similar as possible) use case

**Comment by fisherwei** [comment]
> Hi, in order to be able to reproduce your use case it would be nice to have a `docker-compose` file (without sensitive data like passwords or usernames), and not only the docker-compose if you are mounting custom configuration files or something like that it would also be very useful for us. On this way, we can reproduce the same (or as similar as possible) use case

the slave just use:
```
docker create --name mariadb-slave \
  -e MARIADB_REPLICATION_MODE=slave \
  -e MARIADB_REPLICATION_USER=my_repl_user \
  -e MARIADB_REPLICATION_PASSWORD=my_repl_password \
  -e MARIADB_MASTER_HOST=master \
  -e MARIADB_MASTER_ROOT_PASSWORD=master_root_password \
  -e BITNAMI_DEBUG=true \
  -v $(pwd)/data:/bitnami/mariadb \
  -p 3306:3306 \
  bitnami/mariadb:latest
```

the first time, it is OK,
restart container, it will failed.

log:

> 2020-06-10  6:13:19 9 [Warning] Access denied for user 'root'@'localhost' (using password: YES)
Version check failed. Got the following error when calling the 'mysql' command line client
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
FATAL ERROR: Upgrade failed
mariadb 06:13:19.77 INFO  ==> Stopping mariadb

**Comment by andresbono** [comment]
Hi @fisherwei, is the problem you are facing related to this issue? (init scripts not working for slave nodes). The command that you showed doesn't use init scripts, is that right?

**Comment by fisherwei** [comment]
> Hi @fisherwei, is the problem you are facing related to this issue? (init scripts not working for slave nodes). The command that you showed doesn't use init scripts, is that right?

you are correct, i deleted my post

**Comment by andresbono** [comment]
@fisherwei, please open a new one if you identified an issue with this container!

**Comment by carrodher** [comment]
In order to unify the approaches followed in Bitnami containers and Bitnami charts, we are moving some issues in `bitnami/bitnami-docker-<container>` repositories to `bitnami/containers`. Please follow [bitnami/containers](https://github.com/bitnami/containers) to keep you updated about the latest bitnami images.

If this issue is still applicable, please feel free to recreate it at https://github.com/bitnami/containers/issues/new/choose

More information here: https://blog.bitnami.com/2022/07/new-source-of-truth-bitnami-containers.html
