### ISSUE TITLE
Building my own mariadb-10.3.18-1-linux-amd64-debian-9.tar.gz for Raspberry Pi instead

### ISSUE THREAD

**Issue by jrcichra** [bitnami/bitnami-docker-mariadb#200]
I'm looking to build this image for ARM processors. I see libcomponent.sh is used to download this mariadb tarball: mariadb-10.3.18-1-linux-amd64-debian-9.tar.gz.

Looking inside to the MariaDB file structure, doesn't look like what the mariadb site cmake creates:

![image](https://user-images.githubusercontent.com/1342149/65386526-d84f5500-dd0a-11e9-8a20-e75258c659ba.png)

![image](https://user-images.githubusercontent.com/1342149/65386534-02087c00-dd0b-11e9-8187-132a29262c80.png)

How can I recreate this tarball to build the container for arm? Thanks.

**Comment by rafariossaa** [comment]
Hi, @jrcichra 
  In our compilation pipeline, the packaging also removes files not needed latter. Also the output will vary depending on your compilation options, like the prefix and the other several install directives.
  Did you tried setting a prefix dir ?

**Comment by jrcichra** [comment]
I just followed the instructions here: https://mariadb.com/kb/en/library/generic-build-instructions/#using-cmake

cmake ../server -DBUILD_CONFIG=mysql_release

I do not have any prefixes, nor do I know how to set one up.

**Comment by jrcichra** [comment]
Would it be possible to "apt install mariadb-server" and utilize that in the existing tooling instead of the bitnami tar.gz?

**Comment by rafariossaa** [comment]
No, it is not possible. 
One of the reasons to create the package by ourselves is to have control of the installation process, the location of the files, etc.

Let me check if I can provide more instructions.

**Comment by jrcichra** [comment]
@rafariossaa , if its not possible, I might try and manually place my binaries overtop of the x86 binaries of the provided tarball. It's a long shot, but it might work...

**Comment by rafariossaa** [comment]
Hi @jrcichra,
  I got some information to share:

Hi,
  Theese are the flags we use for cmake, where prefix is the install directory.

```
      -DCMAKE_INSTALL_PREFIX=${prefix}
      -DDEFAULT_SYSCONFDIR=${prefix}/conf
      -DSYSCONFDIR=${prefix}/conf
      -DINSTALL_SBINDIR=sbin',
      -DINSTALL_SCRIPTDIR=${prefix}/bin
      -DINSTALL_PLUGINDIR=plugin
      -DINSTALL_INFODIR=${prefix}/info
      -DINSTALL_SUPPORTFILESDIR=${prefix}/share
      -DMYSQL_DATADIR=${prefix}/data
      -DCURSES_INCLUDE_PATH=/usr/include/
      -DMYSQL_UNIX_ADDR=${prefix}/tmp/mysql.sock
      -DENABLED_LOCAL_INFILE=ON
      -DWITH_INNOBASE_STORAGE_ENGINE=1
      -DWITH_ARCHIVE_STORAGE_ENGINE=1
      -DWITH_BLACKHOLE_STORAGE_ENGINE=1
      -DWITH_PERFSCHEMA_STORAGE_ENGINE=1
      -DWITH_FEDERATED_STORAGE_ENGINE=1
      -DWITH_PARTITION_STORAGE_ENGINE=1
      -DPLUGIN_AUTH_PAM=YES

```
  Then some unneded  files and directories are removed like: `man`, `mysql-test`, `sql-bench`

  Hope this helps.

**Comment by jrcichra** [comment]
@rafariossaa - thank you very much, I'll try it and get back to you.

**Comment by rafariossaa** [comment]
ok, thanks

**Comment by rafariossaa** [comment]
Your are welcome, I am sorry to hear that.

Please don't hesitate to open a new issue if you find problems.

I am closing this issue now.
