### ISSUE TITLE
Helm Kubernetes installation freezes on "Installing database"

### ISSUE THREAD

**Issue by ErmakovDmitriy** [bitnami/bitnami-docker-mariadb#203]
**Description**

When I try to deploy helm chart stable/mariadb,  mariadb installation stops on "Installing database" step. After `livenessProbe.initialDelaySeconds` the container is restarted by Kubernetes.
I tried to set `livenessProbe.initialDelaySeconds` to 600 seconds which did not help me.
Setting image.debug=true did not give me any information.

**Steps to reproduce the issue:**

1. Edit values.yaml to set image.debug = true
2. Install helm chart `helm install --name test --values=values.yaml stable/mariadb`
3. Wait until after `livenessProbe.initialDelaySeconds` Kubernetes kills pod.

**Describe the results you received:**

Mariadb installing database did not finish in 120 seconds.
Kubernetes started liveness check after 120 seconds and after 3 failures killed mariadb pod.
Kubernetes restarted pod and killed it one more time (I think it would be infinite loop of liveness fail => kill => restart).

**Describe the results you expected:**

I expected to have a working mariadb server.

**Additional information you deem important (e.g. issue happens only occasionally):**

Kubernetes: v1.15.4
OS: CentOS Linux 7 (Core)
Kernel: 3.10.0-1062.el7.x86_64
Storage provisioner: [NFS-client-provisioner](https://github.com/helm/charts/tree/master/stable/nfs-client-provisioner)
Helm chart version: 7.0.1
App version: 10.3.20

**Version**

- Output of `docker version`: 

```
Client: Docker Engine - Community
 Version:           19.03.4
 API version:       1.40
 Go version:        go1.12.10
 Git commit:        9013bf583a
 Built:             Fri Oct 18 15:52:22 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.4
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.10
  Git commit:       9013bf583a
  Built:            Fri Oct 18 15:50:54 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

```

- Output of `docker info`:

```

Client:
 Debug Mode: false

Server:
 Containers: 57
  Running: 50
  Paused: 0
  Stopped: 7
 Images: 30
 Server Version: 19.03.4
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 3.10.0-1062.el7.x86_64
 Operating System: CentOS Linux 7 (Core)
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 2.883GiB
 Name: d8e-c1-0b-27-5d-44.my-domain.local
 ID: WBQH:GRZ4:PQC3:RKD4:EWW3:LN66:B6RM:KHH3:N4MG:WKD7:KYHN:MMNG
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

```

- Output of `docker-compose version` (if applicable):

```
N/A
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
Kubernetes nodes are deployed on Proxmox KVM hypervisor. NFS Server is on the same hypervisor, another deployments work well with NFS provisioned Persistent Volumes.
I tried to set `livenessProbe.initialDelaySeconds` to 600 and even 3600 seconds.

Here is my [full log](https://pastebin.com/83qf7vJs) for 120 seconds `livenessProbe.initialDelaySeconds`.

**Comment by juan131** [comment]
Hi @ErmakovDmitriy 

It's very likely the NFS provider you're using is very slow for write operations. Therefore, MariaDB takes so long to initialize. As a workaround, you could:

- Install the chart disabling the readiness/liveness probes
- Wait until MariaDB initializes the database
- Upgrade the chart enabling the readiness/liveness probes (the containers will detect the persisted data and they won't initialize again the db)

**Comment by sameersbn** [comment]
@ErmakovDmitriy Were you able to try out the suggestions by @juan131? 

> I tried to set `livenessProbe.initialDelaySeconds` to 600 seconds which did not help me.

`600` seconds is a lot. I would have expected the initialisation to complete within this period. It's weird that it did not. It does look like it could be a issue with the performance of the NFS volumes. To be sure that it's the case you can try disabling the persistence storage with `--set master.persistence.enabled=false  --set slave.persistence.enabled=false`.

Another thing you may want to give a try is setting `volumePermissions.enabled=true`. 

Do let us know if you have any updates.
