### ISSUE TITLE
Certain symbols in passwords not supported

### ISSUE THREAD

**Issue by enote-kane** [bitnami/bitnami-docker-mariadb#204]
**Description**
When providing passwords in Kubernetes secrets generated from pwgen -scyBn 15 1, most of the time the chart fails to spin up MariaDB correctly and/or checks are failing (maybe due to shell interpretation?).

**Steps to reproduce the issue:**

1. Start the image using a root password like `l\<ZM][a\Fx1U*v`, e.g.:

```bash
docker run -ti --rm -e MARIADB_ROOT_PASSWORD='l\<ZM][a\Fx1U*v' bitnami/mariadb:latest
```

**Describe the results you received:**

The image starts up the MariaDB server but then exits with an error code without producing an error log.

**Describe the results you expected:**

The image starts up as normal and the root password is set as specified.

**Additional information you deem important (e.g. issue happens only occasionally):**

Example (full) output of a Docker session using the above root password:
```
 09:37:54.03 
 09:37:54.03 Welcome to the Bitnami mariadb container
 09:37:54.03 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb
 09:37:54.03 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb/issues
 09:37:54.03 Send us your feedback at containers@bitnami.com
 09:37:54.04 
 09:37:54.04 INFO  ==> ** Starting MariaDB setup **
 09:37:54.06 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars
 09:37:54.07 INFO  ==> Initializing mariadb database
 09:37:54.10 INFO  ==> Installing database
 09:37:56.17 INFO  ==> Starting mariadb in background
 09:37:57.19 INFO  ==> Configuring authentication
 09:37:57.21 INFO  ==> Stopping mariadb
```

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           19.03.3
 API version:       1.40
 Go version:        go1.12.10
 Git commit:        a872fc2f86
 Built:             Tue Oct  8 01:00:44 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.3
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.10
  Git commit:       a872fc2f86
  Built:            Tue Oct  8 00:59:17 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

- Output of `docker info`:

```
(paste your output here)
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.21.0, build unknown
docker-py version: 3.4.1
CPython version: 3.7.5
OpenSSL version: OpenSSL 1.1.1c  28 May 2019
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by juan131** [comment]
Hi @enote-kane 

It seems the unique symbol that's not supported is the the backslash (`\`):

> Because MySQL uses C escape syntax in strings (for example, \n to represent a newline character), you must double any \ that you use in LIKE strings. For example, to search for \n, specify it as \\n. To search for \, specify it as \\\\; this is because the backslashes are stripped once by the parser and again when the pattern match is made, leaving a single backslash to be matched against.

More info at https://dev.mysql.com/doc/refman/8.0/en/string-comparison-functions.html

Therefore, the only thing we can do is to detect the backslash, and escape them before creating the root user at:

- https://github.com/bitnami/bitnami-docker-mariadb/blob/master/10.2/debian-9/rootfs/libmysql.sh#L769

As a workaround you can add use the `-r` option of `pwgen` to exclude the backslash character from the passwords you generate.

**Comment by enote-kane** [comment]
+1 for escaping the backslash character, but it should also be made explicit what the escape character is for this command, in case someone provides a different standard escape character using the server configuration (if that's possible, IDK).

**Comment by juan131** [comment]
Hi @enote-kane 

I've been trying to figure out how we can escape the backslash and it's not simple at all, mainly because it has to be escaped on certain actions (e.g. queries) while it can be used as it's for others. There are also exceptions to handle depending on the position of the backslash.

As a workaround I'm thinking on providing some error when a password including backslashes is set so users are notified about this error.

**Comment by enote-kane** [comment]
Hi @juan131 , thank you for investigating.

I understand, but still people will run into this where passwords are generated in a secure way and they certainly do not expect to have a password character limitation applied.

As an alternative, I would suggest to set the password using a hash variant using the notation `create user '$user'@'%' identified by password '$password_hash';`. Of course, that means first producing a correct hash, but there should be tools available.

As MariaDB does not yet support the SHA-2 plugin, we're most likely stuck with the "mysql_native_password" plugin to support all clients ("ed25519" requires client support AFAIK). That's also how other tools apply the password, e.g. [Puppet](https://github.com/puppetlabs/puppetlabs-mysql/blob/master/lib/puppet/provider/mysql_user/mysql.rb#L77) ([actual hashing function](https://github.com/puppetlabs/puppetlabs-mysql/blob/master/lib/puppet/functions/mysql/password.rb))

**Comment by juan131** [comment]
> I understand, but still people will run into this where passwords are generated in a secure way and they certainly do not expect to have a password character limitation applied.

I agree but there's no much we can the application itself (MariaDB/MySQL in this case) has this limitation. 

I just created a PR to add the validation I mentioned before.

**Comment by enote-kane** [comment]
Erhm, sorry but that is not true (maybe only for the way bitnami deals with passwords here, not MySQL or MariaDB).

Example:
```bash
$ wget -q 'https://raw.githubusercontent.com/parcejohn/mysql_password_hash/master/mysql_password_hash'
$ python mysql_password_hash --password 'l\<ZM][a\Fx1U*v' | sed -n -E 's/^HASH: //p' | tr 'a-z' 'A-Z'
*3DAF14BB6005EC46C03D2B6079F45A50976EF49F
$ sudo mysql mysql
mysql> CREATE USER test@'%' IDENTIFIED WITH mysql_native_password AS '*3DAF14BB6005EC46C03D2B6079F45A50976EF49F';
Query OK, 0 rows affected (0.01 sec)

mysql> GRANT SELECT ON mysql.* TO test;
Query OK, 0 rows affected (0.00 sec)

mysql> quit
Bye

$ export MYSQL_PWD='l\<ZM][a\Fx1U*v'
$ mysql --user=test --execute 'SELECT count(*) FROM user' mysql
+----------+
| count(*) |
+----------+
|        7 |
+----------+
```

So here is the proof that a password containing a backslash character is just working fine.

**Comment by sameersbn** [comment]
@enote-kane thanks for sharing this information. We will evaluate the possibility of hashing the passwords in the image.

**Comment by grooverdan** [comment]
There's only one escaping needed, the form inside a string literal:

Hint: https://github.com/MariaDB/mariadb-docker/blob/master/docker-entrypoint.sh#L239
escape `\`, `\n` and then `'`. Then use it in a way that the shell doesn't expand it.

Also note: `SET @@SESSION.SQL_MODE=REPLACE(@@SESSION.SQL_MODE, 'NO_BACKSLASH_ESCAPES', '');` in case the user has changed the default.

**Comment by juan131** [comment]
Hi @grooverdan 

Our current approach consists on showing a warning when we detect a backslash, see:

- https://github.com/bitnami/bitnami-docker-mariadb/blob/master/10.6/debian-10/rootfs/opt/bitnami/scripts/libmariadb.sh#L114

However, I agree that the ideal solution would be to have a proper way to scape these special characters. Would you like to contribute with a PR to add this feature?

**Comment by carrodher** [comment]
Just for the records. It seems I'm able to reproduce a similar issue when the password contains `"` (see https://github.com/bitnami/charts/issues/8380)
```console
$ docker run --name mariadb -e MARIADB_ROOT_PASSWORD='asdasd"rrr' -e BITNAMI_DEBUG=true bitnami/mariadb:latest
...
mariadb 17:56:04.02 DEBUG ==> Executing SQL command:
-- create root@localhost user for local admin access
-- create user 'root'@'localhost' identified by "asdasd"rrr";
-- grant all on *.* to 'root'@'localhost' with grant option;
-- create admin user for remote access
create user 'root'@'%' identified  by "asdasd"rrr";
grant all on *.* to 'root'@'%' with grant option;
flush privileges;
ERROR 1064 (42000) at line 5: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'rrr";
grant all on *.* to 'root'@'%' with grant option;
flush privileges' at line 1
mariadb 17:56:04.02 INFO  ==> Stopping mariadb
...
```

**Comment by carrodher** [comment]
In order to unify the approaches followed in Bitnami containers and Bitnami charts, we are moving some issues in `bitnami/bitnami-docker-<container>` repositories to `bitnami/containers`. Please follow [bitnami/containers](https://github.com/bitnami/containers) to keep you updated about the latest bitnami images.

If this issue is still applicable, please feel free to recreate it at https://github.com/bitnami/containers/issues/new/choose

More information here: https://blog.bitnami.com/2022/07/new-source-of-truth-bitnami-containers.html
