### ISSUE TITLE
about mariabackup's bug

### ISSUE THREAD

**Issue by zhuochengs** [bitnami/bitnami-docker-mariadb#205]
thanks a lot first! My English is just so so~, please..

I was used your image: `bitnami/mariadb:10.3.18-debian-9-r36` into my k8s cluester, and then find the mysql dump backup always been errors. So I tried all your 10.3 10.4 image containers, and find that an error what I think was when I used like this 
`mariabackup --backup --host=XX.XX.XX.XX --port=3306 --target-dir /backup/$(date +%y-%m-%d_%H_%M_%S)_fullbackup/ --user root --password XXXXXX`
then
```
[00] 2019-12-03 15:26:44 Waiting for log copy thread to read lsn 21872158
[00] 2019-12-03 15:26:45 >> log scanned up to (139845)
[00] 2019-12-03 15:26:46 >> log scanned up to (139845)
[00] 2019-12-03 15:26:47 >> log scanned up to (139845)
[00] 2019-12-03 15:26:48 >> log scanned up to (139845)
[00] 2019-12-03 15:26:49 >> log scanned up to (139845)
[00] 2019-12-03 15:26:50 >> log scanned up to (139845)
[00] 2019-12-03 15:26:51 >> log scanned up to (139845)
```
until over timeout...
![image](https://user-images.githubusercontent.com/17957646/70029320-c1b65b80-15e1-11ea-9846-021f69350f33.png)

BUT

I tried the official image, it can be works!

so WHY? please help me, thanks again!~

**Comment by tompizmor** [comment]
Hi,

I tried to reproduce with this docker-compose and backup command and it worked:

**docker-compose.yml**
```
version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:10.3.18-debian-9-r36'
    ports:
      - '3306:3306'
    environment:
      - MARIADB_ROOT_PASSWORD=qwer1234
```

**backup command**
```
mariabackup --backup --host=127.0.0.1 --port=3306 --target-dir /tmp/$(date +%y-%m-%d_%H_%M_%S)_fullbackup/ --user root --password qwer1234
```

Can you tell us a bit more about your configuration?
Do you have a standalone MariaDB server or do you have a master-slave configuration?
How much data do you have? If you have a lot of GBs maybe the timeout is because of that.

**Comment by zhuochengs** [comment]
thanks a lot!
 I just used docker run command to start a mariadb container like that:
   docker run --name mariadb-test \
    -p 3308:3306 \
	--restart always \
	-v /etc/localtime:/etc/localtime \
	-e MARIADB_ROOT_PASSWORD=root123456 \
    -v /home/mariadb:/bitnami/mariadb \
    -d pro.harbor.amaster.com/library/bitnami/mariadb:10.3.18-debian-9-r36

AND then I want use the mariabackup command in another mariadb-backup container to backup the mariadb-test container's data. the mariadb-backup container command like that:

docker run --name mariadb-backup \
	-v /etc/localtime:/etc/localtime \
	--network host \
	-e MYSQL_ROOT_PASSWORD=123456  \
    -v /home/backup/mariadb/data:/backup \
    -d pro.harbor.amaster.com/library/bitnami/mariadb:10.3.18-debian-9-r36

When I used the command 

mariabackup --backup --host=MY IP --port=3306 --databases=mysql --target-dir /backup/$(date +%y-%m-%d_%H_%M_%S)_fullbackup/   --user root --password root123456

to backup the data, it occur the error , but when I execute the command in the mariadb-test container ,it works, but it's localhost , not suit my condition.

**Comment by tompizmor** [comment]
Hi @zhuochengs,

I tried now to create a backup from a remote machine and also got issues. We will further investigate this issue and update it once we have more information.

Thanks for reporting!

**Comment by zhuochengs** [comment]
Thanks very much!

**Comment by javsalgar** [comment]
I do not have much experience about the `innodb_buffer_pool_size` parameter. Regarding the k8s `request` that you set, that will guarantee that it will be scheduled to a node that can provide that amount of memory and CPU, and by making `limits` and `request` the same, it will increase the priority of the pod. I am not sure if I understood correctly what you want to achieve. Is it something that we can reproduce with less amount of CPU and memory? Also, I would move this conversation to a different ticket so it is less confusing for other users.

**Comment by zhuochengs** [comment]
@javsalgar thanks very much, and I had set the same parameter with the limits and request resource~

**Comment by sameersbn** [comment]
@zhuochengs thanks for the information. We are working on investigating this issue and will get back to you with the update

**Comment by zhuochengs** [comment]
em, happy new year everyone!
   I found somthing not good.  I set the config like that, and I found my master is normal but the slave's memory is growing up every day, and now, it's almost up my limits.
  this is my master's memory used:
![image](https://user-images.githubusercontent.com/17957646/71639388-bc1b6680-2cb0-11ea-815a-52fd2535ae5b.png)

and this is my slave's memory used:
![image](https://user-images.githubusercontent.com/17957646/71639394-ce95a000-2cb0-11ea-9163-0063c3ed6635.png)

I tried to set many config's ,it's not work, I found a part of question is my slow query, and another question is the batch insert , when I test it on the dev and insert 500 counts cost 200ms, but it cost almost 2s on line's. I do not know what happened... this is my all sets
`Aborted_clients	1849
Aborted_connects	7
Access_denied_errors	0
Acl_column_grants	0
Acl_database_grants	3
Acl_function_grants	0
Acl_procedure_grants	0
Acl_package_spec_grants	0
Acl_package_body_grants	0
Acl_proxy_users	1
Acl_role_grants	0
Acl_roles	0
Acl_table_grants	0
Acl_users	3
Aria_pagecache_blocks_not_flushed	0
Aria_pagecache_blocks_unused	15706
Aria_pagecache_blocks_used	15706
Aria_pagecache_read_requests	43114705
Aria_pagecache_reads	289826
Aria_pagecache_write_requests	10694217
Aria_pagecache_writes	326665
Aria_transaction_log_syncs	76
Binlog_commits	1536740
Binlog_group_commits	1477747
Binlog_group_commit_trigger_count	0
Binlog_group_commit_trigger_lock_wait	0
Binlog_group_commit_trigger_timeout	0
Binlog_snapshot_file	mysql-bin.000067
Binlog_snapshot_position	627873716
Binlog_bytes_written	0
Binlog_cache_disk_use	164652
Binlog_cache_use	1536657
Binlog_stmt_cache_disk_use	0
Binlog_stmt_cache_use	0
Busy_time	0.000000
Bytes_received	296
Bytes_sent	31931
Column_compressions	0
Column_decompressions	0
Com_admin_commands	0
Com_alter_db	0
Com_alter_db_upgrade	0
Com_alter_event	0
Com_alter_function	0
Com_alter_procedure	0
Com_alter_server	0
Com_alter_sequence	0
Com_alter_table	0
Com_alter_tablespace	0
Com_alter_user	0
Com_analyze	0
Com_assign_to_keycache	0
Com_begin	0
Com_binlog	0
Com_call_procedure	0
Com_change_db	1
Com_change_master	0
Com_check	0
Com_checksum	0
Com_commit	0
Com_compound_sql	0
Com_create_db	0
Com_create_event	0
Com_create_function	0
Com_create_index	0
Com_create_package	0
Com_create_package_body	0
Com_create_procedure	0
Com_create_role	0
Com_create_sequence	0
Com_create_server	0
Com_create_table	0
Com_create_temporary_table	0
Com_create_trigger	0
Com_create_udf	0
Com_create_user	0
Com_create_view	0
Com_dealloc_sql	0
Com_delete	0
Com_delete_multi	0
Com_do	0
Com_drop_db	0
Com_drop_event	0
Com_drop_function	0
Com_drop_index	0
Com_drop_procedure	0
Com_drop_package	0
Com_drop_package_body	0
Com_drop_role	0
Com_drop_server	0
Com_drop_sequence	0
Com_drop_table	0
Com_drop_temporary_table	0
Com_drop_trigger	0
Com_drop_user	0
Com_drop_view	0
Com_empty_query	0
Com_execute_immediate	0
Com_execute_sql	0
Com_flush	0
Com_get_diagnostics	0
Com_grant	0
Com_grant_role	0
Com_ha_close	0
Com_ha_open	0
Com_ha_read	0
Com_help	0
Com_insert	0
Com_insert_select	0
Com_install_plugin	0
Com_kill	0
Com_load	0
Com_lock_tables	0
Com_multi	0
Com_optimize	0
Com_preload_keys	0
Com_prepare_sql	0
Com_purge	0
Com_purge_before_date	0
Com_release_savepoint	0
Com_rename_table	0
Com_rename_user	0
Com_repair	0
Com_replace	0
Com_replace_select	0
Com_reset	0
Com_resignal	0
Com_revoke	0
Com_revoke_all	0
Com_revoke_role	0
Com_rollback	0
Com_rollback_to_savepoint	0
Com_savepoint	0
Com_select	0
Com_set_option	2
Com_show_authors	0
Com_show_binlog_events	0
Com_show_binlogs	0
Com_show_charsets	0
Com_show_collations	0
Com_show_contributors	0
Com_show_create_db	0
Com_show_create_event	0
Com_show_create_func	0
Com_show_create_package	0
Com_show_create_package_body	0
Com_show_create_proc	0
Com_show_create_table	0
Com_show_create_trigger	0
Com_show_create_user	0
Com_show_databases	0
Com_show_engine_logs	0
Com_show_engine_mutex	0
Com_show_engine_status	0
Com_show_errors	0
Com_show_events	0
Com_show_explain	0
Com_show_fields	0
Com_show_function_status	0
Com_show_generic	0
Com_show_grants	0
Com_show_keys	0
Com_show_master_status	0
Com_show_open_tables	0
Com_show_package_status	0
Com_show_package_body_status	0
Com_show_plugins	0
Com_show_privileges	0
Com_show_procedure_status	0
Com_show_processlist	0
Com_show_profile	0
Com_show_profiles	0
Com_show_relaylog_events	0
Com_show_slave_hosts	0
Com_show_slave_status	0
Com_show_status	3
Com_show_storage_engines	0
Com_show_table_status	0
Com_show_tables	0
Com_show_triggers	0
Com_show_variables	0
Com_show_warnings	0
Com_shutdown	0
Com_signal	0
Com_start_all_slaves	0
Com_start_slave	0
Com_stmt_close	0
Com_stmt_execute	0
Com_stmt_fetch	0
Com_stmt_prepare	0
Com_stmt_reprepare	0
Com_stmt_reset	0
Com_stmt_send_long_data	0
Com_stop_all_slaves	0
Com_stop_slave	0
Com_truncate	0
Com_uninstall_plugin	0
Com_unlock_tables	0
Com_update	0
Com_update_multi	0
Com_xa_commit	0
Com_xa_end	0
Com_xa_prepare	0
Com_xa_recover	0
Com_xa_rollback	0
Com_xa_start	0
Compression	OFF
Connection_errors_accept	0
Connection_errors_internal	0
Connection_errors_max_connections	0
Connection_errors_peer_address	0
Connection_errors_select	0
Connection_errors_tcpwrap	0
Connections	1733401
Cpu_time	0.000000
Created_tmp_disk_tables	0
Created_tmp_files	43617
Created_tmp_tables	0
Delayed_errors	0
Delayed_insert_threads	0
Delayed_writes	0
Delete_scan	0
Empty_queries	0
Executed_events	0
Executed_triggers	0
Feature_check_constraint	0
Feature_custom_aggregate_functions	0
Feature_delay_key_write	0
Feature_dynamic_columns	0
Feature_fulltext	0
Feature_gis	0
Feature_invisible_columns	0
Feature_json	0
Feature_locale	0
Feature_subquery	0
Feature_system_versioning	0
Feature_timezone	0
Feature_trigger	0
Feature_window_functions	0
Feature_xml	0
Flush_commands	3
Handler_commit	0
Handler_delete	0
Handler_discover	0
Handler_external_lock	0
Handler_icp_attempts	0
Handler_icp_match	0
Handler_mrr_init	0
Handler_mrr_key_refills	0
Handler_mrr_rowid_refills	0
Handler_prepare	0
Handler_read_first	0
Handler_read_key	0
Handler_read_last	0
Handler_read_next	0
Handler_read_prev	0
Handler_read_retry	0
Handler_read_rnd	0
Handler_read_rnd_deleted	0
Handler_read_rnd_next	0
Handler_rollback	0
Handler_savepoint	0
Handler_savepoint_rollback	0
Handler_tmp_delete	0
Handler_tmp_update	0
Handler_tmp_write	0
Handler_update	0
Handler_write	0
Innodb_buffer_pool_dump_status	
Innodb_buffer_pool_load_status	Buffer pool(s) load completed at 191119 20:20:57
Innodb_buffer_pool_resize_status	Completed resizing buffer pool at 200101  7:28:30.
Innodb_buffer_pool_load_incomplete	OFF
Innodb_buffer_pool_pages_data	2611438
Innodb_buffer_pool_bytes_data	42785800192
Innodb_buffer_pool_pages_dirty	0
Innodb_buffer_pool_bytes_dirty	0
Innodb_buffer_pool_pages_flushed	16451218
Innodb_buffer_pool_pages_free	8192
Innodb_buffer_pool_pages_misc	1810
Innodb_buffer_pool_pages_total	2621440
Innodb_buffer_pool_read_ahead_rnd	0
Innodb_buffer_pool_read_ahead	1086
Innodb_buffer_pool_read_ahead_evicted	0
Innodb_buffer_pool_read_requests	2725538298071
Innodb_buffer_pool_reads	12654
Innodb_buffer_pool_wait_free	0
Innodb_buffer_pool_write_requests	994311297
Innodb_data_fsyncs	14554408
Innodb_data_pending_fsyncs	0
Innodb_data_pending_reads	0
Innodb_data_pending_writes	0
Innodb_data_read	230214144
Innodb_data_reads	15147
Innodb_data_writes	23905585
Innodb_data_written	618834607104
Innodb_dblwr_pages_written	16467868
Innodb_dblwr_writes	3500466
Innodb_log_waits	0
Innodb_log_write_requests	204240289
Innodb_log_writes	3102792
Innodb_os_log_fsyncs	3921490
Innodb_os_log_pending_fsyncs	0
Innodb_os_log_pending_writes	0
Innodb_os_log_written	78789020672
Innodb_page_size	16384
Innodb_pages_created	3600841
Innodb_pages_read	14046
Innodb_pages0_read	5
Innodb_pages_written	16467999
Innodb_row_lock_current_waits	0
Innodb_row_lock_time	360268
Innodb_row_lock_time_avg	2106
Innodb_row_lock_time_max	17025
Innodb_row_lock_waits	171
Innodb_rows_deleted	606
Innodb_rows_inserted	163448725
Innodb_rows_read	1189697644895
Innodb_rows_updated	2926789
Innodb_system_rows_deleted	0
Innodb_system_rows_inserted	0
Innodb_system_rows_read	4624
Innodb_system_rows_updated	0
Innodb_num_open_files	164
Innodb_truncated_status_writes	0
Innodb_available_undo_logs	128
Innodb_undo_truncations	0
Innodb_page_compression_saved	0
Innodb_num_index_pages_written	0
Innodb_num_non_index_pages_written	0
Innodb_num_pages_page_compressed	0
Innodb_num_page_compressed_trim_op	0
Innodb_num_pages_page_decompressed	0
Innodb_num_pages_page_compression_error	0
Innodb_num_pages_encrypted	0
Innodb_num_pages_decrypted	0
Innodb_have_lz4	OFF
Innodb_have_lzo	OFF
Innodb_have_lzma	OFF
Innodb_have_bzip2	OFF
Innodb_have_snappy	OFF
Innodb_have_punch_hole	ON
Innodb_defragment_compression_failures	0
Innodb_defragment_failures	0
Innodb_defragment_count	0
Innodb_instant_alter_column	0
Innodb_onlineddl_rowlog_rows	0
Innodb_onlineddl_rowlog_pct_used	0
Innodb_onlineddl_pct_progress	0
Innodb_secondary_index_triggered_cluster_reads	872469642844
Innodb_secondary_index_triggered_cluster_reads_avoided	0
Innodb_encryption_rotation_pages_read_from_cache	0
Innodb_encryption_rotation_pages_read_from_disk	0
Innodb_encryption_rotation_pages_modified	0
Innodb_encryption_rotation_pages_flushed	0
Innodb_encryption_rotation_estimated_iops	0
Innodb_encryption_key_rotation_list_length	0
Innodb_encryption_n_merge_blocks_encrypted	0
Innodb_encryption_n_merge_blocks_decrypted	0
Innodb_encryption_n_rowlog_blocks_encrypted	0
Innodb_encryption_n_rowlog_blocks_decrypted	0
Innodb_encryption_n_temp_blocks_encrypted	0
Innodb_encryption_n_temp_blocks_decrypted	0
Innodb_scrub_background_page_reorganizations	0
Innodb_scrub_background_page_splits	0
Innodb_scrub_background_page_split_failures_underflow	0
Innodb_scrub_background_page_split_failures_out_of_filespace	0
Innodb_scrub_background_page_split_failures_missing_index	0
Innodb_scrub_background_page_split_failures_unknown	0
Innodb_scrub_log	0
Innodb_encryption_num_key_requests	0
Key_blocks_not_flushed	0
Key_blocks_unused	26783
Key_blocks_used	2
Key_blocks_warm	0
Key_read_requests	16
Key_reads	2
Key_write_requests	0
Key_writes	0
Last_query_cost	0.000000
Master_gtid_wait_count	0
Master_gtid_wait_time	0
Master_gtid_wait_timeouts	0
Max_statement_time_exceeded	0
Max_used_connections	115
Memory_used	77936
Memory_used_initial	317773312
Not_flushed_delayed_rows	0
Open_files	66
Open_streams	0
Open_table_definitions	231
Open_tables	375
Opened_files	130898
Opened_plugin_libraries	0
Opened_table_definitions	0
Opened_tables	0
Opened_views	0
Performance_schema_accounts_lost	0
Performance_schema_cond_classes_lost	0
Performance_schema_cond_instances_lost	0
Performance_schema_digest_lost	0
Performance_schema_file_classes_lost	0
Performance_schema_file_handles_lost	0
Performance_schema_file_instances_lost	0
Performance_schema_hosts_lost	0
Performance_schema_locker_lost	0
Performance_schema_mutex_classes_lost	0
Performance_schema_mutex_instances_lost	0
Performance_schema_rwlock_classes_lost	0
Performance_schema_rwlock_instances_lost	0
Performance_schema_session_connect_attrs_lost	0
Performance_schema_socket_classes_lost	0
Performance_schema_socket_instances_lost	0
Performance_schema_stage_classes_lost	0
Performance_schema_statement_classes_lost	0
Performance_schema_table_handles_lost	0
Performance_schema_table_instances_lost	0
Performance_schema_thread_classes_lost	0
Performance_schema_thread_instances_lost	0
Performance_schema_users_lost	0
Prepared_stmt_count	0
Qcache_free_blocks	1575
Qcache_free_memory	24207272
Qcache_hits	3302189
Qcache_inserts	3656612
Qcache_lowmem_prunes	57740
Qcache_not_cached	6474079
Qcache_queries_in_cache	2389
Qcache_total_blocks	6663
Queries	78435141
Questions	6
Rows_read	0
Rows_sent	0
Rows_tmp_read	1072
Rpl_semi_sync_master_clients	0
Rpl_semi_sync_master_get_ack	0
Rpl_semi_sync_master_net_avg_wait_time	0
Rpl_semi_sync_master_net_wait_time	0
Rpl_semi_sync_master_net_waits	0
Rpl_semi_sync_master_no_times	0
Rpl_semi_sync_master_no_tx	0
Rpl_semi_sync_master_request_ack	0
Rpl_semi_sync_master_status	OFF
Rpl_semi_sync_master_timefunc_failures	0
Rpl_semi_sync_master_tx_avg_wait_time	0
Rpl_semi_sync_master_tx_wait_time	0
Rpl_semi_sync_master_tx_waits	0
Rpl_semi_sync_master_wait_pos_backtraverse	0
Rpl_semi_sync_master_wait_sessions	0
Rpl_semi_sync_master_yes_tx	0
Rpl_semi_sync_slave_send_ack	0
Rpl_semi_sync_slave_status	OFF
Rpl_status	AUTH_MASTER
Rpl_transactions_multi_engine	0
Select_full_join	0
Select_full_range_join	0
Select_range	0
Select_range_check	0
Select_scan	0
Slave_connections	0
Slave_heartbeat_period	0.000
Slave_open_temp_tables	0
Slave_received_heartbeats	0
Slave_retried_transactions	0
Slave_running	OFF
Slave_skipped_errors	0
Slaves_connected	1
Slaves_running	0
Slow_launch_threads	0
Slow_queries	0
Sort_merge_passes	0
Sort_priority_queue_sorts	0
Sort_range	0
Sort_rows	0
Sort_scan	0
Ssl_accept_renegotiates	0
Ssl_accepts	0
Ssl_callback_cache_hits	0
Ssl_cipher	
Ssl_cipher_list	
Ssl_client_connects	0
Ssl_connect_renegotiates	0
Ssl_ctx_verify_depth	0
Ssl_ctx_verify_mode	0
Ssl_default_timeout	0
Ssl_finished_accepts	0
Ssl_finished_connects	0
Ssl_server_not_after	
Ssl_server_not_before	
Ssl_session_cache_hits	0
Ssl_session_cache_misses	0
Ssl_session_cache_mode	NONE
Ssl_session_cache_overflows	0
Ssl_session_cache_size	0
Ssl_session_cache_timeouts	0
Ssl_sessions_reused	0
Ssl_used_session_cache_entries	0
Ssl_verify_depth	0
Ssl_verify_mode	0
Ssl_version	
Subquery_cache_hit	32386249
Subquery_cache_miss	4612667
Syncs	1474160
Table_locks_immediate	1044
Table_locks_waited	0
Table_open_cache_active_instances	1
Table_open_cache_hits	0
Table_open_cache_misses	0
Table_open_cache_overflows	0
Tc_log_max_pages_used	0
Tc_log_page_size	0
Tc_log_page_waits	0
Threadpool_idle_threads	0
Threadpool_threads	0
Threads_cached	2
Threads_connected	35
Threads_created	20955
Threads_running	1
Transactions_gtid_foreign_engine	0
Transactions_multi_engine	0
Update_scan	0
Uptime	3671393
Uptime_since_flush_status	3671393
wsrep_applier_thread_count	0
wsrep_cluster_conf_id	18446744073709551615
wsrep_cluster_size	0
wsrep_cluster_state_uuid	
wsrep_cluster_status	Disconnected
wsrep_connected	OFF
wsrep_local_bf_aborts	0
wsrep_local_index	18446744073709551615
wsrep_provider_name	
wsrep_provider_vendor	
wsrep_provider_version	
wsrep_ready	OFF
wsrep_rollbacker_thread_count	0
wsrep_thread_count	0`

**Comment by juan131** [comment]
Hi @zhuochengs 

As @javsalgar suggested before, I'd open a different thread to discuss the performance issues with memory/cpu since it's confusing for users that come to this issue for the original issue with `mariabackup ` tool. Thanks in advance.

**Comment by zhuochengs** [comment]
Hi @juan131 , thanks very much!

**Comment by zhuochengs** [comment]
> Hi @zhuochengs,
> 
> I tried now to create a backup from a remote machine and also got issues. We will further investigate this issue and update it once we have more information.
> 
> Thanks for reporting!

hello,  how about it now?

**Comment by juan131** [comment]
Sure! Go ahead and open a new issue where we can discuss the performance details @zhuochengs

**Comment by carrodher** [comment]
In order to unify the approaches followed in Bitnami containers and Bitnami charts, we are moving some issues in `bitnami/bitnami-docker-<container>` repositories to `bitnami/containers`. Please follow [bitnami/containers](https://github.com/bitnami/containers) to keep you updated about the latest bitnami images.

If this issue is still applicable, please feel free to recreate it at https://github.com/bitnami/containers/issues/new/choose

More information here: https://blog.bitnami.com/2022/07/new-source-of-truth-bitnami-containers.html
