### ISSUE TITLE
Slave delayed update

### ISSUE THREAD

**Issue by eo0815** [bitnami/bitnami-docker-mariadb#215]
hi guys,

just want to ask if there is a environment variable I can use on my mariadb-master to delay the update on the slave database for at least an hour.

tried to add -MASTER_DELAY=300 variable for testing but somehow the database master container is not starting.

**Comment by marcosbc** [comment]
@eo0815 Do you mean something such as this? https://dev.mysql.com/doc/refman/8.0/en/replication-delayed.html

If so, the container doesn't currently support it via environment variables, but you may be able to enable it by mounting a SQL file at `/docker-entrypoint-initdb.d/` for the master node, which executes the required SQL commands.

**Comment by eo0815** [comment]
Thanks @marcosbc !!
