### ISSUE TITLE
Initial database doesn't get given Collation

### ISSUE THREAD

**Issue by adibbuchho** [bitnami/bitnami-docker-mariadb#217]
**Description**

I'm using bitnami/mariadb:10.1 and starting the container together with an initial database and change default collation to utf8_bin. I'm expecting, that the initial database will get this new collation, but this doesn't seem to happen. My initial database still have utf8_general_ci.

**Steps to reproduce the issue:**

1. docker-compose.yaml with initial databse and default collation via MARIADB_EXTRA_FLAGS: --collation-server=utf8_bin or via MARIADB_COLLATION: utf8_bin
2. start container with docker-compose up -d
3. check collation of initial database

**Describe the results you received:**

When I give utf8_bin as default collation (described in steps to reproduce) and an initial database the database have collation utf8_general_ci

**Describe the results you expected:**

When I change any server configuration during start up (like collation in this case) I would expect that the initial database will be created based on these changed configurations. So in my case I would expect a database with collation utf8_bin

**Additional information you deem important (e.g. issue happens only occasionally):**

nothing

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b7f0
 Built:             Wed Mar 11 01:25:58 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b7f0
  Built:            Wed Mar 11 01:24:30 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 7
  Running: 5
  Paused: 0
  Stopped: 2
 Images: 92
 Server Version: 19.03.8
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-99-generic
 Operating System: Linux Mint 19
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 7.79GiB
 Name: bjoern-VirtualBox-Mint
 ID: BV6E:YZN5:L5SC:EJBU:5BQC:3YKI:62TY:CUBC:N3QM:X4XJ:OAHL:J36G
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.20.0, build ca8d3c6
docker-py version: 3.1.3
CPython version: 3.6.4
OpenSSL version: OpenSSL 1.0.1t  3 May 2016

```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
Docker runs on Linux Mint in VirtualBox (6.1.6 r137129):
```
Distributor ID:	LinuxMint
Description:	Linux Mint 19 Tara
Release:	19
Codename:	tara
```

**Comment by javsalgar** [comment]
Hi,

Just a quick note to let you know that I was able to reproduce the issue

```
MariaDB [(none)]> SELECT * FROM INFORMATION_SCHEMA.SCHEMATA;
+--------------+--------------------+----------------------------+------------------------+----------+
| CATALOG_NAME | SCHEMA_NAME        | DEFAULT_CHARACTER_SET_NAME | DEFAULT_COLLATION_NAME | SQL_PATH |
+--------------+--------------------+----------------------------+------------------------+----------+
| def          | information_schema | utf8                       | utf8_general_ci        | NULL     |
| def          | test               | latin1                     | latin1_swedish_ci      | NULL     |
| def          | performance_schema | utf8                       | utf8_general_ci        | NULL     |
| def          | mysql              | utf8                       | utf8_bin               | NULL     |
+--------------+--------------------+----------------------------+------------------------+----------+
```

When I use the mysql client  and try to create a new database, it uses the proper collation. While we find out the cause of the issue, you may use the `/docker-entrypoint.initdb` feature with a custom initialization script for the database you require. 

Thanks for reporting

**Comment by Kovah** [comment]
I have a similar issue, only with the difference that when setting `MARIADB_COLLATION=utf8_bin`, the database won't even start. The container exits with code 1 after the `Installing database` step, no matter which collation I set.
When I use `MARIADB_EXTRA_FLAGS=--collation-server=utf8mb4_bin`, the container reaches the `Starting mariadb in background` step, but does not proceeds after this. Hangs until I force stop it.

**Comment by javsalgar** [comment]
Hi,

Thanks for the input! Did you try using a custom init script that would change the collation in the database? Then start mariadb with the default settings. Would that work for your use case?

**Comment by Kovah** [comment]
I haven't tried yet, but would like to minimize to number of needed files to run any containers.

**Comment by javsalgar** [comment]
Yes, there's a task in our backlog, which we still didn't have the time to work on. It would be just to confirm that there's a workaround for the time being.

**Comment by carrodher** [comment]
In order to unify the approaches followed in Bitnami containers and Bitnami charts, we are moving some issues in `bitnami/bitnami-docker-<container>` repositories to `bitnami/containers`. Please follow [bitnami/containers](https://github.com/bitnami/containers) to keep you updated about the latest bitnami images.

If this issue is still applicable, please feel free to recreate it at https://github.com/bitnami/containers/issues/new/choose

More information here: https://blog.bitnami.com/2022/07/new-source-of-truth-bitnami-containers.html
