### ISSUE TITLE
MariaDB wont allow connections after custom dockerfile

### ISSUE THREAD

**Issue by ToNotNo1** [bitnami/bitnami-docker-mariadb#218]
**Description**

Attempting to connect to MariaDB with PHP fails throwing this error: Connection failed: No such file or directory

My dockerfile: https://pastebin.com/raw/hjT6e5dE
My PHP file trying to connect to DB: https://pastebin.com/raw/MM0fgQQZ
My lighttpd config file: https://pastebin.com/raw/SKXVBHw0

I am assuming this may be a problem with MariaDB hence why I am askingbut MariaDB seems to be starting up and well so idk what could be the problem. It also seems like I have installed all php modules to connect to MariaDB

**Steps to reproduce the issue:**

Build container (builds successfully) then try to visit test.php with the PHP code

**Describe the results you received:**

Page loaded with:  Connection failed: No such file or directory

**Describe the results you expected:**

To see connection to db successfully

**Additional information you deem important (e.g. issue happens only occasionally):**

Nope, nothing else. You can build this container and it wont work

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b7f0
 Built:             Wed Mar 11 01:25:46 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b7f0
  Built:            Wed Mar 11 01:24:19 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

```

- Output of `docker info`: 

https://pastebin.com/RgPxLxDA

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

Compiling on virtualbox

**Comment by ToNotNo1** [comment]
sorry for pastebin links but i need to do that to copy really big files or from cmd. its a weird PC so im taking shortcuts by uploading it to pastebin

**Comment by andresbono** [comment]
Hi @ToNotNo1, MariaDB is not running in the container because of the way you have modified the `CMD` in the Dockerfile. You can check that by executing `ps aux` in the containers. You won't see any database process running.

I'd say that `No such file or directory` refers to the database socket not being found. When you use `localhost` as servername, mysqli extension understands that it should connect through socket. If you change it to `127.0.0.1`, you will see that the error is different:

```
PHP Warning:  mysqli::__construct(): (HY000/2002): Connection refused in /var/www/index.php on line 7
```

I would recommend you to split both services (webserver and database) in two different containers and use docker-compose to launch them.

**Comment by ToNotNo1** [comment]
@andresbono Ohh hi, i though if i inherit the container, it would start mariadb. Anyway i really cant split them, i want to have everything in one container so i could probably tackle this by writing an sh script that runs them both.

Where is MariaDB located and how would I start it?

**Comment by ToNotNo1** [comment]
@andresbono Thats a thing actually, could I just start both instead? so an bash script that starts lighttpd then mariadb (using docker-compose or splitting them into two is not an option for me, otherwise it would be first choice)

**Comment by andresbono** [comment]
@ToNotNo1, To initialize and start Mariadb, the Dockerfile does the following:

https://github.com/bitnami/bitnami-docker-mariadb/blob/f6a3d37191bb957b716fbe2dd7fb22195657054a/10.4/debian-10/Dockerfile#L27-L28

You can try to execute that in a custom script that also initializes the webserver:

```
/opt/bitnami/scripts/mariadb/entrypoint.sh /opt/bitnami/scripts/mariadb/run.sh
```
