### ISSUE TITLE
QUESTION: how to enter mariadb client for current container

### ISSUE THREAD

**Issue by alexanderadam** [bitnami/bitnami-docker-mariadb#219]
Not an issue but rather a question:

I'm trying to access client shell for the same instance but I'm obviously missing something:

```bash
docker exec -it container_name mariadb
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/opt/bitnami/mariadb/tmp/mysql.sock' (2)
```

Any advice?

**Comment by andresbono** [comment]
Hi @alexanderadam, if the container is running like this:

```
docker run --name container_name -e ALLOW_EMPTY_PASSWORD=yes bitnami/mariadb:latest
```

You should be able to connect to the database by executing:

```
docker exec -it container_name mysql -u root
```

**Comment by alexanderadam** [comment]
Thank you. I guess it was some other error in my case…
