### ISSUE TITLE
Add support for arm64

### ISSUE THREAD

**Issue by ssmall** [bitnami/bitnami-docker-mariadb#221]
**Description**

I would like to install the bitnami/mariadb Helm chart on a Kubernetes cluster in which all the nodes are arm64. Unfortunately, it looks like this image only builds for amd64. I tried [forking and customizing the Dockerfile](https://github.com/ssmall/bitnami-docker-mariadb/pull/1) to support a multiarch build using `dockerx`,  but it seems like a non-trivial change.

**Steps to reproduce the issue:**

1. `docker run --name mariadb -e ALLOW_EMPTY_PASSWORD=yes bitnami/mariadb:latest` on an arm64 machine with Docker installed.

**Describe the results you received:**

```
standard_init_linux.go:211: exec user process caused "exec format error"
```

**Describe the results you expected:**

Container runs normally

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
Client:
 Version:           19.03.11
 API version:       1.40
 Go version:        go1.13.12
 Git commit:        dd360c7
 Built:             Mon Jun  8 20:34:15 2020
 OS/Arch:           linux/arm64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.11
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.12
  Git commit:       77e06fd
  Built:            Mon Jun  8 20:35:58 2020
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 1
  Running: 0
  Paused: 0
  Stopped: 1
 Images: 1
 Server Version: 19.03.11
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version:
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.3.0-1028-raspi2
 Operating System: Ubuntu Core 16
 OSType: linux
 Architecture: aarch64
 CPUs: 4
 Total Memory: 906.2MiB
 Name: raspi
 ID: TVJ3:EBJ7:DIKR:MV7K:2C3I:YPN7:NHCU:YTT7:JLUR:OD7P:OJ3L:EQWW
 Docker Root Dir: /var/snap/docker/common/var-lib-docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

- Output of `docker-compose version` (if applicable):

N/A

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

N/A

**Comment by carrodher** [comment]
Hi, we would really work on supporting ARM but unfortunately, we are a small team right now and we have a limited bandwidth to work on this. That would require major changes in our pipeline to support building & testing ARM containers.

We would be also happy to integrate any changes in the Helm Chart (e.g. parameters) to make it compatible with any other MariaDB ARM container image, in this way you can use the Bitnami Helm chart but providing an external ARM image.

**Comment by ssmall** [comment]
I've created https://github.com/bitnami/charts/issues/3393 to request support for the official mariadb docker image.

**Comment by ssmall** [comment]
For what it's worth, I would be happy to contribute to creating an arm64 version of this container image. However, because the scripts such as https://github.com/bitnami/bitnami-docker-mariadb/blob/master/10.5/debian-10/prebuildfs/opt/bitnami/scripts/libcomponent.sh download arch-specific tarballs from https://downloads.bitnami.com/files/stacksmith, I am unable to help without access to that server.

**Comment by carrodher** [comment]
Thanks for creating the issue in the chart repo. Regarding the image itself there are needed several changes in our internal system and code in order to support this arch. Let's see if there is a simple way to support official image in the chart, PR are welcome just in case you have something working on your side. Thanks again!

**Comment by shaneutt** [comment]
> Thanks for creating the issue in the chart repo. Regarding the image itself there are needed several changes in our internal system and code in order to support this arch. Let's see if there is a simple way to support official image in the chart, PR are welcome just in case you have something working on your side. Thanks again!

Are you able to enumerate some of the things that need changes for those who may be interested in contribution? Is there a project board somewhere tracking these?

**Comment by carrodher** [comment]
Hi, I am sorry but the required changes for supporting the arm architecture in the Bitnami images need to be implemented in different internal tools and systems that are not hosted as part of the public code in the Bitnami GitHub organization.

Although it is something that is on our radar and we really would like to work on, we are not dedicating time for that right now due to some major changes are required and we are a small team with different priorities.

On the other hand, if you are using the chart we can help to add support for arm images like https://hub.docker.com/_/mariadb?tab=tags&page=1 in the bitnami/mariadb chart, on this way you can use the chart with an arm image (although not provided by Bitnami) (see https://github.com/bitnami/charts/issues/3393)
