### ISSUE TITLE
From Helm chart how to enable SSL between mariadb server and client

### ISSUE THREAD

**Issue by vu2hsj** [bitnami/bitnami-docker-mariadb#223]
We are able to successfully deploy mariadb server both master only (or) master-slave that is default deployment. But there is no option from helm chart to add SSL certificates to make mariadb server SSL enabled. 
Does Mariadb helm support this feature?

As we are able to SSL enable with mariadb on installing in VM we are trying to replicate the same.

**Comment by marcosbc** [comment]
Hi @vu2hsj, currently the chart does support [`extraEnvVars`](https://github.com/bitnami/charts/blob/master/bitnami/mariadb/values.yaml#L278) which you could use to specify for MariaDB TLS options via [`MARIADB_EXTRA_FLAGS`](https://github.com/bitnami/bitnami-docker-mariadb#passing-extra-command-line-flags-to-mysqld-startup).

However (and unfortunately), the chart currently does not support `extraVolumeMounts` yet. You can see an example [here](https://github.com/bitnami/charts/blob/master/bitnami/wordpress/values.yaml#L165).

Feel free to try to make the changes on your side, PRs are welcome and we're glad to review any external contributions.
