### ISSUE TITLE
Problems modifying mariadb password/database names

### ISSUE THREAD

**Issue by Choogster1** [bitnami/bitnami-docker-mariadb#224]
This is probably an entirely simple solution but I've not managed to figure it out yet. 

I want to modify the database username, password etc in Mariadb and then get Moodle to use this to login (I'm also using a Moodle Bitnami container). I've successfully changed the database name itself, but the username and password are causing problems.

I've changed the database name and table name, but moodle refuses to login with the log showing Access denied 'moodle'@'localhost' (Using password: No) and also Access denied 'bn_moodle'@'localhost' (Using password: Yes)

I've tried changing permissions by logging into the container directly with no luck. If anybody can point me at a tutorial or in the right direction on how to get this working, it would be much appreciated. There doesn't seem to be any documentation I can find anywhere (or examples) showing when a user has changed the username and password successfully.

**Comment by marcosbc** [comment]
Hi @Choogster1, you should be setting the following environment options for the MariaDB container:

* MARIADB_DATABASE
* MARIADB_PASSWORD

And then for the Moodle container:

* MOODLE_DATABASE_NAME
* MOODLE_DATABASE_PASSWORD

If you continue to find issues, could you share a `docker-compose.yml` where to reproduce this issue?

**Comment by Choogster1** [comment]
Actually that's what I've been doing. 

The compose file (for Docker Swarm):

Mariadb:
     - MARIADB_USER=moodle
     - MARIADB_DATABASE=moodle_database
     - MARIADB_PASSWORD=password

Moodle:
     - MOODLE_DATABASE_USER=moodle
     - MOODLE_DATABASE_NAME=moodle_database
     - MOODLE_DATABASE_PASSWORD=password

The actual file is too long to include here as it includes Traefik proxy and others.

The log for Mariadb is this:

2020-08-31  8:33:39 9 [Warning] Access denied for user 'moodle'@'localhost' (using password: NO)
2020-08-31  8:33:40 10 [Warning] Access denied for user 'bn_moodle'@'10.0.2.224' (using password: YES)
2020-08-31  8:33:45 11 [Warning] Access denied for user 'bn_moodle'@'10.0.2.224' (using password: YES)
2020-08-31  8:33:50 12 [Warning] Access denied for user 'bn_moodle'@'10.0.2.224' (using password: YES)
2020-08-31  8:33:55 13 [Warning] Access denied for user 'bn_moodle'@'10.0.2.224' (using password: YES)

I tried changing the user permissions within the database but still no success, so help would be appreciated.

**Comment by Choogster1** [comment]
I'm using bitnami/mariadb:10.4 and bitnami/moodle:3.9.1

**Comment by joancafom** [comment]
Hi @Choogster1 ,

I have tried replicating your problem but I did not face any problems. I might be wrong, but maybe the incorrect login attempts you mentioned to see are caused due to previously initialized volumes. Can you please check that? There are the steps I have followed on a brand new deployment (clean volumes, first initialization) just in case it helps:

1. Modify `docker-compose.yml` with your custom values:
```console
$ cat docker-compose.yml
version: '2'
services:
  mariadb:
    image: 'docker.io/bitnami/mariadb:10.3-debian-10'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=user_alpha
      - MARIADB_PASSWORD=pass_alpha
      - MARIADB_DATABASE=sample_alpha
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  moodle:
    image: 'docker.io/bitnami/moodle:3-debian-10'
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=user_alpha
      - MOODLE_DATABASE_PASSWORD=pass_alpha
      - MOODLE_DATABASE_NAME=sample_alpha
    volumes:
      - 'moodle_data:/bitnami/moodle'
      - 'moodledata_data:/bitnami/moodledata'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  moodle_data:
    driver: local
  moodledata_data:
    driver: local
```

2. Start the containers using docker-compose as normal:

```console
$ docker-compose up
...
mariadb_1  | 2020-09-01  6:57:51 0 [Note] Reading of all Master_info entries succeeded
mariadb_1  | 2020-09-01  6:57:51 0 [Note] Added new Master_info '' to hash table
mariadb_1  | 2020-09-01  6:57:51 0 [Note] /opt/bitnami/mariadb/sbin/mysqld: ready for connections.
mariadb_1  | Version: '10.3.24-MariaDB'  socket: '/opt/bitnami/mariadb/tmp/mysql.sock'  port: 3306  Source distribution
moodle_1   | moodle 06:57:55.15 INFO  ==> Running Moodle install script
moodle_1   | moodle 06:59:50.49 INFO  ==> Persisting Moodle installation
moodle_1   | moodle 07:00:12.01 INFO  ==> ** Moodle setup finished! **
moodle_1   |
moodle_1   | /opt/bitnami/scripts/moodle/run.sh: line 28: am_i_root: command not found
moodle_1   | moodle 07:00:12.02 WARN  ==> Cron will not be started because of running as a non-root user
moodle_1   | moodle 07:00:12.03 INFO  ==> ** Starting Apache **
moodle_1   | [Tue Sep 01 07:00:12.359091 2020] [ssl:warn] [pid 1] AH01909: www.example.com:8443:0 server certificate does NOT include an ID which matches the server name
moodle_1   | [Tue Sep 01 07:00:12.359516 2020] [ssl:warn] [pid 1] AH01909: www.example.com:8443:0 server certificate does NOT include an ID which matches the server name
moodle_1   | [Tue Sep 01 07:00:12.403635 2020] [ssl:warn] [pid 1] AH01909: www.example.com:8443:0 server certificate does NOT include an ID which matches the server name
moodle_1   | [Tue Sep 01 07:00:12.403970 2020] [ssl:warn] [pid 1] AH01909: www.example.com:8443:0 server certificate does NOT include an ID which matches the server name
moodle_1   | [Tue Sep 01 07:00:12.542783 2020] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.46 (Unix) OpenSSL/1.1.1d PHP/7.3.21 configured -- resuming normal operations
moodle_1   | [Tue Sep 01 07:00:12.542834 2020] [core:notice] [pid 1] AH00094: Command line: '/opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.conf -D FOREGROUND'

moodle_1   | 192.168.128.1 - - [01/Sep/2020:07:14:10 +0000] "GET / HTTP/1.1" 200 27968
```

3. Verify that schema exists in the desired database
```console
$ docker exec -it bitnami-docker-moodle_mariadb_1 mysql -u user_alpha -D sample_alpha -p
Enter password:
...
MariaDB [sample_alpha]>

$ SHOW TABLES;
...
| mdl_workshopform_comments        |
| mdl_workshopform_numerrors       |
| mdl_workshopform_numerrors_map   |
| mdl_workshopform_rubric          |
| mdl_workshopform_rubric_config   |
| mdl_workshopform_rubric_levels   |
+----------------------------------+
428 rows in set (0.002 sec)
```

**Comment by Choogster1** [comment]
Thanks for your suggestions. I've actually figured out my error (which was common sense....) and it's working now.
