### ISSUE TITLE
 IBM Cloud Wordpress Deployment : MariaDB Persistance Using NFS Permission Issue WordPress

### ISSUE THREAD

**Issue by kenlim1228** [bitnami/bitnami-docker-mariadb#228]
REF: [https://community.bitnami.com/t/ibm-cloud-wordpress-deployment-mariadb-persistance-using-nfs-permission-issue/87967](url)

Hi, I am having issue with Wordpress deployment on IBM Cloud, I opened the case on bitnami, but they told me to reopen it here.

- Version 5.5.0
- Cloud Image on IBM Cloud
- We modified the config for persistence (both file and database) using NFS storage instead of block storage: storage class set to ibmc-file-custom which basically is an NFS storage
- We get an issue with permission it creates the directory for mariadb storage:

> mariadb 21:30:57.25 
mariadb 21:30:57.25 Welcome to the Bitnami mariadb container
mariadb 21:30:57.26 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb
mariadb 21:30:57.26 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb/issues
mariadb 21:30:57.26 
mariadb 21:30:57.26 INFO  ==> ** Starting MariaDB setup **
mariadb 21:30:57.28 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars
mariadb 21:30:57.29 INFO  ==> Initializing mariadb database
mkdir: cannot create directory '/bitnami/mariadb/data': Permission denied

**Comment by juan131** [comment]
Hi @kenlim1228 

Could you please take a look to the workarounds suggested in the guide below for this kind of issues? Thanks in advance

- https://docs.bitnami.com/general/how-to/troubleshoot-helm-chart-issues/#permission-errors-when-enabling-persistence

**Comment by beltran-rubo** [comment]
Hi @kenlim1228, unfortunately the NFS storage is not fully supported on IBM Cloud. Most of the Bitnami Helm Charts uses non-root containers as a good security practice and those containers are not able to create folders on a NFS volume.

In all the IBM Bitnami Charts you would find this paragraph in the README:

> You must install the IBM Cloud Block Storage plug-in from the catalog before you install this Chart. The Block Storage plug-in is a persistent, high-performance iSCSI storage that you can add to your apps by using Kubernetes Persistent Volumes (PVs).

I hope it helps.

**Comment by kenlim1228** [comment]
Thanks, I'll switch the mariadb persistence back to block storage.
