### ISSUE TITLE
Docker Image Stops

### ISSUE THREAD

**Issue by kp3nguinz** [bitnami/bitnami-docker-mariadb#232]
**Description**

I ran docker compose on a ubuntu and a centos machine and received same error, here is my compose file content:

```yaml
version: '2.2'
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - MARIADB_ROOT_PASSWORD=password
      - MARIADB_DATABASE=user
      - MARIADB_USER=mdbuser
      - MARIADB_PASSWORD=password
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - "/opt/data:/bitnami/mariadb/data"
    restart: always
```

**Steps to reproduce the issue:**

1. docker-compose up -d

**Describe the results you received:**

```
mariadb 03:02:04.38 Welcome to the Bitnami mariadb container
mariadb 03:02:04.38 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb
mariadb 03:02:04.39 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb/issues
mariadb 03:02:04.39 
mariadb 03:02:04.39 INFO  ==> ** Starting MariaDB setup **
mariadb 03:02:04.41 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars
mariadb 03:02:04.42 INFO  ==> Initializing mariadb database
mariadb 03:02:04.44 INFO  ==> Updating 'my.cnf' with custom configuration
mariadb 03:02:04.45 INFO  ==> Setting user option
mariadb 03:02:04.46 INFO  ==> Installing database
<Docker Image Dies, or restarts when docker restart option set>
```

A MariaDB server is born and ready to be used by my app!

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**
- Docker Compose Versions Used:
* CentOS 7 docker-compose version 1.18.0, build 8dd22a9
* Ubuntu 20.04 LTS  docker-compose version 1.25.0, build unknown

- Output of `docker version`:
CentOS 7
---
Client:
 Version:         1.13.1
 API version:     1.26
 Package version: docker-1.13.1-203.git0be3e21.el7.centos.x86_64
 Go version:      go1.10.3
 Git commit:      0be3e21/1.13.1
 Built:           Thu Nov 12 15:11:46 2020
 OS/Arch:         linux/amd64
Server:
 Version:         1.13.1
 API version:     1.26 (minimum version 1.12)
 Package version: docker-1.13.1-203.git0be3e21.el7.centos.x86_64
 Go version:      go1.10.3
 Git commit:      0be3e21/1.13.1
 Built:           Thu Nov 12 15:11:46 2020
 OS/Arch:         linux/amd64
 Experimental:    false

Ubuntu 20.04
---
Client:
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.13.8
 Git commit:        afacb8b7f0
 Built:             Fri Dec 18 12:15:19 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.8
  Git commit:       afacb8b7f0
  Built:            Fri Dec  4 23:02:49 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.3-0ubuntu2.2
  GitCommit:        
 runc:
  Version:          spec: 1.0.1-dev
  GitCommit:        
 docker-init:
  Version:          0.18.0
  GitCommit:       

```
(paste your output here)
```

- Output of `docker info`:

Ubuntu 20.04
---
Client:
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.13.8
 Git commit:        afacb8b7f0
 Built:             Fri Dec 18 12:15:19 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.8
  Git commit:       afacb8b7f0
  Built:            Fri Dec  4 23:02:49 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.3-0ubuntu2.2
  GitCommit:        
 runc:
  Version:          spec: 1.0.1-dev
  GitCommit:        
 docker-init:
  Version:          0.18.0
  GitCommit:       

CentOS
---
Client:
 Version:         1.13.1
 API version:     1.26
 Package version: docker-1.13.1-203.git0be3e21.el7.centos.x86_64
 Go version:      go1.10.3
 Git commit:      0be3e21/1.13.1
 Built:           Thu Nov 12 15:11:46 2020
 OS/Arch:         linux/amd64

Server:
 Version:         1.13.1
 API version:     1.26 (minimum version 1.12)
 Package version: docker-1.13.1-203.git0be3e21.el7.centos.x86_64
 Go version:      go1.10.3
 Git commit:      0be3e21/1.13.1
 Built:           Thu Nov 12 15:11:46 2020
 OS/Arch:         linux/amd64
 Experimental:    false

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
Running on compute instances in GCP.

**Comment by juan131** [comment]
Hi @kp3nguinz 

Could you please add the environment variable `BITNAMI_DEBUG` to your Docker Compose as shown below, and retry?

```diff
    image: 'bitnami/mariadb:latest'
    environment:
+     - BITNAMI_DEBUG=true
      - MARIADB_ROOT_PASSWORD=password
```

The verbosity of the logs will be increased and we should have more info to understand what's going on.

**Comment by tijsverwest** [comment]
Hi @kp3nguinz 

I had same issue and this answer resolved it: https://github.com/docker-library/php/issues/898#issuecomment-726981840

**Comment by juan131** [comment]
Thanks for sharing your workaround @tijsverwest !!
It's true that, depending on your docker daemon configuration, the MariaDB container could lack of enough resources to be properly launched.

**Comment by rizkysyazuli** [comment]
Got a similar issue. Adding the `BITNAMI_DEBUG=true` shows me these information. Any ideas?

```
mariadb_1           | Installing MariaDB/MySQL system tables in '/bitnami/mariadb/data' ...
mariadb_1           | 2021-09-22 15:20:59 0 [Warning] Can't create test file /bitnami/mariadb/data/efabf81154f3.lower-test
mariadb_1           |
mariadb_1           | Installation of system tables failed!  Examine the logs in
mariadb_1           | /bitnami/mariadb/data for more information.
mariadb_1           |
mariadb_1           | The problem could be conflicting information in an external
mariadb_1           | my.cnf files. You can ignore these by doing:
mariadb_1           |
mariadb_1           |     shell> /opt/bitnami/mariadb/bin/mysql_install_db --defaults-file=~/.my.cnf
mariadb_1           |
mariadb_1           | You can also try to start the mysqld daemon with:
mariadb_1           |
mariadb_1           |     shell> /opt/bitnami/mariadb/sbin/mysqld --skip-grant-tables --general-log &
mariadb_1           |
mariadb_1           | and use the command line tool /opt/bitnami/mariadb/bin/mysql
mariadb_1           | to connect to the mysql database and look at the grant tables:
mariadb_1           |
mariadb_1           |     shell> /opt/bitnami/mariadb/bin/mysql -u root mysql
mariadb_1           |     mysql> show tables;
mariadb_1           |
mariadb_1           | Try 'mysqld --help' if you have problems with paths.  Using
mariadb_1           | --general-log gives you a log in /bitnami/mariadb/data that may be helpful.
mariadb_1           |
mariadb_1           | The latest information about mysql_install_db is available at
mariadb_1           | https://mariadb.com/kb/en/installing-system-tables-mysql_install_db
mariadb_1           | You can find the latest source at https://downloads.mariadb.org and
mariadb_1           | the maria-discuss email list at https://launchpad.net/~maria-discuss
mariadb_1           |
mariadb_1           | Please check all of the above before submitting a bug report
mariadb_1           | at https://mariadb.org/jira
```

Some additional information:

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           20.10.8
 API version:       1.41
 Go version:        go1.16.6
 Git commit:        3967b7d
 Built:             Fri Jul 30 19:54:27 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.8
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.6
  Git commit:       75249d8
  Built:            Fri Jul 30 19:52:33 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.9
  GitCommit:        e25210fe30a0a703442421b0f60afac609f950a3
 runc:
  Version:          1.0.1
  GitCommit:        v1.0.1-0-g4144b63
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

- Output of `docker info`:

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.6.1-docker)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 7
  Running: 0
  Paused: 0
  Stopped: 7
 Images: 494
 Server Version: 20.10.8
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: e25210fe30a0a703442421b0f60afac609f950a3
 runc version: v1.0.1-0-g4144b63
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-1029-aws
 Operating System: Ubuntu 20.04.1 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.432GiB
 Name: ip-10-203-15-223
 ID: 5GAX:MSKB:CNBP:CTD6:KZA7:BA4E:WSNF:GK76:Z7DB:XHZW:6IIE:L35T
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.29.2, build 5becea4c
docker-py version: 5.0.0
CPython version: 3.7.10
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

**Comment by kp3nguinz** [comment]
I believe I found the issues are usually related to resourcing or storage.
For storage, either  directory permissions (for directory volumes) or
pre-existing install on a volume typically. Make sure you wipe them clean
if you intend a fresh start.
---
Thanks,

Justin Bowen, GCIH, GPEN, GCWN, GCFA
Sr. Security Engineer
Enterprise Security

**Comment by rizkysyazuli** [comment]
hey @kp3nguinz the data directory is still empty. this is a fresh install. about permission, i'm running Docker with non-root, as per their [documentation](https://docs.docker.com/engine/install/linux-postinstall/#manage-docker-as-a-non-root-user).

but.. it does seems i only have 258MB memory left.

**Comment by juan131** [comment]
Hi @rizkysyazuli 

I agree with @kp3nguinz analysis. This could be related with permissions or lack of space. Please ensure that:

- The volume you mount at `/bitnami/mariadb` (as instructed in the [Persistence section](https://github.com/bitnami/bitnami-docker-mariadb#persisting-your-database)) has enough disk space.
- The mounted files and directories must have the proper permissions for the `UID 1001`, since you're running the container as non-root.

**Comment by rizkysyazuli** [comment]
hey @juan131 @kp3nguinz sorry for the late reply. yeah, it seems this was a memory issue (and a little bit of permission as well). but all good now. thx!
