### ISSUE TITLE
setup hangs in lsof

### ISSUE THREAD

**Issue by nafets227** [bitnami/bitnami-docker-mariadb#242]
**Description**

Startup of Mariadb fails. Analysis showed that it is hanging in "lsof" command when restarting MariaDB after setup.
manually killing the lsof processes solves the issue and the container is starting.

**Steps to reproduce the issue:**

1. install helm chart (I use own cloud that has a dependency to MariaDB)
2. See the containers starting

**Describe the results you received:**
MariaDB container is constantly being restarted, since it hangs in lsof and liveliness probes fail.

**Describe the results you expected:**
MariaDB container starting and getting ready

**Additional information you deem important (e.g. issue happens only occasionally):**
Kubernetes 1.21.3
own cloud helm chart with MariaDB helm chart included.
config:
```mariadb:
  primary:
    persistence:
      existingClaim: mariadb.${KUBE_APP}
    extraEnvVars:
    - name: "MARIADB_INIT_SLEEP_TIME"
      value: "20"
  auth:
    rootPassword: "2345678901"
    password: "0987654321"
  volumePermissions:
    enabled: true
```

**Version**

```
runc
VERSION:
   1.0.1
commit: v1.0.1-0-g4144b638
spec: 1.0.2-dev
go: go1.16.6
libseccomp: 2.5.1
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
running on bare metal

**Comment by nafets227** [comment]
Workaround is to limit the nr of files (ulimit -Sn 1024 ; ulimit -Hn 1024) then the issue of lsof does not happen. When not set explicitly, the limit was 1G.

**Comment by pablogalegoc** [comment]
Hi @nafets227!

Although this problem is related to the MariaDB container, it comes from the ownCloud Helm chart so in these cases we recommend opening the issue in [bitnami/charts](https://github.com/bitnami/charts). I can copy it if you like and we’ll take a look a it there.

Regards!

**Comment by korncola** [comment]
Same problem here, setting ulimit as suggests helps, but this is not a solution in a dynamic ci/cd k8s env.
Maybe there should be a timeout in the function are_db_files_locked() in file /opt/bitnami/scripts/libmariadb.sh until the hanging lsof issue itself is resolved.

**Comment by nafets227** [comment]
@pablogalegoc would be happy if you copy it to the helm chart repo, although I am quite sure its not specific to this use case.

**Comment by korncola** [comment]
addendum: using k8s 1.21.3 bare-metal with bitnami/mariadb chart

**Comment by pablogalegoc** [comment]
@nafets227 my fault, I just followed our policy blindly. In these cases where more advanced users point to the issue on a specific docker image we can address it there. About the problem itself, this comes from commit ebfb1cd85bc2b32287c3f299a322c980a6995e22 and is related to bitnami/bitnami-docker-mysql/issues/131. Seems an issue on some combinations of kernel + container runtime. We'll check with the team to see if there are any news on this and will report back.

**Comment by korncola** [comment]
lsof is still used in newest chart.... so still broken
https://artifacthub.io/packages/helm/bitnami/mariadb

**Comment by pablogalegoc** [comment]
@korncola the latest chart version uses `r19` already, you can check:
```
$ helm repo update
$ helm install mariadb bitnami/mariadb
$ kubectl describe pod/mariadb-0 | grep Image:
    Image:          docker.io/bitnami/mariadb:10.5.12-debian-10-r19
```

**Comment by korncola** [comment]
@pablogalegoc thanks forgot to update the repo :-)
Can confirm with the `r19` image everything is working as expected. Thank you very much for your work here.

**Comment by pablogalegoc** [comment]
Awesome! Thank you folks for flagging this in the first place
