### ISSUE TITLE
Can I use git and github in a persistent volume?

### ISSUE THREAD

**Issue by antonio24073** [bitnami/bitnami-docker-mariadb#244]
Hi,
Can I use git and github in a persistent volume?
I think that the max size allowed per file is 100mb.

**Comment by javsalgar** [comment]
Hi,

There was a gitRepo persistent volume type but it was deprecated: https://kubernetes.io/docs/concepts/storage/volumes/#gitrepo

Could you explain your use case in more detail?

**Comment by antonio24073** [comment]
it's ok. I think that git wasn't the better method.
thank you
