### ISSUE TITLE
Can't start container a second time without providing MARIADB_ROOT_PASSWORD

### ISSUE THREAD

**Issue by hamid-elaosta** [bitnami/bitnami-docker-mariadb#250]
**Description**

The official MariaDB Docker image has a feature which allows the container to be started a second time without requiring the root password to be present in the environment so long as data is persisted. The wording in the README for this repository gently implies it should support the same feature, however it does not:

> Passing the MARIADB_ROOT_PASSWORD environment variable when running the image for the first time will set the password of the MARIADB_ROOT_USER user to the value of MARIADB_ROOT_PASSWORD

**Steps to reproduce the issue:**

Here is the process for running the official image. By setting MARIADB_ROOT_PASSWORD on the first run, and persisting data, the container can be stopped and removed, and started again **without** the MARIADB_ROOT_PASSWORD env and it will function as expected. This is a huge advantage because it does not require the root password to be present for the lifetime of the container;

```
➜  ~ docker run -d --name mariadb -e MARIADB_ROOT_PASSWORD=testrootpassword  -p 3306:3306 -v /tmp/mariadb-official:/var/lib/mysql mariadb:10.5
42ba250c9843612f99e712dcaa4a0722a4c5ee5109624d46ccaa82b7b794fd97
➜  ~ docker stop mariadb && docker rm mariadb
mariadb
mariadb
➜  ~ docker run -d --name mariadb -p 3306:3306 -v /tmp/mariadb-official:/var/lib/mysql mariadb:10.5 
d866554eaf95d1cd620a01cd84ba3e7a6516c0583388a40d45dcd54072640772
➜  ~ mysql -h 127.0.0.1 -u root -ptestrootpassword 
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 4
Server version: 10.5.12-MariaDB-1:10.5.12+maria~focal mariadb.org binary distribution

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]>
```

**Describe the results you received:**
When running the Bitnami image, one would assume based on the wording of the README that it also supports this feature of the official image, and that the matching behaviour is expected, however this is not the case:

```
➜  ~ docker run -d --name mariadb-bitnami -e MARIADB_ROOT_PASSWORD=testrootpass -v /tmp/mariadb:/bitnami/mariadb bitnami/mariadb:10.5
f50886e9051b0a3d5410cb0d604815fab0143b27a6f0fb974ddae245f1a3e2cf
➜  ~ docker stop mariadb-bitnami && docker rm mariadb-bitnami                                                                             
mariadb-bitnami
mariadb-bitnami
➜  ~ docker run -d --name mariadb-bitnami -v /tmp/mariadb:/bitnami/mariadb bitnami/mariadb:10.5 
a42255126c124f9346e2caf320ead6ebbbcdb0a0de1d9741a11807c7f507321b
➜  ~ docker logs mariadb-bitnami
mariadb 13:29:53.07 
mariadb 13:29:53.07 Welcome to the Bitnami mariadb container
mariadb 13:29:53.07 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb
mariadb 13:29:53.07 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb/issues
mariadb 13:29:53.07 
mariadb 13:29:53.07 INFO  ==> ** Starting MariaDB setup **
mariadb 13:29:53.09 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars
mariadb 13:29:53.10 ERROR ==> The MARIADB_ROOT_PASSWORD environment variable is empty or not set. Set the environment variable ALLOW_EMPTY_PASSWORD=yes to allow the container to be started with blank passwords. This is recommended only for development.
```

**Describe the results you expected:**

The expected behaviour is for the container to start the second time, without requiring the root password environment variable to be set as it has already been populated in the database.

**Additional information you deem important (e.g. issue happens only occasionally):**

This is not related to empty passwords or the ALLOW_EMPTY_PASSWORD option.

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           20.10.10
 API version:       1.41
 Go version:        go1.16.9
 Git commit:        b485636
 Built:             Mon Oct 25 07:42:57 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.10
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.9
  Git commit:       e2f740d
  Built:            Mon Oct 25 07:41:06 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.11
  GitCommit:        5b46e404f6b9f661a205e28d59c982d3634148f8
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

- Output of `docker info`:

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.6.3-docker)
  scan: Docker Scan (Docker Inc., v0.9.0)

Server:
 Containers: 17
  Running: 1
  Paused: 0
  Stopped: 16
 Images: 212
 Server Version: 20.10.10
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 5b46e404f6b9f661a205e28d59c982d3634148f8
 runc version: v1.0.2-0-g52b36a2
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.11.0-38-generic
 Operating System: Ubuntu 20.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.36GiB
 Name: <redacted>
 ID: <redacted>
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

```

- Output of `docker-compose version` (if applicable):

```
N/A
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
N/A

**Comment by rafariossaa** [comment]
Hi,
  Thanks you very much for you suggestion. Right now, we are a small team with many other tasks and priorities. 
 Would you like to send a PR to include this feature ? We will be glad to review and merge it.

**Comment by hamid-elaosta** [comment]
Hi @rafariossaa, thanks for getting back to me so quickly.

We spent a little time looking at the image, it appears that the need for the root password is pretty tightly integrated into the configuration for replication, the root password is used in several places to configure it.

With a short time-boxed effort we were unable to find a suitable solution that would be of sufficient quality to use, or to PR back here.

As we are also a small team, we will unfortunately need to return to using the MariaDB official image which meets our requirements already; not running as a root user (the main reason we use Bitnami images) and not requiring the root password on every run.

Our thanks for all of the great images you provide.

**Comment by rafariossaa** [comment]
Hi,
  Thanks for coming back and sharing.
   We are glad you liked our images. We try very hard to provide the best user experience we can. Thanks for you kind words.
