### ISSUE TITLE
Initial data import from initdb.d seems to get stuck for larger SQL dumps

### ISSUE THREAD

**Issue by EdanBrooke** [bitnami/bitnami-docker-mariadb#251]
**Description**

When creating a new MariaDB deployment from a `.sql` dump placed in `/docker-entrypoint-initdb.d` the import seems to get stuck at `select 1` if the SQL file is relatively large.

My .sql file is large at 17.2 GB (not tar compressed), but I can reproduce the issue with an entirely different 3.24 GB dump.
I *cannot* reproduce this problem with  a 24.3 MB dump.

```
mariadb 00:05:53.51 INFO  ==> Loading user's custom files from /docker-entrypoint-initdb.d
mariadb 00:05:53.51 DEBUG ==> Executing /docker-entrypoint-initdb.d/01-preimport.sql
mariadb 00:05:53.51 DEBUG ==> Executing SQL command:
select 1
1
mariadb 00:05:53.52 DEBUG ==> Executing SQL command:
SET autocommit=0;
SET unique_checks=0;
SET foreign_key_checks=0;
mariadb 00:05:53.53 DEBUG ==> Executing /docker-entrypoint-initdb.d/02-mydb.sql
mariadb 00:05:53.53 DEBUG ==> Executing SQL command:
select 1
1
```

FYI, my `01-preimport.sql` file disables autocommit and unique/foreign checks to try and accelerate the import.
```sql
SET autocommit=0;
SET unique_checks=0;
SET foreign_key_checks=0;
```

**Steps to reproduce the issue:**

1. Place a larger .sql dump in your working directory (I think anything over 1 GB will probably reproduce this issue)
2. `docker run --rm -it -p 3306:3306 -v $(pwd):/docker-entrypoint-initdb.d -e MARIADB_ROOT_PASSWORD=test -e MARIADB_DATABASE=test -e BITNAMI_DEBUG=true bitnami/mariadb:10.6.5`

**Describe the results you received:**

The import seems to get stuck (see above).
This never seems to complete. I've had one import running for 3 hours and it is still stuck, then tried with the 3.24 GB dump and it's still running after 9 hours. However, when I started the import my system had 46 GB remaining, and 9 hours later it has 43 GB remaining so I think _something_ is happening? Disk IO and system resources are NOT at 100% either,

**Describe the results you expected:**

The import should complete in a timely manner.

**Additional information you deem important (e.g. issue happens only occasionally):**

Not really.

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Cloud integration: 1.0.17
 Version:           20.10.8
 API version:       1.41
 Go version:        go1.16.6
 Git commit:        3967b7d
 Built:             Fri Jul 30 19:54:22 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.8
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.6
  Git commit:       75249d8
  Built:            Fri Jul 30 19:52:31 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.9
  GitCommit:        e25210fe30a0a703442421b0f60afac609f950a3
 runc:
  Version:          1.0.1
  GitCommit:        v1.0.1-0-g4144b63
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

- Output of `docker info`:

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Build with BuildKit (Docker Inc., v0.6.3)
  compose: Docker Compose (Docker Inc., v2.0.0)
  scan: Docker Scan (Docker Inc., v0.8.0)
WARNING: Plugin "/usr/libexec/docker/cli-plugins/docker-app" is not valid: failed to fetch metadata: fork/exec /usr/libexec/docker/cli-plugins/docker-app: no such file or directory

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 257
 Server Version: 20.10.8
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: e25210fe30a0a703442421b0f60afac609f950a3
 runc version: v1.0.1-0-g4144b63
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.4.72-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 50.16GiB
 Name: docker-desktop
 ID: A4B6:BHHF:BX4E:UBU5:ADIP:3RDQ:RUYC:TDIF:KOPO:OFS2:6V4D:QAP6
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 62
  Goroutines: 114
  System Time: 2021-11-14T00:30:44.5487323Z
  EventsListeners: 3
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.29.2, build 5becea4c
docker-py version: 5.0.0
CPython version: 3.7.10
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
I am using Docker for Desktop in WSL 2 (Ubuntu 20.04 distro).

**Comment by pablogalegoc** [comment]
Hi @EdanBrooke!

Just so you know, we don't test our containers on Windows Docker desktop + WSL2 so it's a platform we can't _officially_ support. I'll run some tests to see if it is related to Windows or a general problem with our solution. Do you know where can I download a (large enough) sample sql dump to reproduce the issue? I've not been able to find anything on a quick Google search.

**Comment by EdanBrooke** [comment]
> Hi @EdanBrooke!
> 
> Just so you know, we don't test our containers on Windows Docker desktop + WSL2 so it's a platform we can't _officially_ support. I'll run some tests to see if it is related to Windows or a general problem with our solution. Do you know where can I download a (large enough) sample sql dump to reproduce the issue? I've not been able to find anything on a quick Google search.

Hey @pablogalegoc - you could try with one of Wikimedia's SQL dumps. This is 3 GB compressed. https://dumps.wikimedia.org/enwiki/latest/enwiki-latest-categorylinks.sql.gz

Or there's this dump also from Wikimedia at 550 MB compressed: https://dumps.wikimedia.org/enwiki/latest/enwiki-latest-imagelinks.sql.gz

I appreciate it could be a possible issue with WSL, so I can try and test it on a Linux machine also if needs be.

Thank you
Edan

**Comment by pablogalegoc** [comment]
Thanks! I'll get back to you when I have more info.

**Comment by pablogalegoc** [comment]
Hi again @EdanBrooke!

The `enwiki-latest-imagelinks.sql` is 4.74GB uncompressed and I could import it with no issues:
```
mariadb 10:05:28.25
mariadb 10:05:28.25 Welcome to the Bitnami mariadb container
mariadb 10:05:28.25 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb
mariadb 10:05:28.25 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb/issues
mariadb 10:05:28.25
mariadb 10:05:28.25 INFO  ==> ** Starting MariaDB setup **
mariadb 10:05:28.27 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars
mariadb 10:05:28.28 INFO  ==> Initializing mariadb database
mariadb 10:05:28.28 DEBUG ==> Ensuring expected directories/files exist
mariadb 10:05:28.29 INFO  ==> Updating 'my.cnf' with custom configuration
mariadb 10:05:28.30 DEBUG ==> Cleaning data directory to ensure successfully initialization
mariadb 10:05:28.30 INFO  ==> Installing database
Installing MariaDB/MySQL system tables in '/bitnami/mariadb/data' ...
OK

To start mysqld at boot time you have to copy
support-files/mysql.server to the right place for your system


PLEASE REMEMBER TO SET A PASSWORD FOR THE MariaDB root USER !
To do so, start the server, then issue the following command:

'/opt/bitnami/mariadb/bin/mysql_secure_installation'

which will also give you the option of removing the test
databases and anonymous user created by default.  This is
strongly recommended for production servers.

See the MariaDB Knowledgebase at https://mariadb.com/kb or the
MySQL manual for more instructions.

You can start the MariaDB daemon with:
cd '/opt/bitnami/mariadb' ; /opt/bitnami/mariadb/bin/mysqld_safe --datadir='/bitnami/mariadb/data'

You can test the MariaDB daemon with mysql-test-run.pl
cd '/opt/bitnami/mariadb/mysql-test' ; perl mysql-test-run.pl

Please report any problems at https://mariadb.org/jira

The latest information about MariaDB is available at https://mariadb.org/.
You can find additional information about the MySQL part at:
https://dev.mysql.com
Consider joining MariaDB's strong and vibrant community:
https://mariadb.org/get-involved/

mariadb 10:05:29.04 INFO  ==> Starting mariadb in background
2021-11-19 10:05:29 0 [Note] /opt/bitnami/mariadb/sbin/mysqld (server 10.6.5-MariaDB) starting as process 88 ...
2021-11-19 10:05:29 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
2021-11-19 10:05:29 0 [Note] InnoDB: Number of pools: 1
2021-11-19 10:05:29 0 [Note] InnoDB: Using crc32 + pclmulqdq instructions
2021-11-19 10:05:29 0 [Note] mysqld: O_TMPFILE is not supported on /opt/bitnami/mariadb/tmp (disabling future attempts)
2021-11-19 10:05:29 0 [Note] InnoDB: Using Linux native AIO
2021-11-19 10:05:29 0 [Note] InnoDB: Initializing buffer pool, total size = 134217728, chunk size = 134217728
2021-11-19 10:05:29 0 [Note] InnoDB: Completed initialization of buffer pool
2021-11-19 10:05:29 0 [Note] InnoDB: 128 rollback segments are active.
2021-11-19 10:05:29 0 [Note] InnoDB: Creating shared tablespace for temporary tables
2021-11-19 10:05:29 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
2021-11-19 10:05:29 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
2021-11-19 10:05:29 0 [Note] InnoDB: 10.6.5 started; log sequence number 41361; transaction id 14
2021-11-19 10:05:29 0 [Note] InnoDB: Loading buffer pool(s) from /bitnami/mariadb/data/ib_buffer_pool
2021-11-19 10:05:29 0 [Note] Plugin 'FEEDBACK' is disabled.
2021-11-19 10:05:29 0 [Note] Server socket created on IP: '127.0.0.1'.
2021-11-19 10:05:29 0 [Note] InnoDB: Buffer pool(s) load completed at 211119 10:05:29
2021-11-19 10:05:29 0 [Warning] 'user' entry 'root@fddf998720c0' ignored in --skip-name-resolve mode.
2021-11-19 10:05:29 0 [Warning] 'user' entry '@fddf998720c0' ignored in --skip-name-resolve mode.
2021-11-19 10:05:29 0 [Warning] 'proxies_priv' entry '@% root@fddf998720c0' ignored in --skip-name-resolve mode.
2021-11-19 10:05:29 0 [Note] /opt/bitnami/mariadb/sbin/mysqld: ready for connections.
Version: '10.6.5-MariaDB'  socket: '/opt/bitnami/mariadb/tmp/mysql.sock'  port: 3306  Source distribution
mariadb 10:05:31.06 DEBUG ==> Executing SQL command:
select 1
1
mariadb 10:05:31.06 INFO  ==> Configuring authentication
mariadb 10:05:31.07 DEBUG ==> Executing SQL command:
DELETE FROM mysql.user WHERE user not in ('mysql.sys','mariadb.sys');
mariadb 10:05:31.08 DEBUG ==> Configuring root user credentials
mariadb 10:05:31.08 DEBUG ==> Executing SQL command:
-- create root@localhost user for local admin access
-- create user 'root'@'localhost' identified by "test";
-- grant all on *.* to 'root'@'localhost' with grant option;
-- create admin user for remote access
create user 'root'@'%' identified  by "test";
grant all on *.* to 'root'@'%' with grant option;
flush privileges;
2021-11-19 10:05:31 5 [Warning] 'proxies_priv' entry '@% root@fddf998720c0' ignored in --skip-name-resolve mode.
mariadb 10:05:31.09 DEBUG ==> removing the unknown user
mariadb 10:05:31.10 DEBUG ==> Executing SQL command:
select Host from user where User='';
mariadb 10:05:31.11 DEBUG ==> Creating database test
mariadb 10:05:31.11 DEBUG ==> Executing SQL command:
create database if not exists `test` ;
mariadb 10:05:31.14 INFO  ==> Running mysql_upgrade
Phase 1/7: Checking and upgrading mysql database
Processing databases
mysql
mysql.column_stats                                 OK
mysql.columns_priv                                 OK
mysql.db                                           OK
mysql.event                                        OK
mysql.func                                         OK
mysql.global_priv                                  OK
mysql.gtid_slave_pos                               OK
mysql.help_category                                OK
mysql.help_keyword                                 OK
mysql.help_relation                                OK
mysql.help_topic                                   OK
[...]
Phase 4/7: Running 'mysql_fix_privilege_tables'
Phase 5/7: Fixing table and database names
Phase 6/7: Checking and upgrading tables
Processing databases
information_schema
performance_schema
sys
sys.sys_config                                     OK
test
Phase 7/7: Running 'FLUSH PRIVILEGES'
2021-11-19 10:05:32 19 [Warning] 'proxies_priv' entry '@% root@fddf998720c0' ignored in --skip-name-resolve mode.
OK
[...]
```
```
I have no name!@fddf998720c0:/$ mysql -u root -p
Enter password:
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 5
Server version: 10.6.5-MariaDB Source distribution

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> use sys;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
MariaDB [sys]> show tables;
+-----------------------------------------------+
| Tables_in_sys                                 |
+-----------------------------------------------+
| host_summary                                  |
| host_summary_by_file_io                       |
| host_summary_by_file_io_type                  |
[...]
```
I didn't need to run your `pre-import` script. I think the issue here might be Docker desktop + WSL2. I've run it on minikube without problems: `Linux minikube 4.19.202 #1 SMP Wed Oct 27 22:52:27 UTC 2021 x86_64 GNU/Linux`

**Comment by EdanBrooke** [comment]
> Hi again @EdanBrooke!
> 
> The `enwiki-latest-imagelinks.sql` is 4.74GB uncompressed and I could import it with no issues:
> 
> ```
> mariadb 10:05:28.25
> mariadb 10:05:28.25 Welcome to the Bitnami mariadb container
> mariadb 10:05:28.25 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb
> mariadb 10:05:28.25 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb/issues
> mariadb 10:05:28.25
> mariadb 10:05:28.25 INFO  ==> ** Starting MariaDB setup **
> mariadb 10:05:28.27 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars
> mariadb 10:05:28.28 INFO  ==> Initializing mariadb database
> mariadb 10:05:28.28 DEBUG ==> Ensuring expected directories/files exist
> mariadb 10:05:28.29 INFO  ==> Updating 'my.cnf' with custom configuration
> mariadb 10:05:28.30 DEBUG ==> Cleaning data directory to ensure successfully initialization
> mariadb 10:05:28.30 INFO  ==> Installing database
> Installing MariaDB/MySQL system tables in '/bitnami/mariadb/data' ...
> OK
> 
> To start mysqld at boot time you have to copy
> support-files/mysql.server to the right place for your system
> 
> 
> PLEASE REMEMBER TO SET A PASSWORD FOR THE MariaDB root USER !
> To do so, start the server, then issue the following command:
> 
> '/opt/bitnami/mariadb/bin/mysql_secure_installation'
> 
> which will also give you the option of removing the test
> databases and anonymous user created by default.  This is
> strongly recommended for production servers.
> 
> See the MariaDB Knowledgebase at https://mariadb.com/kb or the
> MySQL manual for more instructions.
> 
> You can start the MariaDB daemon with:
> cd '/opt/bitnami/mariadb' ; /opt/bitnami/mariadb/bin/mysqld_safe --datadir='/bitnami/mariadb/data'
> 
> You can test the MariaDB daemon with mysql-test-run.pl
> cd '/opt/bitnami/mariadb/mysql-test' ; perl mysql-test-run.pl
> 
> Please report any problems at https://mariadb.org/jira
> 
> The latest information about MariaDB is available at https://mariadb.org/.
> You can find additional information about the MySQL part at:
> https://dev.mysql.com
> Consider joining MariaDB's strong and vibrant community:
> https://mariadb.org/get-involved/
> 
> mariadb 10:05:29.04 INFO  ==> Starting mariadb in background
> 2021-11-19 10:05:29 0 [Note] /opt/bitnami/mariadb/sbin/mysqld (server 10.6.5-MariaDB) starting as process 88 ...
> 2021-11-19 10:05:29 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
> 2021-11-19 10:05:29 0 [Note] InnoDB: Number of pools: 1
> 2021-11-19 10:05:29 0 [Note] InnoDB: Using crc32 + pclmulqdq instructions
> 2021-11-19 10:05:29 0 [Note] mysqld: O_TMPFILE is not supported on /opt/bitnami/mariadb/tmp (disabling future attempts)
> 2021-11-19 10:05:29 0 [Note] InnoDB: Using Linux native AIO
> 2021-11-19 10:05:29 0 [Note] InnoDB: Initializing buffer pool, total size = 134217728, chunk size = 134217728
> 2021-11-19 10:05:29 0 [Note] InnoDB: Completed initialization of buffer pool
> 2021-11-19 10:05:29 0 [Note] InnoDB: 128 rollback segments are active.
> 2021-11-19 10:05:29 0 [Note] InnoDB: Creating shared tablespace for temporary tables
> 2021-11-19 10:05:29 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
> 2021-11-19 10:05:29 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
> 2021-11-19 10:05:29 0 [Note] InnoDB: 10.6.5 started; log sequence number 41361; transaction id 14
> 2021-11-19 10:05:29 0 [Note] InnoDB: Loading buffer pool(s) from /bitnami/mariadb/data/ib_buffer_pool
> 2021-11-19 10:05:29 0 [Note] Plugin 'FEEDBACK' is disabled.
> 2021-11-19 10:05:29 0 [Note] Server socket created on IP: '127.0.0.1'.
> 2021-11-19 10:05:29 0 [Note] InnoDB: Buffer pool(s) load completed at 211119 10:05:29
> 2021-11-19 10:05:29 0 [Warning] 'user' entry 'root@fddf998720c0' ignored in --skip-name-resolve mode.
> 2021-11-19 10:05:29 0 [Warning] 'user' entry '@fddf998720c0' ignored in --skip-name-resolve mode.
> 2021-11-19 10:05:29 0 [Warning] 'proxies_priv' entry '@% root@fddf998720c0' ignored in --skip-name-resolve mode.
> 2021-11-19 10:05:29 0 [Note] /opt/bitnami/mariadb/sbin/mysqld: ready for connections.
> Version: '10.6.5-MariaDB'  socket: '/opt/bitnami/mariadb/tmp/mysql.sock'  port: 3306  Source distribution
> mariadb 10:05:31.06 DEBUG ==> Executing SQL command:
> select 1
> 1
> mariadb 10:05:31.06 INFO  ==> Configuring authentication
> mariadb 10:05:31.07 DEBUG ==> Executing SQL command:
> DELETE FROM mysql.user WHERE user not in ('mysql.sys','mariadb.sys');
> mariadb 10:05:31.08 DEBUG ==> Configuring root user credentials
> mariadb 10:05:31.08 DEBUG ==> Executing SQL command:
> -- create root@localhost user for local admin access
> -- create user 'root'@'localhost' identified by "test";
> -- grant all on *.* to 'root'@'localhost' with grant option;
> -- create admin user for remote access
> create user 'root'@'%' identified  by "test";
> grant all on *.* to 'root'@'%' with grant option;
> flush privileges;
> 2021-11-19 10:05:31 5 [Warning] 'proxies_priv' entry '@% root@fddf998720c0' ignored in --skip-name-resolve mode.
> mariadb 10:05:31.09 DEBUG ==> removing the unknown user
> mariadb 10:05:31.10 DEBUG ==> Executing SQL command:
> select Host from user where User='';
> mariadb 10:05:31.11 DEBUG ==> Creating database test
> mariadb 10:05:31.11 DEBUG ==> Executing SQL command:
> create database if not exists `test` ;
> mariadb 10:05:31.14 INFO  ==> Running mysql_upgrade
> Phase 1/7: Checking and upgrading mysql database
> Processing databases
> mysql
> mysql.column_stats                                 OK
> mysql.columns_priv                                 OK
> mysql.db                                           OK
> mysql.event                                        OK
> mysql.func                                         OK
> mysql.global_priv                                  OK
> mysql.gtid_slave_pos                               OK
> mysql.help_category                                OK
> mysql.help_keyword                                 OK
> mysql.help_relation                                OK
> mysql.help_topic                                   OK
> [...]
> Phase 4/7: Running 'mysql_fix_privilege_tables'
> Phase 5/7: Fixing table and database names
> Phase 6/7: Checking and upgrading tables
> Processing databases
> information_schema
> performance_schema
> sys
> sys.sys_config                                     OK
> test
> Phase 7/7: Running 'FLUSH PRIVILEGES'
> 2021-11-19 10:05:32 19 [Warning] 'proxies_priv' entry '@% root@fddf998720c0' ignored in --skip-name-resolve mode.
> OK
> [...]
> ```
> 
> ```
> I have no name!@fddf998720c0:/$ mysql -u root -p
> Enter password:
> Welcome to the MariaDB monitor.  Commands end with ; or \g.
> Your MariaDB connection id is 5
> Server version: 10.6.5-MariaDB Source distribution
> 
> Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.
> 
> Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.
> 
> MariaDB [(none)]> use sys;
> Reading table information for completion of table and column names
> You can turn off this feature to get a quicker startup with -A
> 
> Database changed
> MariaDB [sys]> show tables;
> +-----------------------------------------------+
> | Tables_in_sys                                 |
> +-----------------------------------------------+
> | host_summary                                  |
> | host_summary_by_file_io                       |
> | host_summary_by_file_io_type                  |
> [...]
> ```
> 
> I didn't need to run your `pre-import` script. I think the issue here might be Docker desktop + WSL2. I've run it on minikube without problems: `Linux minikube 4.19.202 #1 SMP Wed Oct 27 22:52:27 UTC 2021 x86_64 GNU/Linux`

Hi,

Thanks for giving this a try.
I will see if I can reproduce the issue on my Linux machine then, but I hope it's something I can work around as our devs use WSL.

Thanks!
Edan

**Comment by EdanBrooke** [comment]
Hi @pablogalegoc -

Just got around to testing this on an Ubuntu 20.04 machine (clean install), and it still appears to be stuck at:
```
mariadb 23:06:55.07 DEBUG ==> Executing SQL command:
select 1
1
```
I started the import of the `enwiki-latest-categorylinks.sql` file nearly an hour ago. (Extracted from the .tar.gz first before trying to import it).

I notice in the command output you shared, there is no `Loading user's custom files from /docker-entrypoint-initdb.d` message after the `[Warning] 'proxies_priv' entry` line. Has this part been redacted? I was trying to work out how long the import took on your machine, maybe I'm being impatient.

Thanks,
Edan

**Comment by EdanBrooke** [comment]
![image](https://user-images.githubusercontent.com/17439456/144742226-436cca12-def7-4353-a30e-c96c4b71da3a.png)

**Comment by EdanBrooke** [comment]
I've done some digging and found that if I replace [this](https://github.com/bitnami/bitnami-docker-mariadb/blob/6fe36d07d7e89c37f79eef7f098b6b8918e5e716/10.6/debian-10/rootfs/opt/bitnami/scripts/libmariadb.sh#L350-L357) with the following, the import works. This indicates that the issue isn't related to the filesystem or a problem with the database dump itself. (I also added `pv` to the image to monitor the import progress, but this shouldn't be necessary).

```
*.sql)
    [[ "$DB_REPLICATION_MODE" = "slave" ]] && warn "Custom SQL initdb is not supported on slave nodes, ignoring $f" && continue
    wait_for_mysql_access "$DB_ROOT_USER"
    pv $f | mysql -u $DB_ROOT_USER -p$DB_ROOT_PASSWORD $DB_DATABASE
    ;;
```

I think there must be something in these DB dumps that's causing the custom `mysql_execute` function to trip up. Any ideas anyone?

Thanks!

**Comment by javsalgar** [comment]
What if you pipe it to mysql_execute, does it get stuck too?

**Comment by EdanBrooke** [comment]
> 

I've not tried this yet, currently on Christmas break but will pick it up again once we return to work.

Thank you

**Comment by mariuszdubielecki** [comment]
I also struggle with importing 1GB  SQL dump and **bitnami/mariadb:10.2**
I spent a lot of time debugging the problem and I think the issue is storing a big file as a variable in bash. I have added a couple of debugging logs and it looks like the following line blocks forever
```mysql_cmd="$(</dev/stdin)"```

CPU usage is 100% for setup.sh while `mysqld` does not do anything which would indicate a problem with the shell script.
```
    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                                                                                                                       
    305 1001      20   0 2103736   2.0g   1704 R 100.0   6.5   1:30.60 setup.sh                                                                                                                                      
      1 1001      20   0    4664   4024   2768 S   0.0   0.0   0:00.01 entrypoint.sh                                                                                                                                 
     15 1001      20   0    6580   5800   2612 S   0.0   0.0   0:05.47 setup.sh                                                                                                                                      
    103 1001      20   0    4792   2616   1320 S   0.0   0.0   0:00.00 setup.sh                                                                                                                                      
    104 1001      20   0 2320848 305276  18460 S   0.0   0.9   0:14.69 mysqld                                                                                                                                        
    281 1001      20   0    3864   3248   2824 S   0.0   0.0   0:00.00 bash                                                                                                                                          
    304 1001      20   0    2676    764    692 S   0.0   0.0   0:04.60 gzip                                                                                                                                          
    307 1001      20   0    6580   3188      0 S   0.0   0.0   0:03.85 setup.sh                                                                                                                                      
    360 1001      20   0    7992   3208   2704 R   0.0   0.0   0:00.00 top                                                                                                                                           


```

I tried to replace it with ```mysql_cmd=$(cat /dev/stdin)``` but it  created an exception like ```/opt/bitnami/scripts/libmariadb.sh: xrealloc: cannot allocate 18446744071665247872 bytes```

I am not Unix/bash expert but it seems to me like storying big files as a variable in bash is not a good idea. Ideally, we should just pass a path to a file with a SQL

Regarding the original post with `01-preimport.sql` beside the file size which seems to be a problem, I think you should set the variables as global otherwise they are session scoped variables and would not be applicable for the following file which are imported.

**Comment by javsalgar** [comment]
Hi,

Thanks for letting us know! I think it makes sense to review the script operations so everything is moved to a file before executing the mysql operation. Would that make sense?

**Comment by EdanBrooke** [comment]
I keep letting this issue go stale, my apologies. I will try to get to this and re test but I believe it is still an issue.

**Comment by EdanBrooke** [comment]
Hi,

I have been able to reproduce the issue again with `10.6.5-debian-10-r91` on another Linux device with `enwiki-latest-imagelinks.sql` in my `/docker-entrypoint-initdb` directory.

Output of `docker version`:
```
Client:
 Version:           20.10.12
 API version:       1.41
 Go version:        go1.17.5
 Git commit:        e91ed5707e
 Built:             Mon Dec 13 22:31:40 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.12
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.5
  Git commit:       459d0dfbbb
  Built:            Mon Dec 13 22:30:43 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.5.9
  GitCommit:        1407cab509ff0d96baa4f0eb6ff9980270e6e620.m
 runc:
  Version:          1.1.0
  GitCommit:        v1.1.0-0-g067aaf85
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

Output of `docker info`
```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.7.1-docker)
  compose: Docker Compose (Docker Inc., 2.2.3)

Server:
 Containers: 5
  Running: 1
  Paused: 0
  Stopped: 4
 Images: 35
 Server Version: 20.10.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: false
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 1407cab509ff0d96baa4f0eb6ff9980270e6e620.m
 runc version: v1.1.0-0-g067aaf85
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.10.96-1-MANJARO
 Operating System: Manjaro Linux
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.33GiB
 Name: edan-laptop
 ID: ZIWF:HVA5:6PMN:SP7L:TWTP:OAMS:PSOS:G532:FE36:SDWW:ACK7:7CZJ
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

Piping to `mysql_execute` doesn't work either. I implemented it as follows, using `pv` again to monitor status.

```
                *.sql)
                    [[ "$DB_REPLICATION_MODE" = "slave" ]] && warn "Custom SQL initdb is not supported on slave nodes, ignoring $f" && continue
                    wait_for_mysql_access "$DB_ROOT_USER"
                    pv $f | mysql_execute "$DB_DATABASE" "$DB_ROOT_USER" "$DB_ROOT_PASSWORD"
                    # if ! mysql_execute "$DB_DATABASE" "$DB_ROOT_USER" "$DB_ROOT_PASSWORD" < "$f"; then
                    #     error "Failed executing $f"
                    #     return 1
                    # fi
                    ;;
```
It seems to get stuck. It very quickly gets to 19% but then doesn't look to progress further, as shown:
```
Phase 7/7: Running 'FLUSH PRIVILEGES'
2022-02-13 14:57:10 19 [Warning] 'proxies_priv' entry '@% root@7b02557d4e47' ignored in --skip-name-resolve mode.
OK
mariadb 14:57:10.05 INFO  ==> Loading user's custom files from /docker-entrypoint-initdb.d
mariadb 14:57:10.05 DEBUG ==> Executing /docker-entrypoint-initdb.d/enwiki-latest-imagelinks.sql
mariadb 14:57:10.06 DEBUG ==> Executing SQL command:
select 1
1
    MiB 0:00:06 [ 158MiB/s] [=================================>                                                                                                                      ] 19% ETA 0:00:24

```

I once again verified with `pv $f | mysql -u "$DB_ROOT_USER" -p"$DB_ROOT_PASSWORD" "$DB_DATABASE"` as I commented earlier and this completed but did take 4 hours, 0 minutes and 14 seconds to finish.

@pablogalegoc - it doesn't appear like the Wikimedia dump was actually imported in your snippet. Can you confirm that the data actually got imported?

It may also be worth noting that as of the later versions of MariaDB, I had to set `MARIA_EXTRA_FLAGS='--transaction-isolation=READ-COMMITTED --binlog-format=ROW --skip-innodb-read-only-compressed'` to allow the Media Links dump to be imported successfully but this is separate from the issue raised.

Best,
Edan

**Comment by javsalgar** [comment]
(Sorry I clicked the wrong button)

Thank you! I will forward this for the engineering team for re-prioritization.

**Comment by marcosbc** [comment]
Hi all, we just released the following versions of the container image, that fix this issue:

* [`10.2.43-debian-10-r14`](https://github.com/bitnami/bitnami-docker-mariadb/commit/81a211a1af39b40b3359b115306fbbcf33d343b4)
* [`10.3.34-debian-10-r17`](https://github.com/bitnami/bitnami-docker-mariadb/commit/65af3badc2fdb2b379bdc16741fca7cb4eeb43c4)
* [`10.4.24-debian-10-r15`](https://github.com/bitnami/bitnami-docker-mariadb/commit/e6a10b8e2d4c105d7451a34a0825c2f78d732944)
* [`10.5.15-debian-10-r15`](https://github.com/bitnami/bitnami-docker-mariadb/commit/40bd4199074695d259b98a1490bcea80c312e240)
* [`10.6.7-debian-10-r14`](https://github.com/bitnami/bitnami-docker-mariadb/commit/030667b16b927bc09ab754f18bc010359b3994b3)

With these changes, we were able to import a 1.2GB database in less than 15 minutes, as opposed to the 4+ hours it would take before.
