### ISSUE TITLE
full mysql_upgrade on every startup instead only on version upgrade

### ISSUE THREAD

**Issue by tgruenert** [bitnami/bitnami-docker-mariadb#252]
**Description**

mariadb starts with a pre startup flight doing a full table checkup for all user data. depending on volume and speed of storage this can take a long time. normaly mysql_upgrade / mariadb_upgrade recognizes a upgrade by checking the content of {data_dir}/mysql_upgrade_info and make a decision by itself about a full upgrade.

with the '--force' in 
https://github.com/bitnami/bitnami-docker-mariadb/blob/d2da044fe6a4bc02196562bd99d78dfc8e6ccba5/10.5/debian-10/rootfs/opt/bitnami/scripts/libmariadb.sh#L735
this function is overwritten.

**Steps to reproduce the issue:**

1. Start docker-container with BITNAMI_DEBUG=TRUE 
You see upgrade log lines for database test
2. Stop and restart container
You see also upgrade log lines for database test

**Describe the results you received:**

actually every time at container starts up every user table is scanned by mariadb_upgrade

**Describe the results you expected:**

mariadb_upgrade should scan user tables only if it detects an upgrade by inspecting file {data_dir}/mysql_upgrade_info
Additional the container should respect settings in section 
```
[mariadb-upgrade]
```
of mariadb config file.

**Additional information**

The problem is relevant for many databases with many tables which may depends on not very fast storage. In my personal case startup time is around 2 hours which is unacceptable.

**Version**

```
Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
```

**Comment by tgruenert** [comment]
Additional i would say that some information came from https://jira.mariadb.org/browse/MDEV-27060

**Comment by grooverdan** [comment]
Recommended change: remove the `--force`. This leaves `mysql_upgrade` to perform the version check and continue without action if already updated.

**Comment by carrodher** [comment]
I guess it makes sense, but I would need to check other collateral effects this may have. Such as how this could affect database upgrading. As an intermediate solution, what do you think about a flag/variable to enable/disable the `--force` option?

**Comment by grooverdan** [comment]
No, an enable/disable isn't sensible. People could put `force` in a `[mariadb-upgrade]` section if they desired. The `force` does nothing other than bypassing the version check.

**Comment by carrodher** [comment]
Would you like to create a PR with the proposed solution? The team will be happy to review it and test the changes into the automated test & release pipeline
