### ISSUE TITLE
Is mariadb-plugin-s3 supported with bitnami/mariadb?

### ISSUE THREAD

**Issue by happycujo** [bitnami/bitnami-docker-mariadb#253]
Hello, 

I was wondering was is the proper way to install the **mariadb-plugin-s3 plugin**? As this plugin is fairly new, it does not seem to be documented how to do so. 

i have try to adding it using the following dockerfile 

  ```
FROM bitnami/mariadb:10.6.5
  USER root
  RUN echo "deb http://ftp.de.debian.org/debian bullseye main" >> /etc/apt/sources.list
  RUN apt-get update
  RUN apt-get install mariadb-plugin-s3 -y
```

docker run --name mariadb  -e ALLOW_EMPTY_PASSWORD=yes -v ${pwd}/mariadb/my.cnf:/opt/bitnami/mariadb/conf/my.cnf mariadb:003

where  my.cnf
```
[mariadb]
plugin-load-add=ha_s3

s3-host-name=s3.amazonaws.com
s3-protocol-version=Amazon
s3-bucket=backup
s3-access-key=...
s3-secret-key=...
s3-region=...
```

It is ending up with mariadb  container crashing without providing an error message. 

```
mariadb 20:59:02.15
mariadb 20:59:02.16 Welcome to the Bitnami mariadb container
mariadb 20:59:02.16 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb
mariadb 20:59:02.17 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb/issues
mariadb 20:59:02.17
mariadb 20:59:02.18 INFO  ==> ** Starting MariaDB setup **
mariadb 20:59:02.23 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars
mariadb 20:59:02.23 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
mariadb 20:59:02.26 INFO  ==> Initializing mariadb database
mariadb 20:59:02.29 INFO  ==> Updating 'my.cnf' with custom configuration
mariadb 20:59:02.31 INFO  ==> Installing database <-- Crash here - no error message
```
Any settings related to s3 seems to make the launch fail. I would assume that the plugin is not installed as intended.

What would be the proper procedure to install **mariadb-plugin-s3 plugin**?

Best Regards

**Comment by miguelaeh** [comment]
Hi @happycujo ,
Could you share a link to the installation docs? 
Also, note that you are at the end running your image as root, I would recommend you to add a `USER 1001` at the end of your Dockerfile

**Comment by happycujo** [comment]
Hello @miguelaeh,

Many thanks for the quick turn around. I will definitively follow your recommendation regarding the user. I was actually not quite sure what was the default user to be used.

Regarding the documentation, i  have used this link: https://mariadb.com/kb/en/using-the-s3-storage-engine/

I was able to make it work  on the main distribution using the dockerfile below:

```
FROM mariadb:10.7.1
USER root
RUN apt-get update
RUN apt-get install mariadb-plugin-s3 -y
#TODO - Add USER 1001 :)
```

I fixed an issue with the previous configuration; i needed to add a space to separate the plugin load from the s3 configuration. (still not working for bitnami mariadb  with this change)

```
[mariadb]
plugin-load-add=ha_s3

# Adding a space 
s3-host-name=s3.amazonaws.com
s3-protocol-version=Amazon
s3-bucket=backup
s3-access-key=...
s3-secret-key=...
s3-region=...
```
Using the following SQL i was able to move the table to S3:
```
MariaDB [(none)]> create database test
MariaDB [(none)]> use test;
MariaDB [test]> create table my(v1 int, v2 int);
MariaDB [test]> insert into my values(1,2);
MariaDB [test]> alter table my engine=s3;
Query OK, 1 row affected (2.171 sec)
Records: 1  Duplicates: 0  Warnings: 0
```

I would like the make the same thing work on bitnami distribution. After some test, i realised that the plugin was not installed in the right folder. I have updated the bitnami dockerfile as follow to correct this:

```
FROM bitnami/mariadb:10.6.5
#FROM mariadb:10.7.1
USER root
RUN echo "deb http://ftp.de.debian.org/debian bullseye main" >> /etc/apt/sources.list
RUN apt-get update
RUN apt-get install mariadb-plugin-s3 -y
RUN cp /usr/lib/mysql/plugin/ha_s3.so /opt/bitnami/mariadb/lib/plugin/
# TODO USER 1001 :)
```

Since i did not have any debug output when using my custom configuration, i launched it manually without custom configuration 

`docker run --name mariadb  -e ALLOW_EMPTY_PASSWORD=yes  bitnami/maria:003`

When i tried to install the plugin manually, i ended up with the following error:
```
INSTALL SONAME 'ha_s3';
ERROR 1126 (HY000): Can't open shared library '/opt/bitnami/mariadb/lib/plugin/ha_s3.so' (errno: 2, undefined symbol: s3f)
```
At this point, i would assume the following points
1- I am not understand well how to install plugin with bitnami mariadb. 
2- I may not be using the right version of the plugin / package repository for the os used by bitnami/mariadb container. 

Your feedback would be well appreciated!

**Comment by miguelaeh** [comment]
Hi @happycujo ,

I can see in the guide you shared that they are using `yum` as package manager. So probably that guide is for centos, I also saw that you are adding a deb repository to be able to install the `mariadb-plugin-s3` package since it does not exist by default.
Login to the errors it seems to me like the package version you are installing is probably not compatible with the MariaDB version you are using

**Comment by happycujo** [comment]
I agree that the package location is likely wrong (http://ftp.de.debian.org/debian bullseye main). As I am not sure what the appropriate one to use (the plugin is not available in the default package location), I will simply assume that this feature is not supported for bitnami/mariadb.

Thanks @miguelaeh for having taken the time to look at the issue.
