### ISSUE TITLE
Not all log is redirected to stdout

### ISSUE THREAD

**Issue by pupseba** [bitnami/bitnami-docker-mariadb#267]
### Name and Version

bitnami/10.6.4-debian-10-r0

### What is the problem this feature will solve?

mysqld.err and mariadb-slow.log are lost after pod restart.

The [comment](https://github.com/bitnami/bitnami-docker-mariadb/blob/10.6.7-debian-10-r21/10.6/debian-10/rootfs/opt/bitnami/scripts/mariadb/postunpack.sh#L30) in the command suggests that all logs are redirected to stdout, yet, only mysqld.log is. This makes us not to be able to see the logs for a pod that crashed.

### What is the feature you are proposing to solve the problem?

All logs, including mysqld.err and mariadb-slow.log should be able to be retained even after a pod crash/restart.

### What alternatives have you considered?

Alternatives we can think of would be one of:

1. Providing a way to redirect these 2 other logs to stdout.
2. Providing a way to log-rotate these logs in case no redirection to stdout is desired, but a persistent storage will be in place for them.

Most infrastructures use some sort of log facility to parse and work with logs where in most cases, JSON is the format of such logs for easy "out-of-the-box" parsing. The lack of ability of mariadb to use JSON output format for its logs, could be a dealbreaker that inclines the balance to chose "persistent storage + logrotation" instead of some stdout/stderr redirection.

**Comment by javsalgar** [comment]
Hi! 

Thank you so much for the input. I will open a task for the engineering team. I cannot guarantee an ETA, but if you want to speed up the process, feel free to submit a PR and we will review it.

**Comment by pupseba** [comment]
Hi!

Well, we sort of found an easy way to deal with it by defining in the my.cnf file, that the slow and err logs should go to /dev/stdout and /dev/stderr.

I guess that is somehow flexible enough for us and hence maybe no need to any change in the image is required (like adding yet another "ln to stdout").

With that in mind, I think we could just close this feature request but I leave it up to you :)

**Comment by webdz9r** [comment]
> 



> Hi!
> 
> Well, we sort of found an easy way to deal with it by defining in the my.cnf file, that the slow and err logs should go to /dev/stdout and /dev/stderr.
> 
> I guess that is somehow flexible enough for us and hence maybe no need to any change in the image is required (like adding yet another "ln to stdout").
> 
> With that in mind, I think we could just close this feature request but I leave it up to you :)

Can you post your example config?

**Comment by pupseba** [comment]
Sure. The "log" part of our my.cnf looks like this:

```yaml
        # Logs:
          log-error               = /dev/stderr
          slow_query_log          = 1
          slow_query_log_file     = /dev/stdout
          long_query_time         = 5.0 # in seconds
          log_queries_not_using_indexes = 1
```

**Comment by gongomgra** [comment]
Hi @pupseba,

We updated our MariaDB containers adding the slow query configuration, disabled by default, and also fixed the issue of some logs not being shown when an error was detected starting MariaDB. You can control the slow query features using the environment variables mentioned in the [README.md](https://github.com/bitnami/bitnami-docker-mariadb#slow-query-logs) file.

I also did a test with the chart by adding a non-valid `this_is_a_wrong_parameter=1` to the `my.cnf` file and the error message is now shown in the pod's logs.

```
# modify values.yaml with 'this_is_a_wrong_parameter=1'
$ helm install --namespace mariadb mariadb bitnami/mariadb
$ kubectl -n mariadb logs mariadb-0
mariadb 11:27:48.42
mariadb 11:27:48.42 Welcome to the Bitnami mariadb container
mariadb 11:27:48.42 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb
mariadb 11:27:48.42 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb/issues
mariadb 11:27:48.42
mariadb 11:27:48.42 INFO  ==> ** Starting MariaDB setup **
mariadb 11:27:48.44 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars
mariadb 11:27:48.45 INFO  ==> Initializing mariadb database
mariadb 11:27:48.46 WARN  ==> The mariadb configuration file '/opt/bitnami/mariadb/conf/my.cnf' is not writable. Configurations based on environment variables will not be applied for this file.
mariadb 11:27:48.46 INFO  ==> Using persisted data
mariadb 11:27:48.48 INFO  ==> Running mysql_upgrade
mariadb 11:27:48.49 INFO  ==> Starting mariadb in background
2022-04-08 11:27:48 0 [Note] InnoDB: Uses event mutexes
2022-04-08 11:27:48 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
(...)
2022-04-08 11:27:48 0 [Note] InnoDB: 10.5.15 started; log sequence number 45130; transaction id 20
2022-04-08 11:27:48 0 [Note] Plugin 'FEEDBACK' is disabled.
2022-04-08 11:27:48 0 [Note] InnoDB: Loading buffer pool(s) from /bitnami/mariadb/data/ib_buffer_pool
2022-04-08 11:27:48 0 [ERROR] /opt/bitnami/mariadb/sbin/mysqld: unknown variable 'this_is_a_wrong_parameter=1'
2022-04-08 11:27:48 0 [ERROR] Aborting
```

**Comment by pupseba** [comment]
This is awesome! Thank you very much!
