### ISSUE TITLE
https://github.com/bitnami/bitnami-docker-mariadb/issues

### ISSUE THREAD

**Issue by ankusjai** [bitnami/bitnami-docker-mariadb#275]
### Name and Version

bitnami/mariadb

### What steps will reproduce the bug?

mkdir: cannot create directory '/bitnami/mariadb/data': Permission denied
nrd-db-mariadb-0   1/2     CrashLoopBackOff   1 (7s ago)   12s
i am getting this error while deployting maria db on google plateform

### What do you see instead?

nrd-db-mariadb-0   1/2     CrashLoopBackOff   1 (7s ago)   12s
,mkdir: cannot create directory '/bitnami/mariadb/data': Permission denied

**Comment by javsalgar** [comment]
Hi,

Did you use the mariadb helm chart? Did you change any values?
