### ISSUE TITLE
TERM environment variable not set when executing mysql client

### ISSUE THREAD

**Issue by prydonius** [bitnami/bitnami-docker-mariadb#32]
Same issue as in dockerfile/mariadb#3. Should we add `ENV TERM dumb` to the Dockerfile?

**Comment by sameersbn** [comment]
Its worth noting that you do not face this after adding `-t` flag to the docker run command.

For example,

```bash
docker run -itd --name mariadb bitnami/mariadb
```

```bash
docker exec -it mariadb mysql
```

OR

```bash
docker exec -it mariadb top -d1
```

**Comment by chipironcin** [comment]
```
ubuntu@ip-172-31-37-157:~/test$ docker exec -it c6dc6ed79291 bash
root@c6dc6ed79291:/# /opt/bitnami/mysql/bin/mysql
TERM environment variable not set.
root@c6dc6ed79291:/#
```

**Comment by sameersbn** [comment]
@chipironcin works fine for me when the container is run with `-itd`

**Comment by chipironcin** [comment]
Oh yea, I thought setting the `-t` option on the run command was one of the possibilities.
You mean the container must be started with `-t` to avoid that problem.

Ok, we can add it to the documentation, but cannot we set the TERM env var and forget about that option?

**Comment by sameersbn** [comment]
@chipironcin Setting TERM in the Dockerfile should work. Some docker images seem to do it. 
I am not sure if there are cases where this could cause problems.

**Comment by jamesreimer** [comment]
Is there an equivilent to adding the -t flag when using docker compose or should I just add the env variable in docker-compose.yml?

**Comment by prydonius** [comment]
@jamesreimer, you can use:
```
tty: true
```
https://docs.docker.com/compose/compose-file/#cpu-shares-cpuset-domainname-entrypoint-hostname-ipc-mac-address-mem-limit-memswap-limit-privileged-read-only-restart-stdin-open-tty-user-working-dir

**Comment by juan131** [comment]
@sameersbn @prydonius I have seen this issue several times on different Bitnami Docker Images in the past. You mentioned that setting TERM in the Dockerfile should work. Should it be done at the minideb base image?

**Comment by prydonius** [comment]
@sameersbn what do you think? Any potential issues in setting TERM in the base image?

**Comment by sameersbn** [comment]
@juan131 @prydonius I would not recommend adding this to base image. In my experience I found that it can interfere with `apt-get` commands,

 f.e. 

```Dockerfile
FROM ubuntu:14.04
ENV TERM=xterm
RUN apt-get update && \
    apt-get install -y mysql-server
```

`TERM=xterm` in the above snippet causes the `mysql-server` package to prompt the user to enter a password at build time. An experienced user can easily remedy this by specifying `DEBIAN_FRONTEND=noninteractive` to the package installation commands.

There may be other cases where this variable can cause issues. I believe `TERM` is a runtime parameter and we should let the users activate it at runtime typically by specifying `-t` on the `docker run` command line.

**Comment by juan131** [comment]
@sameersbn from a user experience point of view I think it can be very disappointing to find the error:

```
TERM environment variable not set.
```

Make users specify `-t` on the docker run command line is not a good solution in my opinion. The user is free to run the Image on very different ways and he expects the Image to work without this weird errors.

Do you think that we could (at least) include it in the entrypoint?

**Comment by sameersbn** [comment]
@juan131 I cannot gauge the effect that defining this as a default can have. All I can tell is that there are close to zero images that do such a thing. If it were up to me, I would avoid defining this as a default at least until it's clearly understood the effect this variable can have. 

/cc @james-w do you have any thoughts on this matter?

> Do you think that we could (at least) include it in the entrypoint?

I was checking this out but unfortunately it appears that bitnami/minideb has some issues getting the `TERM` variable to have the desired effect, see: https://github.com/bitnami/minideb/issues/17

**Comment by james-w** [comment]
I'm not completely sure on this, but it seems like `export TERM=${TERM-dummy}` in mariadb's entrypoint would be the right place to handle it.

We could put it in the nami module, but if we don't use `nami start` for mariadb, would there be a place that it could inject it? I don't think so.

**Comment by juan131** [comment]
I agree with @james-w 
INMHO the MariaDB's entrypoint.sh is the right place to add it.

**Comment by mmikulicic** [comment]
This issue seems to be solved in recent docker (I didn't bisect to figure out in which version exactly).

BTW, if you add `export TERM=${TERM-dummy}` to the `entrypoint.sh` then that variable will be only present in subprocesses spawned by the entrypoint. If you run `docker exec .. /bin/bash` that variable won't be there.

Can we close this issue?

**Comment by juan131** [comment]
I think so @mmikulicic

Regarding adding the environment variable in the entrypoint.sh, you are right! We didn't realized that. Thanks for sharing it.  

I proceed too close the issue. Please reopen it if you find any corner case we didn't contemplate.
