### ISSUE TITLE
Default charset of MariaDB server 

### ISSUE THREAD

**Issue by hnq90** [bitnami/bitnami-docker-mariadb#47]
I found that default charset of MariaDB version10 is `latin1`, not `utf8` like version 5.x.
Please set default charset to `utf8`.

__my.cnf__ should be:
```
[mysqladmin]
user=

[mysqld]
skip-name-resolve=true
basedir=/opt/bitnami/mariadb
port=3306
socket=/opt/bitnami/mariadb/tmp/mysql.sock
tmpdir=/opt/bitnami/mariadb/tmp
max_allowed_packet=16M
bind-address=0.0.0.0
pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid
log-error=/opt/bitnami/mariadb/logs/mysqld.log
character-set-server=UTF8
collation-server=utf8_general_ci

[client]
port=3306
socket=/opt/bitnami/mariadb/tmp/mysql.sock
default-character-set=UTF8

[manager]
port=3306
socket=/opt/bitnami/mariadb/tmp/mysql.sock
pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid
```

Thank you in advance.

**Comment by hnq90** [comment]
I used MariaDB version 5 on my app before but after I upgraded to version 10, it broke my app (didn't display Japanese correctly).

**Comment by sameersbn** [comment]
@hnq90 we are reviewing the change.

**Comment by hnq90** [comment]
Okay, thank you.

On May 23 2016, at 12:11 pm, Sameer Naik &lt;notifications@github.com&gt;
wrote:  

> [@hnq90](https://github.com/hnq90) we are reviewing the change.

>

> —  
You are receiving this because you were mentioned.  
Reply to this email directly or [view it on GitHub](https://github.com/bitnami
/bitnami-docker-mariadb/issues/47#issuecomment-220888655)![](https://github.co
m/notifications/beacon/ABye0tt885Zq37RbYSZuntEWT2uqlyuLks5qETbvgaJpZM4Ih_Fq.gi
f)
