### ISSUE TITLE
Maria DB Error

### ISSUE THREAD

**Issue by swiftini** [bitnami/bitnami-docker-mariadb#50]
I have had an issue trying to install from Docker compose with persistent volumes mounted externally. My YML File looks like this:

version: '2'

services:
  mariadb:
    image: bitnami/mariadb:latest
    volumes:
      - ~/testwp/mariadata:/bitnami/mariadb
  wordpress:
    image: bitnami/wordpress:latest
    depends_on:
      - mariadb
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ~/testwp/wpdata:/bitnami/wordpress
      - ~/testwp/apache:/bitnami/apache

 I have tried reinstalling on a new VM from scratch but I keep getting an error after installation:

**mariadb_1    | harpoon ERROR Unable to start com.bitnami.mariadb: Cannot find pid file '/opt/bitnami/mariadb/tmp/mysqld.pid'.
testwp_mariadb_1 exited with code 1**

**Comment by hnq90** [comment]
Did you try to remove your volume first?
-- 
Huy Nguyen Quang

**Comment by sameersbn** [comment]
@swiftini can you provide the details of you environment like the host os, docker version, docker-machine, docker4mac beta, etc...

Can you try pulling the latest versions of the image from the dockerhub before retrying

```bash
docker pull bitnami/mariadb:latest
docker pull bitnami/wordpress:latest
```

Please share the complete output of the `docker-compose up` command.

**Comment by swiftini** [comment]
@hnq90 - I tried removing all the dangling volumes after removing all containers and I even set up a new docker-machine and pulled everything again. I also physically removed all the volume folders from my file system.

@sameersbn - 

I am running Mac Os X El capitan 10.11.4 with docker machine:

The version info for Docker is as follows:

Leifs-MacBook-Pro:/ leif$ docker version
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:44:17 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:20:08 2016
 OS/Arch:      linux/amd64

I am running docker machine having installed docker toolbox default settings:
`docker-machine version 0.7.0, build a650a40`




here is the output of the docker-compose up command:

`Creating testwp_mariadb_1
Creating testwp_wordpress_1
Attaching to testwp_mariadb_1, testwp_wordpress_1
mariadb_1    | harpoon INFO  Initializing mariadb
wordpress_1  | harpoon INFO  Initializing apache
wordpress_1  | harpoon INFO  apache successfully initialized
wordpress_1  | harpoon INFO  Initializing wordpress
mariadb_1    | mariadb INFO  ==> Creating 'root' user with unrestricted access...
mariadb_1    | mariadb INFO  ==> Flushing privileges...
mariadb_1    | mariadb INFO  ==> Enabling remote connections...
mariadb_1    | mariadb INFO 
mariadb_1    | mariadb INFO  ########################################################################
mariadb_1    | mariadb INFO   Installation parameters for mariadb:
mariadb_1    | mariadb INFO     Password: Not set during installation
mariadb_1    | mariadb INFO   (Passwords are not shown for security reasons)
mariadb_1    | mariadb INFO  ########################################################################
mariadb_1    | mariadb INFO 
mariadb_1    | harpoon INFO  mariadb successfully initialized
mariadb_1    |        ___ _ _                   _
mariadb_1    |       | _ |_) |_ _ _  __ _ _ __ (_)
mariadb_1    |       | _ \ |  _| ' \/ _` | '  \| |
mariadb_1    |       |___/_|\__|_|_|\__,_|_|_|_|_|
mariadb_1    | 
mariadb_1    |   *** Welcome to the mariadb image ***
mariadb_1    |   *** More information: https://github.com/bitnami/bitnami-docker-mariadb ***
mariadb_1    |   *** Issues: https://github.com/bitnami/bitnami-docker-mariadb/issues ***
mariadb_1    | 
mariadb_1    | 
mariadb_1    | *** Your container is up to date! ***
mariadb_1    | 
mariadb_1    | harpoon ERROR Unable to start com.bitnami.mariadb: Cannot find pid file '/opt/bitnami/mariadb/tmp/mysqld.pid'.
testwp_mariadb_1 exited with code 1`

**Comment by swiftini** [comment]
@sameersbn @hnq90 - thanks for the quick response:

I did pull the latest versions of maria db and wordpress before running docker-compose up again

**Comment by sameersbn** [comment]
@swiftini The issue is due to VirtualBox shared folders. When you mount a volume from the host (from `$HOME`) to the container, docker-machine sets up a shared directory between the host and container in virtualbox.

The shared volume is not suitable for hosting MariaDB data. One of the issues is permissions cannot be set for files and folders in these shared directories the unix way. 

You can instead use docker volumes as demonstrated in https://github.com/bitnami/bitnami-docker-wordpress#using-docker-compose.

This will also work

```yaml
version: '2'
services:
  mariadb:
    image: bitnami/mariadb:latest
    volumes:
    - /srv/wordpress/mariadata:/bitnami/mariadb
  wordpress:
    image: bitnami/wordpress:latest
    depends_on:
    - mariadb
    ports:
    - '10080:80'
    volumes:
    - /srv/wordpress/wpdata:/bitnami/wordpress
    - /srv/wordpress/apache:/bitnami/apache
```

Here volumes are not mounted from the host, `/srv/..` is a path is in the docker-machine vm.

**Comment by swiftini** [comment]
@sameersbn thanks for the feedback. The truth is that I don't need the db mounted outside the container, only the WP files. Thanks again for being so responsive - you guys rock.

**Comment by sameersbn** [comment]
I think you should not face issues with having wordpress files on the host.

**Comment by sameersbn** [comment]
please let us know if you face any issues or have suggestions for improving the image
