### ISSUE TITLE
MARIADB_MASTER_PORT is failing to configure custom master port.

### ISSUE THREAD

**Issue by v00rh33s** [bitnami/bitnami-docker-mariadb#55]
Hi, when trying to use the MARIADB_MASTER_PORT option on slave servers, the default 3306 is always used when the container is running. In compose the configuration option is set like this:

`- MARIADB_MASTER_PORT=3309`
    
But in the logs the slave is still connecting to master on port 3306:

`2016-08-01  0:19:57 140347877411584 [ERROR] Slave I/O: error connecting to master 'user1_repl@10.0.0.2:3306' - retry-time: 60  retries: 86400  message: Access denied for user 'user1_repl'@'10.0.0.3' (using password: YES), Internal MariaDB error code: 1045`

**Comment by sameersbn** [comment]
@v00rh33s thanks for reporting the issue. We'll keep you posted.

**Comment by sameersbn** [comment]
FYI, The fix for this issue is queued in #57

**Comment by sameersbn** [comment]
Hi. `bitnami/mariadb:10.1.14-r3` is out with the fix. :smile:

**Comment by v00rh33s** [comment]
Thanks @sameersbn! Confirmed it has resolved the issue.
