### ISSUE TITLE
Can't enable TokuEngine.  - TokuDB is not initialized because jemalloc is older than 2.3.0 

### ISSUE THREAD

**Issue by udomsak** [bitnami/bitnami-docker-mariadb#70]
# Problem
- Can't enable TokuDB engine.
- Log  

```
TokuDB is not initialized because jemalloc is older than 2.3.0
```
# Docker image
-  10.1.17-mariadb  
# Try & Environment
- install jemalloc and lib-dev sometime work and sometime not work not sure what happen  
- Disable linux huge page transparent 
- Load plugin with  'my.cnf'  ( not work ) 
- Load plugin from mysql shell  ( sometime work and not work )

**Comment by chipironcin** [comment]
Hi @udomsak 
I checked and we are shipping `libjemalloc.v.3.6.0` so it should be a parsing error on 'TokuDB' side. This occurred before, check this bug report:
https://tokutek.atlassian.net/browse/DB-939

It seems they added a parameter to skip that check.

We are trying to find how to do that and will document in the main README.md for this repo. Thanks for reporting the issue, will get back to you once we solve it.

Also, you would need to have Linux huge page transparent disabled in your host, as it is a kernel parameter not configurable from inside the container.

**Comment by chipironcin** [comment]
Tracking the issue in PR #82

**Comment by chipironcin** [comment]
@udomsak can you check now?
Make sure of pulling the latest image:

```
docker pull bitnami/mariadb:latest
```

To enable TokuDB you can follow this guide:
http://www.chriscalender.com/enabling-tokudb-in-mariadb-is-a-breeze/

Tell us if it worked for you ;)
Cheers!

**Comment by prydonius** [comment]
@udomsak please reopen this issue if you have issues with enabling TokuDB now, thanks!
