### ISSUE TITLE
Redeploy master on new machine

### ISSUE THREAD

**Issue by theindra** [bitnami/bitnami-docker-mariadb#78]
How can i start a new master-container on a new machine and tell it to sync the data from the (old) slaves?

Situation:
When the node were i deploy the master-container fails. How can i do a failover to have a new master-container on an other node? Does one the slave-containers switch to master-mode?

**Comment by sameersbn** [comment]
You can convert an existing node to become a master. However, this has to be done manually using these steps:

1. Using the `mysql` client, login to the slave as `root` user
2. Stop the streaming replication by executing the following admin commands:

```sql
STOP SLAVE;
RESET SLAVE ALL;
```

3. Exit the mysql prompt and stop the slave node
4. Start the container again with `-e MARIADB_REPLICATION_MODE=master`. The node will no longer be in read-only mode, effectively coming a master node and accepting writes.
5. Setup slave nodes to use the new master.

NOTE: 
The above sequence of commands assumes that the existing slave is using persistent storage. If this is not the case, you can first set up a new slave with persistent storage and use one of the existing slaves as its master. After the initial data has been replicated on the new slave, you can perform the above commands to promote it to become the master.

**Comment by theindra** [comment]
For docker cloud it would be create if there is a automatic fail over. 
Or any script in the container itself that i can easily start from docker cloud.

Whats the best method to switch back to the desired master? Do i have to start the desired container as slave to sync it and then shutdown the current master and do the steps described by you with my desired slave container?

**Comment by sameersbn** [comment]
> For docker cloud it would be create if there is a automatic fail over. 
>  Or any script in the container itself that i can easily start from docker cloud.

We would like to be able to perform automatic failovers. We're are considering the possibilities of such a system. We want to be very careful while dealing with user data.

> Whats the best method to switch back to the desired master? Do i have to start the desired container as slave to sync it and then shutdown the current master and do the steps described by you with my desired slave container?

Exactly.

**Comment by prydonius** [comment]
@theindra did you have any more questions related to this, or can we close this issue out?

**Comment by theindra** [comment]
I didn't test it, but it's clear now. 
Thank you
