### ISSUE TITLE
Performance issue compared to mysql

### ISSUE THREAD

**Issue by theindra** [bitnami/bitnami-docker-mariadb#80]
I setup a mariadb-replication cluster using this docker image with 1 master and 1 slave node.
And i migrated my data from an mysql installation that didn't use docker and is not setup in replication mode.

In both i have the same table with approx 1GB data.

When i execute this statement:
SELECT COUNT(*) FROM test_table

I get this performance results:
> MariaDB cluster master:  33,438 sec.
> MariaDB cluster slave:  33,734 sec.
> MySQL without docker and without replication: 1,328 sec.

Do you have any suggestion why i have such a big difference in performance. That more than 25 times slower than the old mysql setup.

**Comment by prydonius** [comment]
Hi @theindra, this could be an issue with your Docker setup. For example, if your Docker host is different to your host OS, and you're mounting volumes, disk performance can suffer.

If you are comparing MySQL on the same host as your Docker host, there may be other things you could look into, such as different mysql options.

**Comment by theindra** [comment]
I checked os version. This docker image uses ubuntu 14 and the host has installed ubuntu 16!
Could this cause performance issues? 
I guess the best option is to build the image by my self with ubuntu 16 as base image?

I use the default config of this image. Is there any recommended setting to avoid such a bad performance?

**Comment by prydonius** [comment]
@theindra what I meant was if you were running a non-linux OS and connecting to a Linux Docker host, but that doesn't sound like the case for you.

Can you compare the default config of this image and default config for the locally installed mysql?

**Comment by theindra** [comment]
Ok... Thanks for the tip.

I compared the config and copied the following lines from my original mysql config to the mariadb-config:

```
#
# Fine Tuning
#
key_buffer_size         = 64M
max_allowed_packet      = 64M
thread_stack            = 192K
thread_cache_size       = 8
query_cache_limit       = 1M
query_cache_size        = 16M
expire_logs_days        = 30
max_binlog_size         = 100M
innodb_buffer_pool_size = 2000M
innodb_log_file_size    = 1024M
```

Now the same query as above takes: 2,359 sec
It's not so fast than the old mysql installation but by far better than the default config of this image.

Actually i expected a optimized config when using this image. I didn't thought that i have to tune it by myself.

Maybe someone with experience on tuning mariadb could add a good default config for this image. 
The current one is not production ready.

**Comment by sameersbn** [comment]
@theindra your configuration reserve large amounts of RAM in `innodb_buffer_pool_size`. This would indicate the speedup in SQL query.

We cannot impose such large RAM requirements on the image by default. We expect users to fine tune these params according to their requirements.
