### ISSUE TITLE
Can't add my_custom.cnf to image

### ISSUE THREAD

**Issue by theindra** [bitnami/bitnami-docker-mariadb#81]
Hi, i want to add my_custom.cnf to the mariadb image.

I made my own docker file with this image as base image. 
Then i used this line to copy my settings to the image:
`ADD my_custom.cnf /bitnami/$BITNAMI_APP_NAME/conf`

The build works fine but when i try to start the image now i get this error:

> Error executing 'postInstallation': ENOTDIR: not a directory, rename '/opt/bitnami/mariadb/conf/my.cnf' -> '/bitnami/mariadb/conf/my.cnf'

How can i add my custom configuration to the image without breaking it?
I don't want to need put it into the volume on the node, because not all devs have access to the nodes. And so it custom config is versioned in git.

**Comment by prydonius** [comment]
The issue is that `/bitnami/mariadb/conf` must be a directory, and the custom config should be in that directory. The `ADD` command is creating a file called `/bitnami/mariadb/conf` with the content of `my_custom.cnf`.

To correct it, you just need to end your line with a trailing slash:
`COPY my_custom.cnf /bitnami/$BITNAMI_APP_NAME/conf/`

Also, it's recommended to use `COPY` instead of `ADD` for local files.

**Comment by theindra** [comment]
Thank you for that hint. 
I fixed the image and it works as long as i don't try to map the volume /bitnami/mariadb to a directory on host.

Without volume mapping:
`docker run -d myrepo/mariadb:10.1.18`
Result:
`docker exec dreamy_booth ls /bitnami/mariadb/conf
my.cnf
my_custom.cnf
`

Without volume mapping:
`docker run -v /myrepo/mariadb-test:/bitnami/mariadb -d myrepo/mariadb:10.1.18`
Result:
`docker exec cranky_lamarr ls /bitnami/mariadb/conf
my.cnf
`

Any ideas why i loose my custom config when mapping the volume?

**Comment by theindra** [comment]
I was able to fix it by copying the file to this directory:
/opt/bitnami/mariadb/conf

**Comment by chipironcin** [comment]
Thanks @theindra 
We are going to improve the documentation on this 👍

**Comment by theindra** [comment]
Found out that this would only copy the config when initialyzing the database.

I tried to copy the file in my-entrypoint.sh. But when i try to call your entrypoint script it tells me that it doesn't have PID 1.

I also tried executing startup.sh with a CMD statement in Dockerfile

The startup.sh copies the new configfile to correct place and then calls 
`nami start --foreground .....`
But this also doesn't work.

I think the problem is that the config-file is in the volume. I want to deploy my config-changes by pushing a new image and not by copying the config to the hosts where the containers are running.

Any ideas how i can do this?

**Comment by sameersbn** [comment]
> entrypoint script it tells me that it doesn't have PID 1
can you try using `exec` to call the `app-entrypoint.sh` script from `my-entrypoint.sh`?

**Comment by prydonius** [comment]
@theindra were you able to try @sameersbn's suggestion?

**Comment by theindra** [comment]
No i tried a different way. I copied my my_custom.cnf to  /opt/bitnami/mariadb/conf/
